### ISSUE TITLE
15_autoencoders.ipynb PCA with a linear Autoencoder Section

### ISSUE THREAD

**Issue by akellyirl** [ageron/handson-ml#106]
The calls to numpy.random require an import to work. As they are now they are broken.
i.e.

**import numpy.random as rnd**

rnd.seed(4)
m = 200
w1, w2 = 0.1, 0.3
noise = 0.1

angles = rnd.rand(m) * 3 * np.pi / 2 - 0.5
data = np.empty((m, 3))
data[:, 0] = np.cos(angles) + np.sin(angles)/2 + noise * rnd.randn(m) / 2
data[:, 1] = np.sin(angles) * 0.7 + noise * rnd.randn(m) / 2
data[:, 2] = data[:, 0] * w1 + data[:, 1] * w2 + noise * rnd.randn(m)

**Comment by akellyirl** [comment]
Created Pull Request.

**Comment by ageron** [comment]
Thanks a lot, I merged your PR.
