### ISSUE TITLE
The 5 detector predicting wrong. Please help me to debug the issue.

### ISSUE THREAD

**Issue by ajanac** [ageron/handson-ml#108]
https://github.com/ajanac/5-detector-Classifier/blob/master/MNIST.ipynb

**Comment by ajanac** [comment]
I have no idea why it is giving a false value for the prediction.

**Comment by ageron** [comment]
Classifiers are rarely perfect.  Can you try testing it on the full test set and measure the accuracy? Even if it's as high as 99%, it still means that you have a 1% chance that it will make an error on any given instance.  Moreover, random number generators are not guaranteed to produce the same sequence (even given the same seed) on different machines, so it's quite possible that the same exact code with the same random seed will produce two different classifiers on two different machines.

Hope this helps.
