### ISSUE TITLE
dimension reduction 2d plane equation

### ISSUE THREAD

**Issue by wwshunan** [ageron/handson-ml#110]
Hi, where is the following equations for z from:
C = pca.components_
R = C.T.dot(C)
z = (R[0, 2] * x1 + R[1, 2] * x2) / (1 - R[2, 2])
Would you give me some reference? Thank you.

**Comment by wwshunan** [comment]
I know how to get it, just transform to the 2d plane and make a inverse transform.

**Comment by ageron** [comment]
Hi @wwshunan , I'm glad you found the answer.
