### ISSUE TITLE
RNN `DropoutWrapper` can avoid dropout during testing

### ISSUE THREAD

**Issue by shengc** [ageron/handson-ml#111]
Reading the documentation, all three dropout parameters, i.e., `input_keep_prob`, `output_keep_prob`, and `state_keep_prob` can be tensors. This means they can be given different values as `tf.placeholder` in training and testing. The idea is like the following,

```python
  input_keep_prob = tf.placeholder_with_default(tf.constant(1.0, dtype=tf.float32), ())
  output_keep_prob = tf.placeholder_with_default(tf.constant(1.0, dtype=tf.float32), ())
  state_keep_prob = tf.placeholder_with_default(tf.constant(1.0, dtype=tf.float32), ())
  
  # DropoutWrapper
  ..
  cell = DropoutWrapper(lstm_cell, input_keep_prob=input_keep_prob, output_keep_prob=output_keep_prob, state_keep_prob=state_keep_prob)

  # training
  sess.run(..., feed_dict={input_keep_prob:0.8, ...})
  # testing
  # during testing just leave *_keep_prob out of feed_dict, and they will default to 1.0 (do not apply drop out)
  sess.run(..., feed_dict={...})
```

**Comment by ageron** [comment]
Hi @shengc ,
Excellent point, I didn't notice that the parameters could be tensors instead of floats.  I'll update the notebook and the book to use your solution, it's definitely simpler using dropout with RNNs. :)
Thanks!
