### ISSUE TITLE
Bug of code in the book

### ISSUE THREAD

**Issue by JeffreyYafeiHu** [ageron/handson-ml#120]
Never mind, I think it's fixed in the latest edition

**Comment by ageron** [comment]
Yes, despite all my efforts, there were some errors in the first printed version of the book (see the [errata page](http://www.oreilly.com/catalog/errata.csp?isbn=0636920052289)). Most were minor, but there were a few significant ones. I have fixed them in the book as well as in the notebooks. The digital and printed versions have been updated (the latest update was done earlier this week). Hopefully there are no significant errors left, but if you find some more, please don't hesitate to report them here on via the errata page above.
Thanks!
