### ISSUE TITLE
What's the best place to purchase the eBook (i.e. PDF and EPub)?

### ISSUE THREAD

**Issue by conradwt** [ageron/handson-ml#122]
Hi, I was wondering, what's the best place to purchase the PDF and EPub versions of the book that are not connected to one of the many different services (i.e. Safari Books Online and so on) and doesn't require an application?

**Comment by ziembla** [comment]
Hi,

yes that's really a shame that you can't just buy a book at OReilly's any more. Fortunately I've managed to grab my copy before they joined the dark side :-D

Still, there seem to be some resellers whom you can still by an ebook from.

I've checked that you can buy a copy from Polish publisher "Helion" for instance.

https://helion.pl/ksiazki/hands-on-machine-learning-with-scikit-learn-and-tensorflow-concepts-tools-and-techniques-to-build-aur-lien-g-ron,e_0gvu.htm

That's the biggest Polish computer-related publisher which is, among other things, translating many OReilly books for like 20 years or something. I've never bought an English version OReilly ebook from them, but had bought some others. All of these have been DRM-free so I can read them on any of my devices, still they are "watermarked" with "licensed for <your email>" on every page (PDFs at least). Still, it looks that there's only an EPUB there no PDF version. And the problem for you might be that there seems to be only a Polish language version of the site. I could help in translation if need be, but as I can see there also some "English-speking" resellers as linked below, but I have no experience with them.

https://www.booktopia.com.au/ebooks/hands-on-machine-learning-with-scikit-learn-and-tensorflow-aur-lien-g-ron/prod9781491962244.html

Regards

**Comment by ageron** [comment]
Thanks for your question @conradwt , and thanks for your answer @ziembla . :)  I'll ask O'Reilly where else the book can be bought.

**Comment by ziembla** [comment]
In case anyone's listening... I think it won't be any disservice to Aurelien to say that (for some time at least, just got the info in the oreilly's newsletter) you can now get a free copy in return for filling up a questionnaire at oreilly's... Just sayin'
<www.oreilly.com/ai/fighting-financial-crime-survey.html>

**Comment by ageron** [comment]
O'Reilly told me that a good place to purchase the ebook is here:
https://www.ebooks.com/95727996/hands-on-machine-learning-with-scikit-learn-and-tensorflow/g%C3%A9ron-aur%C3%A9lien/
