### ISSUE TITLE
Ch. 2 Problem 5 Question

### ISSUE THREAD

**Issue by stingram** [ageron/handson-ml#126]
I'm looking at the code for your solution to Ch.2, question 5 and I don't understand the name constraint on the param_grid variable.

I notice that if I change 'preparation__num_pipeline__imputer__strategy' to some other string or if I change 'feature_selection__k' to some other string, then calling grid_search_prep.fit(housing, housing_labels) will produce errors.

Why does this happen? I don't understand how I would know what specific strings I need in the param_grid variable. I'm worried I won't be able to extrapolate from this solution and use it to create my own custom GridSearchCV calls because I won't know what names to put into param_grid.

**Comment by ageron** [comment]
Hi @stingram , great question!

When you create a `Pipeline`, you give each step a name, for example:

```python
prepare_select_and_predict_pipeline = Pipeline([
    ('preparation', full_pipeline),
    ('feature_selection', TopFeatureSelector(feature_importances, k)),
    ('svm_reg', SVR(**rnd_search.best_params_))
])
```

The only hard constraint for the names is that they must not contain double underscores, but it's also a good idea to format them like regular Python identifiers (no spaces or special characters, do not start with a digit, and so on, we will see why below). So here, I chose to name them `"preparation"`, `"feature_selection"` and `"svm_reg"`. Now, suppose you want to modify one of the hyperparameters of one of these steps, for example you want to set the SVR's kernel to "rbf". One approach would be to first get a handle on the estimator for that step, then modify the hyperparameter, like this:

```python
prepare_select_and_predict_pipeline.named_steps["svm_reg"].kernel = "rbf"
```

Another approach is to use a "magical" naming scheme implemented by the `Pipeline` object:

```python
prepare_select_and_predict_pipeline.svm_reg__kernel = "rbf"
```

The `Pipeline` object automatically parses the attribute, it sees the double underscores, and it understands what you are trying to do: in this example, access the estimator of the step named `"svm_reg"`, and modify its hyperparameter called `"kernel"`.

There can actually be nested `Pipeline` object, which explains the name `"preparation__num_pipeline__imputer__strategy"`. The following lines are equivalent:

```python
prepare_select_and_predict_pipeline.preparation__num_pipeline__imputer__strategy = "mean"
prepare_select_and_predict_pipeline.named_steps["preparation"].num_pipeline__imputer__strategy = "mean"
prepare_select_and_predict_pipeline.named_steps["preparation"].named_steps["num_pipeline"].imputer__strategy = "mean"
prepare_select_and_predict_pipeline.named_steps["preparation"].named_steps["num_pipeline"].named_steps["imputer"].strategy = "mean"
```

So the following code will perform a grid search on two hyperparameters: the strategy of the imputer and the `k` hyperparameter of the feature selection object:
```python
param_grid = [
        {'preparation__num_pipeline__imputer__strategy': ['mean', 'median', 'most_frequent'],
         'feature_selection__k': [3, 4, 5, 6, 7]}
]
grid_search_prep = GridSearchCV(prepare_select_and_predict_pipeline, param_grid, cv=5,
                                scoring='neg_mean_squared_error', verbose=2, n_jobs=4)
grid_search_prep.fit(housing, housing_labels)
```

I hope this helps,
Aurélien
