### ISSUE TITLE
Stacked Denoising Autoencoders code

### ISSUE THREAD

**Issue by sarmadm** [ageron/handson-ml#128]
HI

Sorry for my question . I couldn't find your email .

I have question about Stacked Denoising Autoencoders code , what is the difference between your 

implementation of Stacked Denoising Autoencoders and the implementation of 

http://deeplearning.net/tutorial/SdA.html .  ?

**Comment by ageron** [comment]
Hi @sarmadm ,

I'm guessing it's roughly the same thing, except they're using Theano and I'm using TensorFlow.  Did you notice an important difference?

**Comment by sarmadm** [comment]
Thanks very much for answering . 
But why when I change the output in stacked denoising auto-encoder  to any number (eg  :n_outputs = 30)
 It shows error ( ValueError: Dimensions must be equal, but are 30 and 784 for 'sub' (op: 'Sub') with input shapes: [?,30], [?,784].) 

I think the output can be of any diemension, right ?
while in http://deeplearning.net/tutorial/SdA.html , the output can be changed to any number ?

**Comment by ageron** [comment]
Oh, I see.  What they call the _output_ of the Denoising Autoencoder (DA) is what I call the hidden layer's output (it is also called the _coding layer_).  For example, consider a DA with one input layer of size 784, then one hidden layer of size 30, and finally one output layer of size 784.  In an Autoencoder, we try to train the network so that its outputs reproduces the inputs, so they must have the same size (in this example, 784).  But you can change the size of the coding layer as you please (usually, you want it to be smaller than the input & output layer size). For example, you could resize the coding layer from 30 to 50.
Hope this helps.

**Comment by sarmadm** [comment]
Thanks very much again ,

Using stacked denoising code I need to read my data from csv file not images  and produce output of 

into another csv given the accuracy of the compact output features compared to input features . 

`from __future__ import division, print_function, unicode_literals

# Common imports
import numpy as np
import os
import sys
import tensorflow as tf
import pandas as pd

from tensorflow.examples.tutorials.mnist import input_data
mnist = input_data.read_data_sets("/tmp/data/")



n_inputs = 784
n_hidden1 = 300
n_hidden2 = 150  # codings
n_hidden3 = n_hidden1
n_outputs = n_inputs

learning_rate = 0.01




noise_level = 1.0

X = tf.placeholder(tf.float32, shape=[None, n_inputs])
X_noisy = X + noise_level * tf.random_normal(tf.shape(X))

hidden1 = tf.layers.dense(X_noisy, n_hidden1, activation=tf.nn.relu,
                      name="hidden1")
hidden2 = tf.layers.dense(hidden1, n_hidden2, activation=tf.nn.relu, # not 
shown in the book
                      name="hidden2")                            # not shown
hidden3 = tf.layers.dense(hidden2, n_hidden3, activation=tf.nn.relu, # not shown
                      name="hidden3")                            # not shown
outputs = tf.layers.dense(hidden3, n_outputs, name="outputs")        # not shown

reconstruction_loss = tf.reduce_mean(tf.square(outputs - X)) # MSE

optimizer = tf.train.AdamOptimizer(learning_rate)
training_op = optimizer.minimize(reconstruction_loss)

init = tf.global_variables_initializer()
saver = tf.train.Saver()

n_epochs = 10
batch_size = 150




with tf.Session() as sess:
   init.run()
      for epoch in range(n_epochs):
          n_batches = mnist.train.num_examples // batch_size
          for iteration in range(n_batches):
          print("\r{}%".format(100 * iteration // n_batches), end="")
          sys.stdout.flush()
          X_batch, y_batch = mnist.train.next_batch(batch_size)
          sess.run(training_op, feed_dict={X: X_batch})
      loss_train = reconstruction_loss.eval(feed_dict={X: X_batch})
      print("\r{}".format(epoch), "Train MSE:", loss_train)`

**Comment by ageron** [comment]
Hi @sarmadm ,
I just ran your code, and I got this output:

```
0 Train MSE: 0.0430786
1 Train MSE: 0.0406427
2 Train MSE: 0.0387867
3 Train MSE: 0.0377221
4 Train MSE: 0.0384901
5 Train MSE: 0.0367403
6 Train MSE: 0.0377636
7 Train MSE: 0.0382239
8 Train MSE: 0.0379851
9 Train MSE: 0.0367461
```

It looks like it's learning correctly.  Could you please clarify your question, I'm not sure I see what problem you are trying to fix.  In fact, could you please tell me more generally what your project is and what you are trying to do?

**Comment by sarmadm** [comment]
HI @ageron 

I'm trying to do the following 

![image](https://user-images.githubusercontent.com/14107864/34920626-6a91d1c8-f96d-11e7-99dd-4bda82b655ea.png)

**Comment by sarmadm** [comment]
Hi , you have any idea about this ?

**Comment by ageron** [comment]
Hi @sarmadm ,
I'm guessing it should be possible, yes, but to be honest I don't have enough time to try it out.  I'd be curious to know if you make it work, though.
Cheers,
Aurélien
