### ISSUE TITLE
Problem with server extensions

### ISSUE THREAD

**Issue by rodrigo-toledo** [ageron/handson-ml#13]
Im having this problem, im new using jupyter and don't know what info could be relevant for the issue, please let me know if there's any extra data I can provide:
[W 19:07:07.908 NotebookApp] server_extensions is deprecated, use nbserver_extensions
[W 19:07:08.549 NotebookApp] Error loading server extension jupyter_nbextensions_configurator

**Comment by ageron** [comment]
The notebook extensions are just nice to have, but if you are experiencing difficulties installing them, you can just ignore them (they're mostly to have nice table of contents, that's all).

If you want to use them, can you please give me more information about your system (O.S., python version, using pip or anaconda? etc.)?
Did you follow the [installation instructions](https://github.com/ageron/handson-ml#installation)?

**Comment by rodrigo-toledo** [comment]
Sure, thanks for the quick response. I followed the instructions yes, maybe it has something to do with having jupyter previously installed outside virtualenv?
This is my history:

1. virtualenv env
2. source ./env/bin/activate
3. pip3 install --upgrade -r requirements.txt
4. jupyter contrib nbextension install --user
5. jupyter nbextension enable toc2/main
6. jupyter notebook index.ipynb

**Comment by rodrigo-toledo** [comment]
Well, I don't know what fixed it but I fixed it. Tried many things like installing jupyter_nbextensions_configurator from github and also updating all pip packages.

**Comment by ageron** [comment]
Great! Thanks for letting me know. Enjoy the book.
