### ISSUE TITLE
typo in chapter 9?

### ISSUE THREAD

**Issue by vd1** [ageron/handson-ml#131]
Near the beginning of chapter 9 (the intro to NN)  there is this sentence: "It provides several advanced optimization nodes to search for the parameters that minimize a cost function." Did you mean perhaps "modes" instead of "nodes"?

Thanks for the great book!

**Comment by ageron** [comment]
Thanks for your feedback Vincent! I did mean node, in the sense that TensorFlow will create nodes in the computation graph to minimize the model's loss, but I agree that it's not very clear. I should have written that TensorFlow provides many different optimizers. :)
I'll try to rephrase this for future editions.
Thanks again!
