### ISSUE TITLE
  Traceback (most recent call last)

### ISSUE THREAD

**Issue by sa1lor** [ageron/handson-ml#134]
I have revisited my file after a few weeks, still on page 59 and I got several issues.

- First off, even though the file is saved each time I have to rerun all the cells in order to be able to run the next one
- But last time the graphs are not shown anymore, I get msgs like the following: <matplotlib.axes._subplots.AxesSubplot at 0x27da2288ef0>
- also the lines  on page 59 dont seem to work, I receive 100 lines of error msgs: 
TypeError                                 Traceback (most recent call last)
E:\Szemelyes\Python\Anaconda3\envs\mlbook\lib\site-packages\pandas\core\ops.py in na_op(x, y)
    657             result = expressions.evaluate(op, str_rep, x, y,
--> 658                                           raise_on_error=True, **eval_kwargs)
    659         except TypeError:

E:\Szemelyes\Python\Anaconda3\envs\mlbook\lib\site-packages\pandas\core\computation\expressions.py in evaluate(op, op_str, a, b, raise_on_error, use_numexpr, **eval_kwargs)
    210         return _evaluate(op, op_str, a, b, raise_on_error=raise_on_error,
--> 211                          **eval_kwargs)
    212     return _evaluate_standard(op, op_str, a, b, raise_on_error=raise_on_error)

E:\Szemelyes\Python\Anaconda3\envs\mlbook\lib\site-packages\pandas\core\computation\expressions.py in _evaluate_numexpr(op, op_str, a, b, raise_on_error, truediv, reversed, **eval_kwargs)
    121     if result is None:
--> 122         result = _evaluate_standard(op, op_str, a, b, raise_on_error)
    123 

E:\Szemelyes\Python\Anaconda3\envs\mlbook\lib\site-packages\pandas\core\computation\expressions.py in _evaluate_standard(op, op_str, a, b, raise_on_error, **eval_kwargs)
     63     with np.errstate(all='ignore'):
---> 64         return op(a, b)
     65 

E:\Szemelyes\Python\Anaconda3\envs\mlbook\lib\site-packages\pandas\core\ops.py in <lambda>(x, y)
     96                           default_axis=default_axis, reversed=True),
---> 97         rtruediv=arith_method(lambda x, y: operator.truediv(y, x),
     98                               names('rtruediv'), op('/'), truediv=True,

TypeError: ufunc 'true_divide' not supported for the input types, and the inputs could not be safely coerced to any supported types according to the casting rule ''safe''

During handling of the above exception, another exception occurred:

TypeError                                 Traceback (most recent call last)
<ipython-input-32-023a7d2c1869> in <module>()
      1 housing["rooms_per_household"] = housing["total_rooms"]/housing["households"]
      2 housing["bedrooms_per_room"] = housing["total_bedrooms"]/housing["total_rooms"]
----> 3 housing["population_per_household"] = ["population"]/housing["households"]

E:\Szemelyes\Python\Anaconda3\envs\mlbook\lib\site-packages\pandas\core\ops.py in wrapper(left, right, name, na_op)
    719                 lvalues = lvalues.values
    720 
--> 721         result = wrap_results(safe_na_op(lvalues, rvalues))
    722         return construct_result(
    723             left,

E:\Szemelyes\Python\Anaconda3\envs\mlbook\lib\site-packages\pandas\core\ops.py in safe_na_op(lvalues, rvalues)
    680         try:
    681             with np.errstate(all='ignore'):
--> 682                 return na_op(lvalues, rvalues)
    683         except Exception:
    684             if isinstance(rvalues, ABCSeries):

E:\Szemelyes\Python\Anaconda3\envs\mlbook\lib\site-packages\pandas\core\ops.py in na_op(x, y)
    666                 result = np.empty(len(x), dtype=x.dtype)
    667                 mask = notnull(x)
--> 668                 result[mask] = op(x[mask], y)
    669             else:
    670                 raise TypeError("{typ} cannot perform the operation "

E:\Szemelyes\Python\Anaconda3\envs\mlbook\lib\site-packages\pandas\core\ops.py in <lambda>(x, y)
     95         rsub=arith_method(lambda x, y: y - x, names('rsub'), op('-'),
     96                           default_axis=default_axis, reversed=True),
---> 97         rtruediv=arith_method(lambda x, y: operator.truediv(y, x),
     98                               names('rtruediv'), op('/'), truediv=True,
     99                               fill_zeros=np.inf, default_axis=default_axis,

TypeError: ufunc 'true_divide' not supported for the input types, and the inputs could not be safely coerced to any supported types according to the casting rule ''safe''

I thought to go through this book with having the same outputs as in there by following everything letter by letter.. :(

**Comment by ageron** [comment]
Hi @sa1lor ,
I see that the error occurs on this line:
```python
housing["population_per_household"] = ["population"]/housing["households"]
```
It should be:
```python
housing["population_per_household"] = housing["population"]/housing["households"]
```
Make sure you use the exact same code as in the Jupyter notebook in this project.
Hope this helps.

**Comment by sa1lor** [comment]
Many thanks

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

________________________________

**Comment by dineshacharya2000** [comment]
Hi Guys, I have just installed Anaconda Python 3.6 and am facing a peculiar problem. I get this following error. Please assist.
>>> from urllib.request import urlopen as uReq
>>> from bs4 import BeautifulSoup as soup
>>> my_url='https://www.amazon.com'
>>> uClient=uReq(my_url)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\dines\Anaconda3\lib\urllib\request.py", line 223, in urlopen
    return opener.open(url, data, timeout)
  File "C:\Users\dines\Anaconda3\lib\urllib\request.py", line 532, in open
    response = meth(req, response)
  File "C:\Users\dines\Anaconda3\lib\urllib\request.py", line 642, in http_response
    'http', request, response, code, msg, hdrs)
  File "C:\Users\dines\Anaconda3\lib\urllib\request.py", line 570, in error
    return self._call_chain(*args)
  File "C:\Users\dines\Anaconda3\lib\urllib\request.py", line 504, in _call_chain
    result = func(*args)
  File "C:\Users\dines\Anaconda3\lib\urllib\request.py", line 650, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 503: Service Unavailable
>>>

**Comment by ageron** [comment]
Hi @dineshacharya2000 ,
I think you may have posted your question in the wrong place: it seems to have nothing to do with this project. Perhaps post it on StackOverflow.com instead.
I tried running your code, and I got the same error. But if you replace amazon.com by amazon.fr, then it works fine.  So I'm guessing amazon.com has a special server-side protection against robots, and it detects that this is a simple script.
