### ISSUE TITLE
Valid padding in CapNets

### ISSUE THREAD

**Issue by phongnhhn92** [ageron/handson-ml#136]
Hello sir,
I am following the Capsule Network paper and your implementation.
I have a quick question about the valid padding in the conv2 you used to get output for the Primary Caps. So as I understand, after the 1st conv layer, the size of output is (batchsize,20,20,256). So if the conv2 has 256, 9x9 kernel, stride 2 then the formula output should be (20-9+2*p)/2+1 = 6. However, mathematically, the formula above can not be solved so I would like to ask how did exactly padding (valid) works in this situation to have the output is (batchsize,6,6,256).
 Thanks !

**Comment by ageron** [comment]
Hi Phong,
After the first layer, indeed there are 256 20x20 maps, because 28-9+1=20. After the second layer, there are 256 6x6 maps, because 20-9+1=12, and stride 2 means we divide 12 by 2, which gives 6.
I hope this helps,
Aurélien

**Comment by phongnhhn92** [comment]
![capture](https://user-images.githubusercontent.com/11288381/33596489-2a32d5bc-d9df-11e7-8ab1-cd0d72b09cb4.PNG)
Thanks Aurélien,
I kind a understand it now. before i am just following the formula given by CS231 course so I dont understand it. 
Thanks for your reply then :D
