### ISSUE TITLE
Chapter 8, Running times of randomized pca and rugular pca are the same.

### ISSUE THREAD

**Issue by oldiron-ho** [ageron/handson-ml#137]
Hi,
Thanks for your great book. 
I found something strange result.
In ch8, ln[52] regular pca and randomized pca running times are the same. 
I think lower n_components must cause better randomized pca result.
Then, I searched sklearn documents and found that default svd_solver option of PCA() is 'auto'
That means....
>auto :
the solver is selected by a default policy based on X.shape and n_components: if the input data is larger than 500x500 and the number of components to extract is lower than 80% of the smallest dimension of the data, then the more efficient ‘randomized’ method is enabled. Otherwise the exact full SVD is computed and optionally truncated afterwards.

I think
regular_pca = PCA(n_components=n_components) 
must be
regular_pca = PCA(n_components=n_components, svd_solver='full')

Then, we can use pca with regular mode.

After modifying the source, My results are:
>n_components = 2
    PCA: 16.0 seconds
    IncrementalPCA: 31.3 seconds
    PCA: 5.5 seconds
n_components = 10
    PCA: 16.0 seconds
    IncrementalPCA: 28.9 seconds
    PCA: 5.1 seconds
n_components = 154
    PCA: 15.3 seconds
    IncrementalPCA: 38.9 seconds
    PCA: 12.5 seconds

**Comment by ageron** [comment]
Great catch, @oldiron-ho ! The `svd_solver` parameter was added in Scikit-Learn 0.18, while I wrote this chapter when it was still 0.17.
I'll update the book and the code to clarify this.
Thanks a lot!
