### ISSUE TITLE
Exercise Solutions

### ISSUE THREAD

**Issue by oanise93** [ageron/handson-ml#14]
Hey, first off I'm really enjoying your book so far, but I was wondering when you will have the solutions up for the coding exercises. I'm really stuck on Chapter 2 Exercise 3 and would love to know the correct way to solve the problem.

**Comment by ageron** [comment]
Ah, sorry about that, it's definitely in my To-Do list.  In the meantime, this [code example](http://scikit-learn.org/stable/auto_examples/hetero_feature_union.html#sphx-glr-auto-examples-hetero-feature-union-py) may help? Please let me know. If you're still stuck in a couple of days, I'll definitely write the solution.

As a sort of excuse, I've been incredibly busy these days, preparing this [online training course](https://www.safaribooksonline.com/live-training/courses/introduction-to-tensorflow/0636920079460/) and this talk at [Strata London](https://conferences.oreilly.com/strata/strata-eu/public/schedule/speaker/270099) while helping with the french translation of my book, and that's just during my week-ends, I'm a consultant during the week. Oh boy...  ;-)

**Comment by ageron** [comment]
Hi @oanise93, are you still stuck?

**Comment by oanise93** [comment]
Thanks for getting back to me. I'm able to make a pipeline that would just do feature selection and then prediction, but I don't see how I could add that data transformation part that is implemented in the beginning of the chapter. I kept getting an error concerning the pipeline not being able to call fit_transform.
`
from sklearn.feature_selection import SelectFromModel

selection = Pipeline([
        ('feature_selection', SelectFromModel(RandomForestRegressor(), threshold=0.01)),
        ('estimator', RandomForestRegressor())
    ])

selection.fit(housing_prepared, housing_labels).predict(housing_prepared)`

**Comment by ageron** [comment]
I'll post a solution this week-end.

**Comment by ageron** [comment]
Hi @oanise93,

As promised, I just added exercise solutions for chapter 2.  I'll be pushing exercise solutions every few days for the other chapters as well.

Note that user @bjpcjp kindly shared a repo with his own solutions:
https://github.com/bjpcjp/scikit-and-tensorflow-workbooks/

Have fun learning ML!

**Comment by oanise93** [comment]
Thanks @ageron!
