### ISSUE TITLE
Chapter 5, class MyLinearSVC, method fit() gives incorrect support_vectors_idx

### ISSUE THREAD

**Issue by jshmchenxi** [ageron/handson-ml#140]
Hi @ageron 👍 👍:
Thank you for the book, I find it very useful!

When I ran the code in chapter 5, I found a mistake.

The third last line of fit() is:
`        support_vectors_idx = (X_t.dot(w) + b < 1).ravel()`
It should be:
`        support_vectors_idx = (X_t.dot(w) + t * b < 1).ravel()`

Otherwise it labels negative samples beyond the margin as support vectors!

**Comment by ageron** [comment]
Hi @jshmchenxi ,

Double thanks 👍 👍  for your kind and encouraging words, and for spotting this issue!  :))

I just fixed it.

Cheers,
Aurélien
