### ISSUE TITLE
Chapter 2 getting the Housing datasets, encountered file-not-found error

### ISSUE THREAD

**Issue by vibhavk** [ageron/handson-ml#142]
Hi Aurelien,

While preparing the housing data set in Chapter 2, I ran the function code in my Jupyter Notebook mentioned, to fetch the housing.tgz file it ran w/o any issues and then I ran the pandas function to return a Pandas dataframe, it ran without errors...but when I ran the following code to use DataFrame's  head( ) method.

housing = load_housing_data( )
housing.head( )

the kernel throws a FileNotFoundError...and says this---->File b 'datasets/housing/housing.csv' not found.

I'm using virtualenv, Python3.5...

Following is the exact error I'm encountering....Please help me

FileNotFoundError                         Traceback (most recent call last)
<ipython-input-5-96e33597e42c> in <module>()
----> 1 housing = load_housing_data()
      2 housing.head

<ipython-input-4-6111fd061431> in load_housing_data(housing_path)
      2 def     load_housing_data(housing_path=HOUSING_PATH):
      3                                 csv_path        =       os.path.join(housing_path,      "housing.csv")
----> 4                                 return  pd.read_csv(csv_path)

~/env/lib/python3.5/site-packages/pandas/io/parsers.py in parser_f(filepath_or_buffer, sep, delimiter, header, names, index_col, usecols, squeeze, prefix, mangle_dupe_cols, dtype, engine, converters, true_values, false_values, skipinitialspace, skiprows, nrows, na_values, keep_default_na, na_filter, verbose, skip_blank_lines, parse_dates, infer_datetime_format, keep_date_col, date_parser, dayfirst, iterator, chunksize, compression, thousands, decimal, lineterminator, quotechar, quoting, escapechar, comment, encoding, dialect, tupleize_cols, error_bad_lines, warn_bad_lines, skipfooter, skip_footer, doublequote, delim_whitespace, as_recarray, compact_ints, use_unsigned, low_memory, buffer_lines, memory_map, float_precision)
    703                     skip_blank_lines=skip_blank_lines)
    704 
--> 705         return _read(filepath_or_buffer, kwds)
    706 
    707     parser_f.__name__ = name

~/env/lib/python3.5/site-packages/pandas/io/parsers.py in _read(filepath_or_buffer, kwds)
    443 
    444     # Create the parser.
--> 445     parser = TextFileReader(filepath_or_buffer, **kwds)
    446 
    447     if chunksize or iterator:

~/env/lib/python3.5/site-packages/pandas/io/parsers.py in __init__(self, f, engine, **kwds)
    812             self.options['has_index_names'] = kwds['has_index_names']
    813 
--> 814         self._make_engine(self.engine)
    815 
    816     def close(self):

~/env/lib/python3.5/site-packages/pandas/io/parsers.py in _make_engine(self, engine)
   1043     def _make_engine(self, engine='c'):
   1044         if engine == 'c':
-> 1045             self._engine = CParserWrapper(self.f, **self.options)
   1046         else:
   1047             if engine == 'python':

~/env/lib/python3.5/site-packages/pandas/io/parsers.py in __init__(self, src, **kwds)
   1682         kwds['allow_leading_cols'] = self.index_col is not False
   1683 
-> 1684         self._reader = parsers.TextReader(src, **kwds)
   1685 
   1686         # XXX

pandas/_libs/parsers.pyx in pandas._libs.parsers.TextReader.__cinit__()

pandas/_libs/parsers.pyx in pandas._libs.parsers.TextReader._setup_parser_source()

FileNotFoundError: File b'datasets/housing/housing.csv' does not exist

**Comment by ageron** [comment]
Hi Vibhav,

Well it looks like the program does not find the file `datasets/housing/housing.csv`.  Since this is a relative path, it means that the code is trying to find this file relative to the current directory, so please make sure that you started the Jupyter notebook from this project's root directory (i.e., the directory that contains the `datasets` directory, which should contain a `housing` directory, which should contain a `housing.csv` file).
Hope this helps.

**Comment by ganeshth** [comment]
Hi @vibhavk

Try running this code in the Jupyter notebook. You will get the current working directory of your Jupyter notebook. This is the path where the housing dataset gets downloaded and unzipped.
`import os`
`os.getcwd()`

Resolve the path conflicts based on the above command output. 
(or)
Navigate to this directory and start the notebook. Hope this helps.

**Comment by Joe295159** [comment]
For people that have this problem and are dumb like me, make sure that you actually call(like below) before trying to load the data...

`fetch_housing_data()
`

**Comment by ageron** [comment]
Thanks @ganeshth  and @Joe295159 , very useful feedback. :)

**Comment by longbored** [comment]
I also ran into a problem at this function, and realized it was a macOS SSL error with the Python 3.6 installation. This tip here helped me: https://stackoverflow.com/a/42334357

**Comment by datracker** [comment]
To solve the SSL Error for python 3.6 in macOS 10.6+, go to /Applications/Python 3.6 and open Install Certificates.command file, this will install a third party certifi package and solves the SSL error.

**Comment by vibhavk** [comment]
Guys thanks you! issue resolved... :-)

**Comment by anthonydekerckheer** [comment]
Thanks! But I tried the last option and got the following error
ParserError: Error tokenizing data. C error: Expected 1 fields in line 76, saw 6

Indeed (line 76 of the csv file):
 <meta name="enabled-features" content="UNIVERSE_BANNER,MARKETPLACE_PLAN_RESTRICTION_EDITOR,NOTIFY_ON_BLOCK,RELATED_ISSUES,MARKETPLACE_BROWSING_V2,MARKETPLACE_INSIGHTS_V2">


And ignoring this line by making "load_housing_data" to return "pd.read_csv(csv_path, error_bad_lines=False)" doesn't help at all :(

Thanks in advance for your help!

**Comment by ageron** [comment]
Hi @anthony-dk ,
It looks like you downloaded an HTML page instead of the CSV file. On github, you need to click on "raw" to get the raw file instead of an HTML page that displays the contents nicely. Make sure to download the raw file:
https://raw.githubusercontent.com/ageron/handson-ml/master/datasets/housing/housing.csv
Hope this helps

**Comment by Amol1991** [comment]
import os
import tarfile
from six.moves import urllib

DOWNLOAD_ROOT = "https://raw.githubusercontent.com/ageron/handson-ml/master/"
HOUSING_PATH = os.path.join("datasets", "housing")
HOUSING_URL = DOWNLOAD_ROOT + "datasets/housing/housing.tgz"

def fetch_housing_data(housing_url=HOUSING_URL, housing_path=HOUSING_PATH):
    if not os.path.isdir(housing_path):
        os.makedirs(housing_path)
    tgz_path = os.path.join(housing_path, "housing.tgz")
    urllib.request.urlretrieve(housing_url, tgz_path)
    housing_tgz = tarfile.open(tgz_path)
    housing_tgz.extractall(path=housing_path)
    housing_tgz.close()

**Comment by Amol1991** [comment]
Dear Ageron sir, 
can you explain the above coading its good but not undustandable.

**Comment by ageron** [comment]
Hi @Amol1991 ,
The function creates the `./datasets/housing` directory if it does not exist yet (`os.makedirs(...)`), then it downloads the `housing.tgz` file at the URL `"https://raw.githubusercontent.com/ageron/handson-ml/master/housing.tgz"` and saves it in the `./datasets/housing` directory (`urlretrieve(...)`), then it uncompresses it (`extractall()`).
Hope this helps,
Aurélien

**Comment by mathewsmutethia** [comment]
Hello @ageron 
I am new in python and all this coding confuses me when trying to understand the book.
Will it hinder my capability of learning the content?
Regards
Mathews

**Comment by ageron** [comment]
Hi @mathewsmutethia ,
I tried to make the code as simple as possible, but I did assume that the reader would know how to program in Python. You can try to read on, but if you get confused too often with the code, I would suggest taking a break from the book, and getting a bit more experience with Python before you continue. There are tons of resources out there to learn Python, for example the [official tutorial](https://docs.python.org/3/tutorial/). There are also several books on the topic.
That said, most of the code I wrote is fairly straightforward. You need to know python basics, including lists, list comprehensions, dictionaries, strings, functions, lambdas, how to write and use a class, and the most common packages in the standard library (at least know what they do and where to get more documentation if needed), such as os, sys, json, time, logging, itertools, re, hashlib, zlib, tarfile and collections. I also assume that the reader knows scientific python libraries, including NumPy, SciPy, Matplotib and Pandas. If you don't know these, I wrote [a few tutorials](https://nbviewer.jupyter.org/github/ageron/handson-ml/blob/master/index.ipynb#Scientific-Python-tutorials) that you may find useful.
I hope this helps,
Aurélien

**Comment by Suveesh** [comment]
I had a same experience but then I realized the DOWNLOAD_ROOT = "https://raw.githubusercontent.com/ageron/handson-ml/master/" was copied directly from the e-book instead try to type it manually, that should work.
I just followed the instructions in the book and had no issues in retrieving the table head.

hope this helps!

**Comment by smt07** [comment]
> For people that have this problem and are dumb like me, make sure that you actually call(like below) before trying to load the data...
> 
> `fetch_housing_data() `

fetch_housing_data()
housing = load_housing_data()
housing.head()

**Comment by smt07** [comment]
Good one :)

**Comment by isuri9734** [comment]
import os
import tarfile
from six.moves import urllib

DOWNLOAD_ROOT = "https://raw.githubusercontent.com/ageron/handson-ml/master/housing.tgz"
HOUSING_PATH = os.path.join("datasets", "housing")
HOUSING_URL = DOWNLOAD_ROOT + HOUSING_PATH + "/housing.tgz"

def fetch_housing_data(housing_url=HOUSING_URL, housing_path=HOUSING_PATH):
    if not os.path.isdir(housing_path):
        os.makedirs(housing_path)
    tgz_path = os.path.join(housing_path, "housing.tgz")
    urllib.request.urlretrieve(housing_url, tgz_path)
    housing_tgz = tarfile.open(tgz_path)
    housing_tgz.extractall(path=housing_path)
    housing_tgz.close() 


fetch_housing_data()

When I run  code, I got this error. Why ?

HTTPError                                 Traceback (most recent call last)
<ipython-input-39-bd66b1fe6daf> in <module>
----> 1 fetch_housing_data()

<ipython-input-38-3c520314a71c> in fetch_housing_data(housing_url, housing_path)
     11         os.makedirs(housing_path)
     12     tgz_path = os.path.join(housing_path, "housing.tgz")
---> 13     urllib.request.urlretrieve(housing_url, tgz_path)
     14     housing_tgz = tarfile.open(tgz_path)
     15     housing_tgz.extractall(path=housing_path)

~\.conda\envs\tf_cpu\lib\urllib\request.py in urlretrieve(url, filename, reporthook, data)
    245     url_type, path = splittype(url)
    246 
--> 247     with contextlib.closing(urlopen(url, data)) as fp:
    248         headers = fp.info()
    249 

~\.conda\envs\tf_cpu\lib\urllib\request.py in urlopen(url, data, timeout, cafile, capath, cadefault, context)
    220     else:
    221         opener = _opener
--> 222     return opener.open(url, data, timeout)
    223 
    224 def install_opener(opener):

~\.conda\envs\tf_cpu\lib\urllib\request.py in open(self, fullurl, data, timeout)
    529         for processor in self.process_response.get(protocol, []):
    530             meth = getattr(processor, meth_name)
--> 531             response = meth(req, response)
    532 
    533         return response

~\.conda\envs\tf_cpu\lib\urllib\request.py in http_response(self, request, response)
    639         if not (200 <= code < 300):
    640             response = self.parent.error(
--> 641                 'http', request, response, code, msg, hdrs)
    642 
    643         return response

~\.conda\envs\tf_cpu\lib\urllib\request.py in error(self, proto, *args)
    567         if http_err:
    568             args = (dict, 'default', 'http_error_default') + orig_args
--> 569             return self._call_chain(*args)
    570 
    571 # XXX probably also want an abstract factory that knows when it makes

~\.conda\envs\tf_cpu\lib\urllib\request.py in _call_chain(self, chain, kind, meth_name, *args)
    501         for handler in handlers:
    502             func = getattr(handler, meth_name)
--> 503             result = func(*args)
    504             if result is not None:
    505                 return result

~\.conda\envs\tf_cpu\lib\urllib\request.py in http_error_default(self, req, fp, code, msg, hdrs)
    647 class HTTPDefaultErrorHandler(BaseHandler):
    648     def http_error_default(self, req, fp, code, msg, hdrs):
--> 649         raise HTTPError(req.full_url, code, msg, hdrs, fp)
    650 
    651 class HTTPRedirectHandler(BaseHandler):

HTTPError: HTTP Error 404: Not Found

**Comment by rajnishkaushik** [comment]
I was missing the **fetch_housing_data()** as @smt07 has pointed out. Thanks much. However, now I am getting a 404 as  the source file:
https://raw.githubusercontent.com/agreon/handson-ml2/master/datasets/housing/housing.tgz does not exist. 

@ageron, please advise if the file location has changed. Thanks much

**Comment by kyb111** [comment]
> I was missing the **fetch_housing_data()** as @smt07 has pointed out. Thanks much. However, now I am getting a 404 as the source file:
> https://raw.githubusercontent.com/agreon/handson-ml2/master/datasets/housing/housing.tgz does not exist.
> 
> @ageron, please advise if the file location has changed. Thanks much

https://github.com/rickiepark/handson-ml/tree/master/datasets/housing

링크가 변경 되었습니다.

**Comment by NathanNYC** [comment]
If we're using Jupyter Notebook, how could we have the directory match what's needed for this code to run? Additionally, if we try to take a less painful route and download the CSV, what ends up happening at https://raw.githubusercontent.com/ageron/handson-ml/master/datasets/housing/housing.csv is that we just get the data as a block of text, it's not really even a CSV, so we'd have to do some manual work to get it into a proper CSV form. 

I guess basically any step-by-step guides out there on how to change one's directory? Or even to see what directory we're working in?

**Comment by garciamilord** [comment]
> I never call the function to load the extract dataset lmao

**Comment by sbp240103** [comment]
> Hi Vibhav,
> 
> Well it looks like the program does not find the file `datasets/housing/housing.csv`. Since this is a relative path, it means that the code is trying to find this file relative to the current directory, so please make sure that you started the Jupyter notebook from this project's root directory (i.e., the directory that contains the `datasets` directory, which should contain a `housing` directory, which should contain a `housing.csv` file). Hope this helps.
