### ISSUE TITLE
Chapter 9 - variable_scope() parameter "reuse"

### ISSUE THREAD

**Issue by shabie** [ageron/handson-ml#144]
Hello Aurélien,

I don't think it is strictly an issue so to say but as far as I have read the official documentation [here ](https://www.tensorflow.org/api_docs/python/tf/variable_scope)and [here](https://www.tensorflow.org/versions/r0.12/how_tos/variable_scope/), reuse=False is not allowed as described in the book one page 249 and 251 of the PDF version.

 I am sorry if that has been clarified elsewhere but I didn't find it so I am posting it for others' help.

P.S. Thank you for writing perhaps the most amazing book on practical Machine Learning available today. I hope you write more books or at least come up with later editions including more stuff and explanations. Please don't worry about the number of pages! Better to have all the good stuff in one place.

**Comment by ageron** [comment]
Thanks Shabie, very interesting feedback.  I'll replace `reuse=False` with `reuse=None` (since 1.1.0, they do the exact same thing, but it's better to respect the API).

Thanks for your encouraging words regarding future editions.  👍 
Cheers!
