### ISSUE TITLE
Readme should instruct on how to install certs

### ISSUE THREAD

**Issue by gthompson333** [ageron/handson-ml#145]
Hi Aurelien,

When attempting to download the housing data for chapter 2, I ran into a Python SSL error.  It wasn't too difficult to resolve, but it might save others some time and frustration if you were to include in your Readme that certs need to be installed for Python.

This is when running on MacOS, that is.

One need only run the below command:

open "/Applications/Python 3.6/Install Certificates.command"

**Comment by ageron** [comment]
Good point, thanks.  I added a comment in the README.md, as you suggested.
