### ISSUE TITLE
chapter3:  norm_conf_mx =  conf_mx  / row_sums :return all zeros

### ISSUE THREAD

**Issue by chamao** [ageron/handson-ml#148]
in python 2.7

"norm_conf_mx =  conf_mx  / row_sums"

returns all 0 array.

so, to get float array

norm_conf_mx  =  (conf_mx * 1.0)  / row_sums"

**Comment by chamao** [comment]
This issue is due to python version.
In python3,  "norm_conf_mx = conf_mx / row_sums"  returns  float array.
I think code in this boook supports python 2.7.

**Comment by denfromufa** [comment]
`from __future__ import division`
