### ISSUE TITLE
Don't understand Equation C.4

### ISSUE THREAD

**Issue by antoinecollas** [ageron/handson-ml#149]
Hello,
first of all thank you for having written this very interesting book. However, I don't understand the equation C.4 (in the appendix C). Why is it alpha and not alpha hat? Before the equation it is written: "we plug these results into the definition of the generalized Lagrangian"; the equations contain alpha hat so I don't understand why it is still alpha in equation C.4.

Thank you in advance!

**Comment by antoinecollas** [comment]
For those who also don't understand equation C.4, there is a good explanation on wikipedia: https://en.wikipedia.org/wiki/Wolfe_duality

**Comment by ageron** [comment]
Hi Antoine, thanks for the pointers, glad you found the explanation you were looking for.
Cheers,
Aurélien
