### ISSUE TITLE
DataFrameSelector IndexError

### ISSUE THREAD

**Issue by shanepiesik** [ageron/handson-ml#15]
Enjoy reading the book thus far! 

However, when implementing the the `full_pipeline.fit_transform(housing)` I receive an IndexError, which seems to be a product of the transform method on the DataFrameSelector class. 

IndexError: only integers, slices (`:`), ellipsis (`...`), numpy.newaxis (`None`) and integer or boolean arrays are valid indices

`DataFrameSelector` is defined in cell 51 of the notebook.

In the book you reference other ways to do the task of `DataFrameSelector` but I'd like to understand exactly what went wrong here.

**Comment by shanepiesik** [comment]
Nothing wrong with `DataFrameSelector`. I was erroneously defining `full_pipeline` without `FeatureUnion` which was causing the issue. Closing this.

**Comment by ageron** [comment]
Thanks for your kinds words. I'm glad you found a solution to the problem.
