### ISSUE TITLE
Chapter 2, exercise 5

### ISSUE THREAD

**Issue by MostafaKhezri** [ageron/handson-ml#151]
In solution of this exercise, you are saying that
> ... apparently only the top 7 features are useful (out of 9), the last 2 seem to just add some noise.

I noticed few confusions with this statement:

1. There are total of 8+2+(1 or 5?) features in this pipeline: 8 original features,  2 new features added with `CombinedAttributesAdder`, and the `ocean_proximity`.
For `ocean_proximity` I'm confused how to think about it after the encoding. Is it still considered one feature? Or after encoding we should think of it as 5 distinct features? I would guess that the later is correct cause each of the encoded results get their own `feature_importances` parameter, but I'm not sure.

2. You are only searching for up to 7 top features in this solution. This means it cannot be claimed that more features are not better. In other words,  more top features are not searched over to see if it gives better results or not.
For example, I searched over `'feature_selection__k': [5, 7, 9, 11, 13, 16]` [note that `len(feature_importances)` is 16] and got `preparation__num_pipeline__imputer__strategy': 'most_frequent', 'feature_selection__k': 16`.

**Comment by MostafaKhezri** [comment]
P.S. : Your amazingly practical book and jupyter notebooks are great and much appreciated.

**Comment by ageron** [comment]
Hi @MostafaKhezri ,

Thanks for your feedback.  Indeed, you are quite right on both points, I must have been asleep when I wrote this solution, good catch!  ;-)

Regarding your first point, at the beginning, the dataset contains 9 features: longitude, latitude, housing_median_age, total_rooms, total_bedrooms, population, households, median_income, ocean_proximity. At the end of preprocessing, there are 16 features: the ocean_proximity feature is replaced by 5 dummy features (INLAND, <1H OCEAN, NEAR OCEAN, NEAR BAY, ISLAND), and 3 additional features are computed (pop_per_hhold, rooms_per_hhold and bedrooms_per_room). So it's 9 - 1 + 5 + 3 = 16.

Regarding your second point, you are quite right. I'll fix this asap.

Thanks again!
Aurélien

**Comment by ageron** [comment]
Fixed in commit 3b4de785e7fb5523c62046edb075a85c6dcdb7ad.
Apparently all features are useful, except for the ISLAND feature.
Thanks again for your feedback!  :)
