### ISSUE TITLE
Value of vector b in Equation 5-5 when applying to hard margin problem

### ISSUE THREAD

**Issue by greatji** [ageron/handson-ml#152]
b here seems to be -1 vector instead of 1.

**Comment by ageron** [comment]
Hi @greatji ,
Thanks for your feedback.  I double-checked, and I think the book is correct: note the negative sign when I define a^(i) = -t^(i) x^(i).
Feel free to reopen this issue if you disagree, maybe I missed another error.
Cheers,
Aurélien
