### ISSUE TITLE
Chapter 2: visualising the data - How to find a background image?

### ISSUE THREAD

**Issue by nkoronka** [ageron/handson-ml#163]
This is not technically an issue, I must confess, but will add something. How were you able to find such a clean map background for your california visualisation?

The visualisation is really powerful and I (and I'm sure others) would like to repeat it with different geographies.

**Comment by ageron** [comment]
Hi @nkoronka ,
I just did a Google Image search, filtering on images that I could reproduce and modify without authorization.  I believe it is this public domain image:

**Comment by nkoronka** [comment]
Thanks @ageron
