### ISSUE TITLE
ETA for french translation?

### ISSUE THREAD

**Issue by ogrange** [ageron/handson-ml#17]
Hello Aurélien,

You're mentioning in a [previous issue](/ageron/handson-ml/issues/14#issuecomment-296380051) a french translation (awesome!). Is there an ETA?

Thank you!

**Comment by ageron** [comment]
It's supposed to be released sometime around July 2017, published by the [Dunod editions](https://www.dunod.com/).  It will actually be split into two books: the first part, which is an introduction to Machine Learning using Scikit-Learn, will be the first book, and the second part, which is about Deep Learning with TensorFlow will be the second book.
Enjoy!  :)

**Comment by ogrange** [comment]
Thank you Aurélien!
