### ISSUE TITLE
random_state

### ISSUE THREAD

**Issue by magicmutal** [ageron/handson-ml#170]
Dear Aurélien,

Hi, my name is Jinsu.
I'm really enjoying your book!!

I don't understand what is the "random_state=42" and "random generator seed"

in page 51,
"First there is a random_state parameter that allows you to set the random generator seed
 as explained previously, and second you can pass it multiple datasets with an identical number
 of rows, and it will split them on the same indices(this is very useful, for example, if you have a 
 separate DataFrame for labels)

Could you explain more about it in detail??

And, I want to know how SGDclassifier works.
the book just described the advantage of the classifier.

Thank you

Jinsu Kim

**Comment by cuent** [comment]
@magicmutal a `random_state` is used to generate a random number based on a seed. This means that every time you re-execute your workflow is going to generate the same random number. This used to make your workflow reproducible and obtain the same results.

**Comment by ageron** [comment]
As @cuent said (thanks Xavier!), setting the `random_state` is useful to ensure that your program will always have the same output.  For example, when you don't set the random state, and you train the model multiple times, you get different results every time:

```python
>>> SGDClassifier().fit(X, y).score(X_test, y_test)
0.81999999999999995
>>> SGDClassifier().fit(X, y).score(X_test, y_test)
0.85999999999999999
>>> SGDClassifier().fit(X, y).score(X_test, y_test)
0.77000000000000002
```

But when you set the random state, you always get the same result:

```python
>>> SGDClassifier(random_state=42).fit(X, y).score(X_test, y_test)
0.82999999999999996
>>> SGDClassifier(random_state=42).fit(X, y).score(X_test, y_test)
0.82999999999999996
>>> SGDClassifier(random_state=42).fit(X, y).score(X_test, y_test)
0.82999999999999996
>>> SGDClassifier(random_state=42).fit(X, y).score(X_test, y_test)
0.82999999999999996
```

Of course, if you change the random state, you get a different result:

```python
>>> SGDClassifier(random_state=123).fit(X, y).score(X_test, y_test)
0.87
>>> SGDClassifier(random_state=123).fit(X, y).score(X_test, y_test)
0.87
>>> SGDClassifier(random_state=123).fit(X, y).score(X_test, y_test)
0.87
>>> SGDClassifier(random_state=123).fit(X, y).score(X_test, y_test)
0.87
```

Don't worry if you don't know how the `SGDClassifier` works yet, the point of the second and third chapters is to grasp fundamental concepts.  The details of how Stochastic Gradient Descent works is explained in chapter 4.

Hope this helps!
