### ISSUE TITLE
RNNs with Mixed Time Series Frequencies

### ISSUE THREAD

**Issue by kightlingerh** [ageron/handson-ml#177]
Thanks for the great book! I thoroughly enjoyed it.

In chapter 14, on the difficulty of training RNNs over many time steps, you suggested a solution whereby you shorten time sequences by using aggregated data for certain time periods: "monthly data for the last five months, then weekly for the last 5 weeks, then daily data over the last 5 days".

Any chance you can provide or point me to an example where this is done?

**Comment by ageron** [comment]
That's a good question, I believe I saw something like this is in a blog somewhere, but to be honest I can't find it (I just spent 20 minutes searching), sorry about that.

The best option is to try it! :)
