### ISSUE TITLE
Chapter 4 Batch gradient descent path is a closed polygon

### ISSUE THREAD

**Issue by amamolea** [ageron/handson-ml#180]
This corresponds to figure 4-11 in text (the book is fine, the problem is only in current notebook)

Root cause: the code saving figure gradient_descent_plot is run twice and both times it updates the theta_path_bgd list.

To fix, just remove duplicate code, the last code cell in section "Linear regression using batch gradient descent."

**Comment by ageron** [comment]
Wow, thanks @amamolea , I love it when nice people like you submit both the issue *and* the fix! :)
Just pushed the fix right now, thanks again,
Aurélien
