### ISSUE TITLE
text not rendered correctly in notebook caps net

### ISSUE THREAD

**Issue by worthlessFella** [ageron/handson-ml#185]
To compute $\hat{\mathbf{u}}_{j|i}$ for every pair of capsules ($i$, $j$), we will use a nice feature of the tf.matmul() function: you probably know that it lets you multiply two matrices, but you may not know that it also lets you multiply higher dimensional arrays. It treats the arrays as arrays of matrices, and it performs itemwise matrix multiplication. For example, suppose you have two 4D arrays, each containing a 2×3 grid of matrices. The first contains matrices $\mathbf{A}, \mathbf{B}, \mathbf{C}, \mathbf{D}, \mathbf{E}, \mathbf{F}$ and the second contains matrices $\mathbf{G}, \mathbf{H}, \mathbf{I}, \mathbf{J}, \mathbf{K}, \mathbf{L}$. If you multiply these two 4D arrays using the tf.matmul() function, this is what you get:

$ \pmatrix{ \mathbf{A} & \mathbf{B} & \mathbf{C} \\ \mathbf{D} & \mathbf{E} & \mathbf{F} } \times \pmatrix{ \mathbf{G} & \mathbf{H} & \mathbf{I} \\ \mathbf{J} & \mathbf{K} & \mathbf{L} } = \pmatrix{ \mathbf{AG} & \mathbf{BH} & \mathbf{CI} \\ \mathbf{DJ} & \mathbf{EK} & \mathbf{FL} } $

I am sure something is wrong here. The text rendering is not proper

**Comment by vd1** [comment]
it shows ok on my version
did you check that the cell is in "markdown" mode and not in "raw" mode?

**Comment by worthlessFella** [comment]
Its not cell.. Its just text

**Comment by worthlessFella** [comment]
Earlier I was just viewing online. I was getting it like what i mentioned. Now I am download in my machine and put it in markdown mode. Its ok now!!

**Comment by vd1** [comment]
cool!
