### ISSUE TITLE
Chapter 12 solution

### ISSUE THREAD

**Issue by boyuanf** [ageron/handson-ml#187]
Hi, I am wondering when we can upload the solution for Chapter 12? Really need some hint for the source code there. Thank you very much

**Comment by ageron** [comment]
Hi @boyuanf ,

Yikes, this is one of the 4 chapters for which I haven't found the time to work on the solutions, I'm really sorry.  I'll do my best to upload this quickly, but it will probably take a few weeks, I'm incredibly busy these days.

In the mean time, you can check out the code examples here:
https://www.tensorflow.org/deploy/distributed

I'll do my best to upload the solutions asap.

Cheers,
Aurélien

**Comment by boyuanf** [comment]
@ageron Many thanks for reply. The Chapter 12 would be perfect if it could talk more about the distributed training with examples, the examples from other Chapters are really helpful, so I am looking forward for your uploading 👍 

Meanwhile, I find those two examples are very helpful:

https://github.com/tensorflow/models/blob/master/tutorials/image/cifar10/cifar10_multi_gpu_train.py
https://github.com/awslabs/deeplearning-benchmark/tree/master/tensorflow/inception

**Comment by gneglia** [comment]
Hi, I am also interested in the solutions for chapter 12 and in particular exercise 12.10. Any forecast?

Thanks for the excellent book.
Best,
Giovanni

**Comment by ageron** [comment]
Closing stale issues. Please reopen if you are still experiencing a problem.
