### ISSUE TITLE
OpenAI gym is not in docker

### ISSUE THREAD

**Issue by layssi** [ageron/handson-ml#191]
```python
import gym
---------------------------------------------------------------------------
ModuleNotFoundError                       Traceback (most recent call last)
<ipython-input-2-c727ea424a25> in <module>()
----> 1 import gym

ModuleNotFoundError: No module named 'gym'
```

**Comment by ageron** [comment]
Thanks for your feedback, Samir.

@StevenBunkley or @ziembla , could one of you please check out this issue, I would greatly appreciate it. Thanks!

**Comment by pidugusundeep** [comment]
pip install gym
install the module zym.

**Comment by ageron** [comment]
Thanks @pidugusundeep . I'm afraid just installing gym will solve the `import gym` issue, but it will not be possible to use the Atari environment, and possibly other environments.  See https://github.com/openai/gym#installing-everything

**Comment by ziembla** [comment]
Sorry, I only yesterday got your message - see <https://github.com/ageron/handson-ml/pull/197>. Atari and cart pole samples are working now.
