### ISSUE TITLE
Chapter 8 pre-image reconstruction uses sigmoid kernel instead of RBF kernel

### ISSUE THREAD

**Issue by amamolea** [ageron/handson-ml#192]
When computing:

```python
X_inverse = pca.inverse_transform(X_reduced_rbf)
```

`pca` is still set to `sig_pca`, from the for loop in the code cell above.

To fix just use `rbf_pca` directly:
```python
X_inverse = rbf_pca.inverse_transform(X_reduced_rbf)
```

Regards,
Adrian

**Comment by ageron** [comment]
Great catch, thanks a lot, Adrian!  I updated the notebook, and fortunately it does not change the figure much (it mostly rotates it), which means that the book does not need to be changed (since it only contains the figure, not this code). Phew!  :)
