### ISSUE TITLE
Linear Regression Returns Non

### ISSUE THREAD

**Issue by tonytunde2012** [ageron/handson-ml#20]
Hi Geron,

Thanks for your great book, I am new to Tensorflow and following your implementation, however,  I am encountering an error with Linear Regression implementation.
 I implemented using the California Dataset that was downloaded from chapter 2 because my download using sklearn fetch() returns a responseError
After my implementation the result returns Nan, Can you help me figure out what could be wrong
My observation using np.dot to operate on X.T * X, I found out that the result contains nan values, I don't know if this could be a clue to why the result is as it is

Below is my code
`import numpy as np
import os
import pandas as pd

FILENAME = 'housing.csv'
HOUSING_PATH = "datasets/housing"
def load_housing_data(housing_path=HOUSING_PATH, csv_filename=FILENAME):
    """
    Function to load csv file given a housing, path
    """
    csv_path = os.path.join(housing_path, csv_filename)
    return pd.read_csv(csv_path)

housing = load_housing_data()
housing_target = housing['median_house_value']
housing_target = pd.Series.as_matrix(housing_target)
housing.drop(['ocean_proximity', 'median_house_value'],axis=1, inplace=True)
housing_matrix = pd.DataFrame.as_matrix(housing)

m, n =housing.shape
housing_data_plus_bias = np.c_[np.ones((m, 1)), housing_matrix]

tf.reset_default_graph()

X = tf.constant(housing_data_plus_bias, dtype=tf.float64, name="X")
y = tf.constant(housing_target.reshape(-1, 1), dtype=tf.float64, name="y")
XT = tf.transpose(X)
theta = tf.matmul(tf.matmul(tf.matrix_inverse(tf.matmul(XT, X)), XT), y)

with tf.Session() as sess:
    result = theta.eval()

print(result)

[[ nan]
 [ nan]
 [ nan]
 [ nan]
 [ nan]
 [ nan]
 [ nan]
 [ nan]
 [ nan]]`

**Comment by ageron** [comment]
Hi @tonytunde2012, thanks for your kind words, I'm glad you enjoy the book.

I actually added a few NaN values in the housing dataset used in chapter 2, because I wanted to highlight the fact that datasets are not always clean.  If you use that dataset instead of the one that scikit-learn downloads, you are indeed going to have some trouble.  You

**Comment by tonytunde2012** [comment]
Thanks Ageron,
This is the error from the fetch function
`downloading Cal. housing from http://www.dcc.fc.up.pt/~ltorgo/Regression/cal_housing.tgz to C:\Users\ADEKUNLE\scikit_learn_data
---------------------------------------------------------------------------
RemoteDisconnected                        Traceback (most recent call last)
<ipython-input-1-4e3d1a42651e> in <module>()
      1 from sklearn.datasets import fetch_california_housing
      2 
----> 3 housing = fetch_california_housing()
      4 m, n = housing.data.shape
      5 housing_data_plus_bias = np.c_[np.ones((m, 1)), housing.data]

C:\Users\ADEKUNLE\Anaconda3_2\lib\site-packages\sklearn\datasets\california_housing.py in fetch_california_housing(data_home, download_if_missing)
     91     if not exists(filepath):
     92         print('downloading Cal. housing from %s to %s' % (DATA_URL, data_home))
---> 93         archive_fileobj = BytesIO(urlopen(DATA_URL).read())
     94         fileobj = tarfile.open(
     95             mode="r:gz",

C:\Users\ADEKUNLE\Anaconda3_2\lib\urllib\request.py in urlopen(url, data, timeout, cafile, capath, cadefault, context)
    161     else:
    162         opener = _opener
--> 163     return opener.open(url, data, timeout)
    164 
    165 def install_opener(opener):

C:\Users\ADEKUNLE\Anaconda3_2\lib\urllib\request.py in open(self, fullurl, data, timeout)
    464             req = meth(req)
    465 
--> 466         response = self._open(req, data)
    467 
    468         # post-process response

C:\Users\ADEKUNLE\Anaconda3_2\lib\urllib\request.py in _open(self, req, data)
    482         protocol = req.type
    483         result = self._call_chain(self.handle_open, protocol, protocol +
--> 484                                   '_open', req)
    485         if result:
    486             return result

C:\Users\ADEKUNLE\Anaconda3_2\lib\urllib\request.py in _call_chain(self, chain, kind, meth_name, *args)
    442         for handler in handlers:
    443             func = getattr(handler, meth_name)
--> 444             result = func(*args)
    445             if result is not None:
    446                 return result

C:\Users\ADEKUNLE\Anaconda3_2\lib\urllib\request.py in http_open(self, req)
   1280 
   1281     def http_open(self, req):
-> 1282         return self.do_open(http.client.HTTPConnection, req)
   1283 
   1284     http_request = AbstractHTTPHandler.do_request_

C:\Users\ADEKUNLE\Anaconda3_2\lib\urllib\request.py in do_open(self, http_class, req, **http_conn_args)
   1255             except OSError as err: # timeout error
   1256                 raise URLError(err)
-> 1257             r = h.getresponse()
   1258         except:
   1259             h.close()

C:\Users\ADEKUNLE\Anaconda3_2\lib\http\client.py in getresponse(self)
   1195         try:
   1196             try:
-> 1197                 response.begin()
   1198             except ConnectionError:
   1199                 self.close()

C:\Users\ADEKUNLE\Anaconda3_2\lib\http\client.py in begin(self)
    295         # read until we get a non-100 response
    296         while True:
--> 297             version, status, reason = self._read_status()
    298             if status != CONTINUE:
    299                 break

C:\Users\ADEKUNLE\Anaconda3_2\lib\http\client.py in _read_status(self)
    264             # Presumably, the server closed the connection before
    265             # sending a valid response.
--> 266             raise RemoteDisconnected("Remote end closed connection without"
    267                                      " response")
    268         try:

RemoteDisconnected: Remote end closed connection without response`

**Comment by ageron** [comment]
Really weird... perhaps it's a transient error on the server side, or perhaps a version mismatch in your python libraries, or perhaps it's a networking issue (like a misconfigured firewall).

Here's a workaround for you:

first, dowload the following file and save it somewhere on your disk:
http://www.dcc.fc.up.pt/~ltorgo/Regression/cal_housing.tgz

Then use the following function to load and preprocess the data much like `sklearn.datasets.fetch_california_housing()`:

```python
import tarfile

def fetch_california_housing(tgz_filepath):
    with open(tgz_filepath, "rb") as f:
        fileobj = tarfile.open(mode="r:gz", fileobj=f).extractfile('CaliforniaHousing/cal_housing.data')
        cal_housing = np.loadtxt(fileobj, delimiter=',')
    columns_index = [8, 7, 2, 3, 4, 5, 6, 1, 0]
    cal_housing = cal_housing[:, columns_index]
    y, X = cal_housing[:, 0], cal_housing[:, 1:]
    # avg rooms = total rooms / households
    X[:, 2] /= X[:, 5]
    # avg bed rooms = total bed rooms / households
    X[:, 3] /= X[:, 5]
    # avg occupancy = population / households
    X[:, 5] = X[:, 4] / X[:, 5]
    # Target in units of 100,000
    y = y / 100000.0
    return X, y
```

To use it, just call this function like so (change the path to the `cal_housing.tgz` file if necessary):

```python
X, y = fetch_california_housing("cal_housing.tgz")
```

**Comment by tonytunde2012** [comment]
Used Both Method, all worked well!
