### ISSUE TITLE
Capsule for 3D images

### ISSUE THREAD

**Issue by Usmabhatt** [ageron/handson-ml#211]
I ran your capsule code for 3D medical images. I am getting 50% accuracy at every epoch.  I made necessary changes there are 1349 patients with 64x64x20 images

**Comment by crypdick** [comment]
@Usmabhatt can you give more detail? What dataset are you using?

**Comment by Usmabhatt** [comment]
Sir Thank you so much for reply. I was eagerly waiting.
I m using Kaggle Data Science bowl 2017 but I m badly stuck .
It will be great help if you upload your code on github

Sent from BlueMail<http://www.bluemail.me/r?b=12687>
On Apr 14, 2018, at 7:06 PM, Richard Decal <notifications@github.com<mailto:notifications@github.com>> wrote:

@Usmabhatt<https://github.com/Usmabhatt> can you give more detail? What dataset are you using?

**Comment by ageron** [comment]
Oops, missed this issue, sorry.  If this is still an ongoing project, could you please give more details. For example, please post the code in a github project or a gist so I can run it and investigate what's wrong.

**Comment by Usmabhatt** [comment]
I apologize for the late reply.  Well, there is no deadline for passion and It will be a great help if you investigate my project. Sir, i am new to this field and your help will be a big favour. I have uploaded the code on GitHub. The link is given below
https://github.com/Usmabhatt/project_capsule_3D
________________________________

**Comment by ageron** [comment]
Closing stale issues. Please reopen if you are still experiencing a problem.
