### ISSUE TITLE
chapter 3 spam exercise requires cleaning

### ISSUE THREAD

**Issue by Kallin** [ageron/handson-ml#213]
Love the book, and am just wrapping up doing the exercises from Chapter 3 myself.

My first attempt was to use sklearn built-in text processing libs, and the pipeilne looked pretty simple like

```
pipeline = Pipeline([
    ('vect', CountVectorizer()),
    ('tfidf', TfidfTransformer()),
    ('clf', SGDClassifier()),
])
```

Just using that with the raw text of the emails gave really amazing results across the entire dataset. Maybe worth including it as an example of how to accomplish most of the exercise without having to build those custom estimators.

After checking the top coefficients of the SGD classifier, it turns out that all the spam2 emails have the term 'Spamassassin-Sightings' in the body, which basically lets the algorithm cheat quite a bit. I know that your example solution doesn't use spam2, but it might be worth mentioning that problem exists, or more generally maybe add something to the solution that shows what is impacting the classifier. For instance, with SGD I ran something like this to spit out the most important terms:

```
# how many coefficients are there? Should be the same as the number of features.
best_vanilla_estimator = grid_search.best_estimator_
coefs = best_vanilla_estimator.named_steps['clf'].coef_[0]
print(len(coefs))
vect = best_vanilla_estimator.named_steps['vect']
print(len(vect.get_feature_names()))

# what are the highest weights?
from numpy import argpartition
import numpy as np

ind = np.argpartition(coefs, -20)[-20:]
print(ind)
print(coefs[ind])
print(np.array(vect.get_feature_names())[np.array(ind)])
```

**Comment by ageron** [comment]
Super useful feedback, thanks @Kallin . I'll update this exercise. :)

**Comment by ageron** [comment]
Closing stale issues. Please reopen if you are still experiencing a problem.
