### ISSUE TITLE
Chapter 2 Jupyter notebook: Error executing Jupyter command 'notebook': [Errno 2] No such file or directory

### ISSUE THREAD

**Issue by andsec** [ageron/handson-ml#215]
Hello,
That error; Error executing Jupyter command `'notebook': [Errno 2] No such file or directory.` Continues to pop up every time I try to type the `$jupyter notebook` command. I have followed every command in the book so far. I have also tried uninstalling and reinstalling everything, including Ananconda. Running this list of commands also doesn't work:

```bash
$sudo apt-get install python-setuptools
$sudo easy_install pip==9.0.1
$sudo pip install virtualenv
$pip3 install --user --upgrade virtualenv
$source env/bin/activate
$pip3 install --upgrade jupyter matplotlib numpy pandas scipy scikit-learn
$sudo pip install jupyter
$pip3 install --upgrade --force-reinstall --no-cache-dir jupyter
$pip install notebook
````

The commands run fine but `$jupyter notebook` outputs the same error. I am trying this on windows 10 with an ubuntu shell (bash). Any help would be appreciated, thanks!

Also, great book!

**Comment by nil12285** [comment]
refer to these link
```
http://jupyter.readthedocs.io/en/latest/install.html#id4
http://jupyter.readthedocs.io/en/latest/running.html#running
```

you can do this on windows too; you don't need ubuntu shell;

**Comment by ageron** [comment]
Hi @andsec ,
Make sure you don't type the "$" in the commands: this character is a common convention to indicate that you should type the command in a terminal.  The command you should type is `jupyter notebook`, not `$jupyter notebook`.  If you enter the command with a `$`, the shell (i.e., the program that executes your commands) will replace `$jupyter` with the value of the `jupyter` environment variable, which is certainly not defined, so it's as if you just typed ` notebook`, which is an unknown command.
Hope this helps.

**Comment by andsec** [comment]
Hello @ageron 
The $ was to show that I was typing commands in bash. Sorry, I am new to git so I wasn't sure what the right format was. But I got it to work by starting the notebook through Anaconda. Also, Thank you for writing this book! Ill definitely be looking out for your other work.

**Comment by ageron** [comment]
Hi @andsec ,
Is everything working fine now?

**Comment by andsec** [comment]
@ageron 
Everything is good. Sorry for all of the reopens. Still getting used to git
