### ISSUE TITLE
[Q] Chapter 11: Exercise Q9.3 caching frozen layers

### ISSUE THREAD

**Issue by daQuincy** [ageron/handson-ml#220]
Hi sir, I am following along the code in Chapter 11, exercise question 9.3. At In [146]:  

> hidden5_out = tf.get_default_graph().get_tensor_by_name("hidden5_out:0")

I realize that hidden5_out was not initialize in any way before this line, so I'm not able to get this output from the restored model (I am coding this exercise on a separate Python file). What is the correct name I should input into the function to cache the last layer? Or am I getting this whole concept wrong?

**Comment by ageron** [comment]
Hi @daQuincy ,

This layer comes from the `_dnn()` method of the `DNNClassifier` class (cell 119):

```python
inputs = self.activation(inputs, name="hidden%d_out" % (layer + 1))
````
The `DNNClassifier` is trained in cell 122 (within a `RandomizedSearchCV`) and saved in cell 125 (at path `my_best_mnist_model_0_to_4`) and restored in cell 145.

Hope this helps,
Aurélien

**Comment by daQuincy** [comment]
@ageron I see! I worked on separate files and saved multiple models and got confused in this process. Thanks a lot for clearing this up for me, have a nice day.
