### ISSUE TITLE
Chapter 9, cannot load California data

### ISSUE THREAD

**Issue by masuguaz** [ageron/handson-ml#221]
In chapter 9, I cannot download the data. How can I handle it?

I added `import ssl` part in the source, because
`URLError: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:719)>`
has come out.

## Script

```python
import numpy as np
from sklearn.datasets import fetch_california_housing
import ssl
ssl._create_default_https_context = ssl._create_unverified_context

reset_graph()

housing = fetch_california_housing()
m, n = housing.data.shape
housing_data_plus_bias = np.c_[np.ones((m, 1)), housing.data]
```

## Result

```python
Downloading Cal. housing from 
https://ndownloader.figshare.com/files/5976036 to /Users/kibanken/scikit_learn_data
HTTPError                                 Traceback (most recent call last)
<ipython-input-21-405ae2210930> in <module>()
      4 reset_graph()
      5 
----> 6 housing = fetch_california_housing()
      7 m, n = housing.data.shape
      8 housing_data_plus_bias = np.c_[np.ones((m, 1)), housing.data]

~/anaconda/envs/Hamaguchi/lib/python3.5/site-packages/sklearn/datasets/california_housing.py in fetch_california_housing(data_home, download_if_missing)
     99             ARCHIVE.url, data_home))
    100 
--> 101         archive_path = _fetch_remote(ARCHIVE, dirname=data_home)
    102 
    103         with tarfile.open(mode="r:gz", name=archive_path) as f:

~/anaconda/envs/Hamaguchi/lib/python3.5/site-packages/sklearn/datasets/base.py in _fetch_remote(remote, dirname)
    872     file_path = (remote.filename if dirname is None
    873                  else join(dirname, remote.filename))
--> 874     urlretrieve(remote.url, file_path)
    875     checksum = _sha256(file_path)
    876     if remote.checksum != checksum:

~/anaconda/envs/Hamaguchi/lib/python3.5/urllib/request.py in urlretrieve(url, filename, reporthook, data)
    186     url_type, path = splittype(url)
    187 
--> 188     with contextlib.closing(urlopen(url, data)) as fp:
    189         headers = fp.info()
    190 

~/anaconda/envs/Hamaguchi/lib/python3.5/urllib/request.py in urlopen(url, data, timeout, cafile, capath, cadefault, context)
    161     else:
    162         opener = _opener
--> 163     return opener.open(url, data, timeout)
    164 
    165 def install_opener(opener):

~/anaconda/envs/Hamaguchi/lib/python3.5/urllib/request.py in open(self, fullurl, data, timeout)
    470         for processor in self.process_response.get(protocol, []):
    471             meth = getattr(processor, meth_name)
--> 472             response = meth(req, response)
    473 
    474         return response

~/anaconda/envs/Hamaguchi/lib/python3.5/urllib/request.py in http_response(self, request, response)
    580         if not (200 <= code < 300):
    581             response = self.parent.error(
--> 582                 'http', request, response, code, msg, hdrs)
    583 
    584         return response

~/anaconda/envs/Hamaguchi/lib/python3.5/urllib/request.py in error(self, proto, *args)
    508         if http_err:
    509             args = (dict, 'default', 'http_error_default') + orig_args
--> 510             return self._call_chain(*args)
    511 
    512 # XXX probably also want an abstract factory that knows when it makes

~/anaconda/envs/Hamaguchi/lib/python3.5/urllib/request.py in _call_chain(self, chain, kind, meth_name, *args)
    442         for handler in handlers:
    443             func = getattr(handler, meth_name)
--> 444             result = func(*args)
    445             if result is not None:
    446                 return result

~/anaconda/envs/Hamaguchi/lib/python3.5/urllib/request.py in http_error_default(self, req, fp, code, msg, hdrs)
    588 class HTTPDefaultErrorHandler(BaseHandler):
    589     def http_error_default(self, req, fp, code, msg, hdrs):
--> 590         raise HTTPError(req.full_url, code, msg, hdrs, fp)
    591 
    592 class HTTPRedirectHandler(BaseHandler):

HTTPError: HTTP Error 418: Service Unavailable
```

**Comment by ageron** [comment]
Hi @masuguaz ,

This is quite weird, the server seems to be returning an HTTP 418 error, which actually means "I'm a teapot"! This is an [April fool's joke](http://knowyourmeme.com/memes/http-error-418-im-a-teapot), so I'm not sure why the server would return that. Perhaps it was a temporary server-side problem, you should try again.

If it still does not work, you might have either a network problem, or an Anaconda installation problem. Either way, I can't help you fix it, but I can give you a workaround:

1. Manually download the data using your web browser: https://ndownloader.figshare.com/files/5976036
2. Make sure the downloaded file is named `cal_housing.tgz`.
3. Execute the following Python code:

```python
import numpy as np
import os
import tarfile
from sklearn.externals import joblib
from sklearn.datasets.base import _pkl_filepath, get_data_home

archive_path = "cal_housing.tgz" # change the path if it's not in the current directory
data_home = get_data_home(data_home=None) # change data_home if you are not using ~/scikit_learn_data
if not os.path.exists(data_home):
    os.makedirs(data_home)
filepath = _pkl_filepath(data_home, 'cal_housing.pkz')

with tarfile.open(mode="r:gz", name=archive_path) as f:
    cal_housing = np.loadtxt(
        f.extractfile('CaliforniaHousing/cal_housing.data'),
        delimiter=',')
    # Columns are not in the same order compared to the previous
    # URL resource on lib.stat.cmu.edu
    columns_index = [8, 7, 2, 3, 4, 5, 6, 1, 0]
    cal_housing = cal_housing[:, columns_index]

    joblib.dump(cal_housing, filepath, compress=6)
```

After that you should be able to use `fetch_california_housing()` without any problem.

Hope this helps,
Aurélien

**Comment by masuguaz** [comment]
Thank you Aurélien!
The code you instructed worked for me!! Now I could fetch the California data!

**Comment by phsimon** [comment]
Thanks you !
I has a problem with SHA checksum (difference between what I get and what was expected...). Did not know how to fix that. So I have used your code : it runs :-)

**Comment by sumitgee** [comment]
WHEN I AM RUNNING FOLLOWING CODE IN VSCODE- 

import pandas as pd
import mlflow
import mlflow.sklearn
from sklearn.ensemble import RandomForestRegressor
from sklearn.model_selection import train_test_split,GridSearchCV
from sklearn.metrics import mean_squared_error
from sklearn.datasets import fetch_california_housing

housing=fetch_california_housing()
print(housing)

THE FOLLOWING ERROR IS COMING. PLEASE HELP
---------------------------------------------------------------------------
SSLCertVerificationError                  Traceback (most recent call last)
File e:\ML Course Krish Naik\MLFLOWSTARTER\venv\lib\urllib\request.py:1348, in AbstractHTTPHandler.do_open(self, http_class, req, **http_conn_args)
   [1347](file:///E:/ML%20Course%20Krish%20Naik/MLFLOWSTARTER/venv/lib/urllib/request.py:1347) try:
-> [1348](file:///E:/ML%20Course%20Krish%20Naik/MLFLOWSTARTER/venv/lib/urllib/request.py:1348)     h.request(req.get_method(), req.selector, req.data, headers,
   [1349](file:///E:/ML%20Course%20Krish%20Naik/MLFLOWSTARTER/venv/lib/urllib/request.py:1349)               encode_chunked=req.has_header('Transfer-encoding'))
   [1350](file:///E:/ML%20Course%20Krish%20Naik/MLFLOWSTARTER/venv/lib/urllib/request.py:1350) except OSError as err: # timeout error

File e:\ML Course Krish Naik\MLFLOWSTARTER\venv\lib\http\client.py:1276, in HTTPConnection.request(self, method, url, body, headers, encode_chunked)
   [1275](file:///E:/ML%20Course%20Krish%20Naik/MLFLOWSTARTER/venv/lib/http/client.py:1275) """Send a complete request to the server."""
-> [1276](file:///E:/ML%20Course%20Krish%20Naik/MLFLOWSTARTER/venv/lib/http/client.py:1276) self._send_request(method, url, body, headers, encode_chunked)

File e:\ML Course Krish Naik\MLFLOWSTARTER\venv\lib\http\client.py:1322, in HTTPConnection._send_request(self, method, url, body, headers, encode_chunked)
   [1321](file:///E:/ML%20Course%20Krish%20Naik/MLFLOWSTARTER/venv/lib/http/client.py:1321)     body = _encode(body, 'body')
-> [1322](file:///E:/ML%20Course%20Krish%20Naik/MLFLOWSTARTER/venv/lib/http/client.py:1322) self.endheaders(body, encode_chunked=encode_chunked)

File e:\ML Course Krish Naik\MLFLOWSTARTER\venv\lib\http\client.py:1271, in HTTPConnection.endheaders(self, message_body, encode_chunked)
   [1270](file:///E:/ML%20Course%20Krish%20Naik/MLFLOWSTARTER/venv/lib/http/client.py:1270)     raise CannotSendHeader()
-> [1271](file:///E:/ML%20Course%20Krish%20Naik/MLFLOWSTARTER/venv/lib/http/client.py:1271) self._send_output(message_body, encode_chunked=encode_chunked)

File e:\ML Course Krish Naik\MLFLOWSTARTER\venv\lib\http\client.py:1031, in HTTPConnection._send_output(self, message_body, encode_chunked)
   [1030](file:///E:/ML%20Course%20Krish%20Naik/MLFLOWSTARTER/venv/lib/http/client.py:1030) del self._buffer[:]
-> [1031](file:///E:/ML%20Course%20Krish%20Naik/MLFLOWSTARTER/venv/lib/http/client.py:1031) self.send(msg)
   [1033](file:///E:/ML%20Course%20Krish%20Naik/MLFLOWSTARTER/venv/lib/http/client.py:1033) if message_body is not None:
   [1034](file:///E:/ML%20Course%20Krish%20Naik/MLFLOWSTARTER/venv/lib/http/client.py:1034) 
...
-> [1351](file:///E:/ML%20Course%20Krish%20Naik/MLFLOWSTARTER/venv/lib/urllib/request.py:1351)         raise URLError(err)
   [1352](file:///E:/ML%20Course%20Krish%20Naik/MLFLOWSTARTER/venv/lib/urllib/request.py:1352)     r = h.getresponse()
   [1353](file:///E:/ML%20Course%20Krish%20Naik/MLFLOWSTARTER/venv/lib/urllib/request.py:1353) except:

URLError: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:997)>
Output is truncated. View as a [scrollable element](command:cellOutput.enableScrolling?093d18f4-9443-42f5-84a7-ebcfd8dd40d5) or open in a [text editor](command:workbench.action.openLargeOutput?093d18f4-9443-42f5-84a7-ebcfd8dd40d5). Adjust cell output [settings](command:workbench.action.openSettings?%5B%22%40tag%3AnotebookOutputLayout%22%5D)...
----------------------
