### ISSUE TITLE
Formula display issue

### ISSUE THREAD

**Issue by zhangyuting** [ageron/handson-ml#222]
In the file handson-ml/extra_capsnets.ipynb, the section "Compute the Predicted Output Vectors" failed to display some formula. It shows something like this:

```
$ \pmatrix{ \mathbf{A} & \mathbf{B} & \mathbf{C} \\
\mathbf{D} & \mathbf{E} & \mathbf{F} } \times \pmatrix{ \mathbf{G} & \mathbf{H} & \mathbf{I} \\
\mathbf{J} & \mathbf{K} & \mathbf{L} } = \pmatrix{ \mathbf{AG} & \mathbf{BH} & \mathbf{CI} \\
\mathbf{DJ} & \mathbf{EK} & \mathbf{FL} } $
```

**Comment by ageron** [comment]
Hi @zhangyuting ,
Thanks for your feedback. Are you looking at the notebook using github's viewer or Jupyter.org's viewer or directly using your own Jupyter server?

Unfortunately, the first option is terrible at showing math equations. The second is much better but still not perfect.  The last one is the only option that really displays the equations correctly, although sometimes it takes a few seconds.

If you are using your own Jupyter server and the equation is still not displaying correctly, please make sure this cell's markdown code was not modified. It should be:

```
$
\pmatrix{
\mathbf{A} & \mathbf{B} & \mathbf{C} \\
\mathbf{D} & \mathbf{E} & \mathbf{F}
} \times
\pmatrix{
\mathbf{G} & \mathbf{H} & \mathbf{I} \\
\mathbf{J} & \mathbf{K} & \mathbf{L}
} = \pmatrix{
\mathbf{AG} & \mathbf{BH} & \mathbf{CI} \\
\mathbf{DJ} & \mathbf{EK} & \mathbf{FL}
}
$

I think that's what you have, but perhaps there's a `{` or `}` missing that I am not seeing.

Hope this helps.

**Comment by ageron** [comment]
Closing this issue, please reopen if you still have the problem.
