### ISSUE TITLE
Anaconda display of Chapter 6 Decision Tree

### ISSUE THREAD

**Issue by sabinasaib** [ageron/handson-ml#224]
Because the unix dot command was not available to me on my Windows 10 system, I used python and pydotplus to display and save the decision tree at the start of Chapter 6 in your Machine Learning Book.
I like the book very much and enjoy going through the exercises--so far only to chapter 6.  It is not a problem of course for some not to be able to see the decision tree, but I found it frustrating not to see it.
This is what I used, and perhaps you could add something similar to your notebook which I also found very useful.
Thanks for writing the book and the notebook,
Sabina

```python
from sklearn.externals.six import StringIO  
from IPython.display import Image  
from sklearn.tree import export_graphviz
import pydotplus
dot_data = StringIO()
export_graphviz(tree_clf, out_file=dot_data,  
                filled=True, rounded=True,
                special_characters=True)
graph = pydotplus.graph_from_dot_data(dot_data.getvalue())  
graph.write_png("iris_tree.png")
Image(graph.create_png())
```

**Comment by ageron** [comment]
Thanks a lot, Sabina, both for your kind words and for your helpful contribution.
I don't use Windows, but I thought GraphViz was [available for Windows](https://graphviz.gitlab.io/download/).  Doesn't it work on Windows 10? Did you have an installation problem? Or does the package not contain the `dot` command?
FYI, on Linux or MacOSX, the `dot` command is not included either, it is required to install GraphViz.
Thanks again,
Aurélien

**Comment by sabinasaib** [comment]
GraphViz was available and installed in Anaconda.  The package did not seem to contain the dot command.
I just realized, I had troubles with using it and had to add the path where it was hidden under .../Anaconda3/Library/bin  in order to use it in Python.
Just tried the dot command again now that the path is fixed for GraphViz and the dot command worked ok.

I know I should switch to Linux for this kind of work.

Sabina

**Comment by ageron** [comment]
Thanks for your feedback, I'm glad everything works now.
