### ISSUE TITLE
Ch 3 - Titanic Exercise - boxplot addition

### ISSUE THREAD

**Issue by nyilmaz1** [ageron/handson-ml#225]
Hi @ageron !
First, I want to say that I love your book! It's so informative and easy to follow. I am learning a lot! I followed your code for the Titanic exercise, and at the end I just added a visualization to compare the two algorithms you used: SVM and Random Forest. It just helps to see the accuracy difference in a plot, and also I needed some kind of a visual comparison to put on my portfolio website so people can see the difference instead of just reading it. Here is the code I used:
```
models = []
models.append(('SVM', svm_clf))
models.append(('RandomForest', forest_clf))
results = []
names = []
for name, model in models:
    cv_results = cross_val_score(model, X_train, y_train, cv=10)
    results.append(cv_results)
    names.append(name)
    msg = "%s: %f " % (name, cv_results.mean())
    print(msg)

fig = plt.figure()
fig.set_size_inches(15, 10)
fig.suptitle('Algorithm Comparison', fontsize=30)
ax = fig.add_subplot(111)
plt.boxplot(results)
ax.set_xticklabels(names)
ax.tick_params(direction='out', length=6, width=2, labelsize=30)

plt.show()
```
I am inspired by an article at machinelearningmastery.com written by Jason Brownlee to draw this plot. I wanted to share, because I think it is useful. The resulting graph is (y-axis =  cross_val_score):
![screen shot 2018-05-20 at 6 54 19 pm](https://user-images.githubusercontent.com/35677173/40324781-72c8f030-5cee-11e8-9496-ed2b9c7db0bf.png)

**Comment by debasish2256** [comment]
Thanks for reading..

**Comment by ageron** [comment]
Hi @nyilmaz1 ,
Thanks a lot for your kind message and your code to plot this graph, this is really nice!  I'll add it to the Jupyter notebook.
I hope you will find the rest of the book useful too,
Cheers,
Aurélien

**Comment by ageron** [comment]
I made the code a bit shorter. The tick labels are a bit small, but it remains readable:

```python
plt.figure(figsize=(8, 4))
plt.plot([1]*10, svm_scores, ".")
plt.plot([2]*10, forest_scores, ".")
plt.boxplot([svm_scores, forest_scores], labels=("SVM","Random Forest"))
plt.ylabel("Accuracy", fontsize=14)
plt.show()
```

**Comment by ageron** [comment]
Just pushed the change, thanks again!  :)

**Comment by debasish2256** [comment]
THis is to notify you that the previous email hasnt been inititalted by me.
And i do not bear no responsibility of anything regarding this. It was a
mistake
