### ISSUE TITLE
CH 16: Q-Values

### ISSUE THREAD

**Issue by mfuellbier** [ageron/handson-ml#227]
Hello,
as far as I understood, computing Q-values is done by an iteration algorithm (Equation 16-3). Since this is a series (indefinite sum), you either have to compute all the Q-values until the game is over, or clip the sum after a number of steps.

But the pacman example uses only the reward of the the last action and the maximal reward of the next possible actions to compute the target Q-value for the online-DQN (see cell 69 on https://github.com/ageron/handson-ml/blob/master/16_reinforcement_learning.ipynb: `y_val = rewards + continues * discount_rate * max_next_q_values`). This means, that only two consecutive steps are used to compute the Q-value, which does not seem to be very foresightful.

Wouldn't it be more effective, to compute the Q-values as in Equation 16-3?

**Comment by ageron** [comment]
Closing stale issues. Please reopen if you are still experiencing a problem.
