### ISSUE TITLE
Understanding the Input Parameters in RNN

### ISSUE THREAD

**Issue by raagas** [ageron/handson-ml#233]
Hi,

I'm having a hard time to understand the different "jargons" used in RNN. They are the following:
`batch_size`, `time_steps`, `inputs` and `instances`.

Let me go through my understanding of each input parameters & please correct me where I'm wrong.
Suppose I've got a sequence of numbers and I want to predict the next number. The numbers are the following:
`[1,2,3,4,5,....,100]`

`time_steps`: This parameter means how far RNN will look into past before it predicts the future. For simplicity, I want to predict 1 number ahead. And want to do after I see 10 numbers in the past. So, in this case, `time_steps` will be 10.

`inputs`: These are the values at each `time_steps`. In first `time_step` (`t`) the `inputs` are
`t0`: `[1]`

`t1`: `[2]`

    .
    .
    .

`t10`: [10]`

`batch_size`: This helps in efficient computation of RNN model. Suppose my `batch_size` is 2. In that case, at `time_step` 2, the RNN input will be

    t0: [1]
    t0: [11]

Then what's the usage of `instances`?  Is it means each loop over batch? E.g. there are 5 batches, each of size 2. Then there will be 5 `instances`.

Please help me correct my understanding.

Thanks!

**Comment by ageron** [comment]
Hi @raagas ,
You're mostly correct, except for the instances.  A batch is composed of multiple instances (in your example, 2 instances), and each instance is one sequence.

Each batch fed to an RNN is usually 3 dimensional: the first is the number of instances in the batch (i.e., the batch size), the second is the number of time steps, and the third is the dimensionality of the inputs at each time step.  In your example, it would be [2, 10, 1], for example:

```python
X_batch = [
    [[1],[2],[3],[4],[3],[2],[0],[-1],[3],[6]],
    [[0],[0],[-1],[0],[1],[3],[4],[5],[4],[4]],
]
```

The targets are usually two or three dimensional, depending on whether your network predicts a single vector or a sequence.  For example, if you are just predicting the value at t+1, it would be something like:

```python
y_batch = [
    [7],
    [3],
]
```

The shape is [batch_size, output dimensionality].  In your case it's [2, 1].

However, when doing forecasting, it is often preferable to predict the full sequence shifted one time step into the future. This limits overfitting and accelerates training:

```python
y_batch = [
    [[2],[3],[4],[3],[2],[0],[-1],[3],[6],[7]],
    [[0],[-1],[0],[1],[3],[4],[5],[4],[4];[3]],
]
```

Hope this helps,
Aurélien

**Comment by raagas** [comment]
Thanks Aurélien! This was really helpful. Just to confirm my understanding on `instances`, you are saying each element of `batch_size` is an `instance`?

Thanks again!

**Comment by ageron** [comment]
My pleasure.  Yes, exactly.

**Comment by raagas** [comment]
Thanks a lot Aurélien! You are as wonderful as your book!
