### ISSUE TITLE
I get  this error message - Chapter 2, code[47

### ISSUE THREAD

**Issue by kfellague** [ageron/handson-ml#238]
```
NameError                                 Traceback (most recent call last)
<ipython-input-47-b4b47ed4e188> in <module>()
      1 import matplotlib.image as mpimg
----> 2 california_img=mpimg.imread(PROJECT_ROOT_DIR + '/images/end_to_end_project/california.png')
      3 ax = housing.plot(kind="scatter", x="longitude", y="latitude", figsize=(10,7),
      4                        s=housing['population']/100, label="Population",
      5                        c="median_house_value", cmap=plt.get_cmap("jet"),

NameError: name 'PROJECT_ROOT_DIR' is not defined
```

**Comment by ageron** [comment]
Hi @kfellague ,

To keep the book focused on the important points, I left out some details, such as defining some constants.  Hopefully the constant's name should make sense: it should point to the project's root directory.  In the jupyter notebook, this constant is defined as "." in the first cell.  I suggest you follow along with the Jupyter notebook while reading the book (plus, I added some comments when there were modifications to the API, or errata).
Hope this helps,
Aurélien

**Comment by kfellague** [comment]
Thanks.   I am going through the book which is great, The underlying
assumptions is you have good software skills.  This is the hard part for me
understanding what all detailed code means,  I am from aerospace/automotive
traditional mechanical engineering background.  So much to learn.  My goal
is to use ML for aircraft maintenance & failure predictions for example.
If you know of some resources in this area, please let me know.

Kader Fellague
