### ISSUE TITLE
Chapter 1 - error in code

### ISSUE THREAD

**Issue by kfellague** [ageron/handson-ml#239]
Hi,

When I try to run the code for chapter 1, I get this error.  It seems that it cannot find the cvs file. 

Thanks

Kader

```python
FileNotFoundError                         Traceback (most recent call last)
<ipython-input-13-6f170f733fda> in <module>()
      7 
      8 # Load the data
----> 9 oecd_bli = pd.read_csv(datapath + "oecd_bli_2015.csv", thousands=',')
     10 gdp_per_capita = pd.read_csv(datapath + "gdp_per_capita.csv",thousands=',',delimiter='\t',
     11                              encoding='latin1', na_values="n/a")
```

**Comment by kaiwakari** [comment]
You don't need to use that same path location which he has mentioned. 
What you can do is: First go to the file location in your system and find the path of the file location.
- Now import os 
- os.chdir('location path')
- Now read the file in pandas through pd.read_csv(' filename')
- Now you can again change the path to your current Jupyter notebook path thro-ugh os.chdir() library.

**Comment by ageron** [comment]
Hi @kfellague,

Did you download the whole project or just the notebook? You need the whole project, which contains the CSV file you are looking for, in the `datasets\lifesat` directory.

Then you need to set the `datapath` to the path of the directory that contains the `oecd_bli_2015.csv` file.  If you are running the Jupyter notebook, then it should contain:

```python
import os
datapath = os.path.join("datasets", "lifesat", "")
```

Everything should work out of the box if you download the whole project, and run the Jupyter notebook.  However, if you are running the code somewhere else, then you might need to change the `datapath`. For example, if the CSV file is located in `C:\Users\kfellague\handson-ml\datasets\lifesat\`, then you can write:

```python
lifesat = r"C:\Users\kfellague\handson-ml\datasets\lifesat\"
```

Hope this helps.

**Comment by kfellague** [comment]
Thanks!
