### ISSUE TITLE
Chapter 14: Basic RNN results differs from "Static Unrolling"

### ISSUE THREAD

**Issue by achintyasarkar** [ageron/handson-ml#240]
Hi,

Can you please explain little bit why the simulation code (basic RNN) is differ from using "Static Unrolling" as they are given the same input. However, you have mentioned that both creates the "exact same model".

Best,
Achintya

**Comment by ageron** [comment]
Hi @achintyasarkar ,

Thanks for your question.  The weights are initialized randomly, so the output will vary.  But the math equations are the same.

Hope this helps,
Aurélien

**Comment by achintyasarkar** [comment]
Thanks for your reply. It's now clear.
Best,
Achintya
