### ISSUE TITLE
Chapter 9, Mini-batch training with housing data throws an error: InvalidArgumentError

### ISSUE THREAD

**Issue by wimurr** [ageron/handson-ml#242]
Hi, I'm trying the Chapter 9 examples. Everything is fine until I try the mini-batch example. The problem appears to be with using placeholders, as everything runs fine for the examples with constant nodes. My code follows, and should be identical to the book's. What is going wrong? Please help, I really like the book but feel stuck now! Code and error message attached. Thank you!

[Hands-on-ML_ch_9_california_housing_demo_4_mini-batch_test_w_multiple_batches.py.txt](https://github.com/ageron/handson-ml/files/2116803/Hands-on-ML_ch_9_california_housing_demo_4_mini-batch_test_w_multiple_batches.py.txt)
[Error Message.txt](https://github.com/ageron/handson-ml/files/2116807/Error.Message.txt)

**Comment by ageron** [comment]
Hi @wimurr,
I'll take a look at this code probably tomorrow.  Could you please tell me the OS, python version and scikit-learn and tensorflow versions you are using? Thanks.

**Comment by ageron** [comment]
Okay, I believe I have found the problems:

* on line 63, when you run `mse.eval()`, it crashes because the `mse` depends on `X` and `y`, so if they are placeholders you need to feed them.
* also, your code never calls `fetch_batch()` so it will crash when it reaches the line with `X_batch` and `y_batch`.

You can fix both problems by modifying the code like so:

```python
with tf.Session() as sess:
    sess.run(init)

    for epoch in range(n_epochs):
        for batch_index in range(n_batches):
            X_batch, y_batch = fetch_batch(epoch, batch_index, batch_size)
            mse_val, _ = sess.run([mse, training_op], feed_dict={X: X_batch, y: y_batch})
        if epoch % 10 == 0:
            print("Epoch", epoch, "MSE =", mse_val)

    best_theta = theta.eval()
```

Hope this helps,
Aurélien

**Comment by wimurr** [comment]
Thanks, Aurélien, yes, I didn't see that the feed_dict was required earlier than when I provided it. It all runs fine now, thanks again very much for your help!
