### ISSUE TITLE
Chapter 2: Transformation pipelines  (fit.transform function)

### ISSUE THREAD

**Issue by kfellague** [ageron/handson-ml#243]
The book is great.  I am having fun with it. but some times I get stuck with the code. 
I am having a hard time running this part of the code from Scikit-learn.  Not sure if I am missing something in the arguments.  Here a screenshot.  Thanks.

https://screenshotscdn.firefoxusercontent.com/images/893e71e7-87ae-42de-bd06-693965775d59.png

**Comment by ageron** [comment]
Hi @kfellague ,
Thanks for your kind words, I'm glad you like the book.  Unfortunately, the important part of the exception is usually at the very bottom, so I can't really tell what's wrong in this example.  Could you please copy/paste the full exception stack trace here?
Also, please specify your O.S., python version and scikit-learn version. Thanks!

**Comment by kfellague** [comment]
[image: image.png]


[image: image.png]
[image: image.png]

Thanks for your email.  Please find attached copies of errors I got from
running the code.

I am using Windows 10, 64-bit, Scikit-learn 0.19.1 (Jupyter), python 3.6.5
(Jupyter)

Thanks again.

Kader Fellague

**Comment by ageron** [comment]
Hi @kfellague , unfortunately the images are not showing.  Can you please copy&paste the stacktrace? Thanks.

**Comment by kfellague** [comment]
Hi Aurelien,

There are 3 png files attached to this emails showing the stack traceback
(sent on June 22).  I am able to read them.
Hope this helps.

Thanks




---------- Forwarded message ---------

**Comment by ageron** [comment]
Hi @kfellague ,
I don't actually receive the emails directly, they are received by github which parses them and updates the corresponding issue online: please visit https://github.com/ageron/handson-ml/issues/243 to see what I see. There's no image here.
:)

**Comment by ageron** [comment]
Closing this issue. Please reopen if you still experience the problem.
