### ISSUE TITLE
chapter 3 titanic Question

### ISSUE THREAD

**Issue by nitml** [ageron/handson-ml#248]
hi,
In titanic question in jupyter notebook `DataFrameSelector` code was:

```python
#cell 110
class DataFrameSelector(BaseEstimator, TransformerMixin):
    def __init__(self, attribute_names):
        self.attribute_names = attribute_names
    def fit(self, X, y=None):
        return self
    def transform(self, X):
        return X[self.attribute_names]
```

but should not the last line be : 

```python
return X[self.attribute_names].values
```

if it is `X[self.attribute_names]` then retured object will still be a `pandas.DataFrame` but we want `numpy.array` so that it can be used in sklearn.

and also should not we be dropping `Survived` column for `X_train`  before:

```python
#cell 118
X_train = preprocess_pipeline.fit_transform(train_data)
```

**Comment by ageron** [comment]
Hi @nitml ,

Good questions. Scikit-Learn estimators actually accept `DataFrame`s as inputs: they just use the `values` automatically.
Regarding dropping the `Survived` column before calling `fit_transform()`, it might indeed be safer but in this particular case the pipeline uses the `DataFrameSelector` transformer to select a subset of the columns, and this does not include the `Survived` column, so we're fine.

For example:

```python
cat_pipeline = Pipeline([
        ("select_cat", DataFrameSelector(["Pclass", "Sex", "Embarked"])),
        ("imputer", MostFrequentImputer()),
        ("cat_encoder", OneHotEncoder(sparse=False)),
    ])
```

**Comment by nitml** [comment]
So what will be the difference if I use "X[self.attribute_names].values" or if I use 
"X[self.attribute_names]"

**Comment by nitml** [comment]
wasn't the whole point of writing DataFrameSelector class was to make dataframe into numpy ?

 but if sklearn can handle dataframe why do we need DataFrameSelector class ?

**Comment by ageron** [comment]
My pleasure :)

The point of the `DataFrameSelector` is to *select* the appropriate columns in the `DataFrame`.  The numerical pipeline selects the numerical columns, while the categorical pipeline selects the categorical columns.
If you just passed the original `DataFrame` to a Scikit-Learn estimator, it would just gets its `values`, but this would contain a mix of numerical and categorical columns (not to mention the `Survived` column!), and it would fail.
Hope this helps

**Comment by nitml** [comment]
Thanks Great explanation !!
