### ISSUE TITLE
Exercise 2, Chapter 13

### ISSUE THREAD

**Issue by jingw222** [ageron/handson-ml#25]
Hi Aurélien, 

In this exercise, does it implicitly assume three different filters are applied to the three input channel (RGB) independently like `depthwise_conv2d()`? Previously, only one filter operates on the same patch across different channels. Is that the case? Is there any rules regarding how to choose these two ways of applying filters?

**Comment by ageron** [comment]
Hi James,

In convolutional neural networks, the default is to use `tf.layers.conv2d()` which creates filters that span across all the input channels (i.e. the second option you mentionned).  The other `conv2d()` variants are much less used.

Regards,
Aurélien
