### ISSUE TITLE
Chapter 2: savefig fails the first time it's run due to directory not existing

### ISSUE THREAD

**Issue by Undrinkable** [ageron/handson-ml#251]
In 02_end_to_end_machine_learning_project.ipynb, on input line 12, savefig will fail when run for the first time because the images directory does not exist.
The fix is to check if the directory exists first, and if not, create it.

**Comment by ageron** [comment]
Hi @Undrinkable ,
Thanks for your feedback. The notebooks assume that the project was cloned or downloaded completely.  If you only download the notebooks, without the accompanying files and directories, then errors like this will occur. I recommend you clone the whole project (it contains the `images/end_to_end_project` directory).
Hope this helps.

**Comment by Undrinkable** [comment]
I see. I saw that we create the housing directory if it is not already present on input line 2, so I assumed that we would want to handle that case for images as well.
Thanks for your response!

**Comment by ageron** [comment]
That's a good point, the housing directory was initially not part of the project, and it would be created by the notebook, but some people had trouble downloading the data, so I included it in the project.
