### ISSUE TITLE
chapture 8 ploting projection 

### ISSUE THREAD

**Issue by nitml** [ageron/handson-ml#252]
i'm having trouble understanding following code of chapter 8 ploting projection and plane of   jupyter notebook cell 23 and 24 code : 

```python
R = C.T.dot(C)
z = (R[0, 2] * x1 + R[1, 2] * x2) / (1 - R[2, 2])
```

can u please explain it to me.

**Comment by ageron** [comment]
Aha, yes, it took me a while to figure that one out.  I don't have the time right now (off to Singapore tomorrow), but I'll try to remember how I found this.  I suppose it's not urgent? :)

**Comment by johnvorsten** [comment]
Was there any solution to this?  I'm running into the same question.. I thought the plane equation would be found with the first two eigenvectors cross product - or the third eigenvector.  But I still don't understand where the "1-" came from

**Comment by ageron** [comment]
Hi @johnvorsten ,
Thanks for your question.
To project the dataset from 3D down to 2D, we must multiply it by V[:, 2].
To project the dataset back from 2D up to 3D, we must multiply it by V.T[:2], where V.T is the transpose of V.
If we project the dataset from 3D down to 2D and then back to 3D, we get the 3D coordinates of the projections of all the original points onto the 2D plane in 3D space.
If we define R = V[:, 2] @ V.T[:2], then simplify multiplying the original 3D dataset by R will give use these coordinates of the projection onto the plane in 3D space.

Now the points on that plane are the only ones that do not change when projected down to 2D and back to 3D. So if we have a matrix P=[[x1, x2, z]] containing a single instance with 3D coordinates x1, x2 and z, then P @ R just returns P. So if we look into what exactly is calculated when we compute P @ R, we get:

x1 * R[0, 0] + x2 * R[0, 1] + z * R[0, 2] = x1
x1 * R[1, 0] + x2 * R[1, 1] + z * R[1, 2] = x2
x1 * R[2, 0] + x2 * R[2, 1] + z * R[2, 2] = z

Looking at the last line, you can see that you can turn it into:
x1 * R[2, 0] + x2 * R[2, 1] = z - z * R[2, 2]

Then factorize by z:
x1 * R[2, 0] + x2 * R[2, 1] = z * (1 - R[2, 2])

And divide both sides by (1 - R[2, 2]):
(x1 * R[2, 0] + x2 * R[2, 1]) / (1 - R[2, 2]) = z

And that's how the 1 - R[2,2] appears.
Hope this helps.

**Comment by johnvorsten** [comment]
That makes a lot of sense - it is just he projection of the first two dimensions onto the planes basis if I understand correctly.  Thanks!

**Comment by ageron** [comment]
Closing stale issues. Please reopen if you are still experiencing a problem.
