### ISSUE TITLE
chapture 8 Unsupervised learning

### ISSUE THREAD

**Issue by nitml** [ageron/handson-ml#253]
Is there any  document file for theory of unsupervised learning  whose code are present in Jupyter Notebook  of chapter 8 as it is not present in book ?
also can you please explain me image segmentation code of notebook  : 

```python
X = image.reshape(-1, 3)
kmeans = KMeans(n_clusters=8, random_state=42).fit(X)
segmented_img = kmeans.cluster_centers_[kmeans.labels_]
segmented_img = segmented_img.reshape(image.shape)
```

also what is the conclusion of "limit of k-means" in notebook  ? 
I can see that the resultant clustering of " kmeans_bad" is bad but what is the reason for that ?

**Comment by ageron** [comment]
Hi @nitml ,

The first edition of my book covers dimensionality reduction in chapter 8, but not the other unsupervised learning tasks, such as clustering or anomaly detection. This will be covered in the next edition of my book.

The image segmentation code works like this: the first line reshapes the image to a long list of colors (each color is 3D: red, green, blue). Then I create a KMeans object and use it to cluster the colors. The `kmeans.labels_` is a long list of cluster IDs (e.g., [2, 1, 1, 0, 2, 7, 1, 3, 0, 5, 4, 4, 2...]). By using these IDs to index the `kmeans.cluster_centers_`, I get back a long list of colors, where each color is the cluster center for the given cluster ID. It's somewhat like writing `[kmeans.cluster_centers_[2], kmeans.cluster_centers_[1], kmeans.cluster_centers_[1], kmeans.cluster_centers_[0],...`. In other words, for every color I get its cluster's central color (e.g., all shades of green may be mapped to a single green color). Finally, I just reshape this long list of colors to the original image's shape.

Regarding the limit of K-means, basically it does not work well when the clusters have very different sizes, densities, or if they are elongated, as you can see on the `bad_kmeans_diagram`: the clustering on the right is clearly worse, yet its inertia is lower (so it will be preferred by the algorithm).

Hope this helps,
Aurélien

**Comment by nitml** [comment]
Again Great Explanation !!!
Also i would like to suggest that in 2nd edition of book exercise there should be programming  questions on feature  selection and extraction .For example as i was doing Titanic question in Chapter 3 and then i saw some kaggle solution lots of feature selection and extraction was done to improve performance.
As always Thanks for your time,
Enjoy Your Trip !!!!!

**Comment by ageron** [comment]
I'm glad I could help.  Thanks for the suggestions regarding feature selection/extraction, that's a good point.
