### ISSUE TITLE
I am getting very close numbers to the book 

### ISSUE THREAD

**Issue by amgenene** [ageron/handson-ml#256]
For the forest_reg and decision tree models I get numbers very close but different than the numbers in the book why do you think this could be??

**Comment by ageron** [comment]
Hi @amgenene ,
Interesting. Random forests and decision trees are naturally stochastic, so they will always give slightly different results every time you train them. However, I was careful to set the `random_state` everywhere, so if you run the code multiple times on the same platform, it should always give the same result. The only reasons I can think of for getting different results are:

* if I forgot a `random_state=42` somewhere. If this is the case, then you should get slightly different results every time you run the code. Is it the case?
* if you are using a different platform where the random number generator produces different sequences of pseudo-random numbers. If this is the case, then you should get the same result at every run, but not the same as mine.
* if you are setting `n_jobs` to some other value than 1: in this case, training will be multithreaded, and you will get different results depending on the order in which threads pull from the random number generator.
* if you are using a 32 bit platform (I use a 64-bit platform)?

Hope this helps,
Aurélien

**Comment by amgenene** [comment]
Thank you I realized that was the issue I am really enjoying this textbook alot and hope you guys the best moving forward!!
