### ISSUE TITLE
plot_digits

### ISSUE THREAD

**Issue by batblah** [ageron/handson-ml#257]
I'm new to these libraries and while I was running the code in Chapter 3:

    cl_a, cl_b = 3, 5
    X_aa = X_train[(y_train == cl_a) & (y_train_pred == cl_a)]
    X_ab = X_train[(y_train == cl_a) & (y_train_pred == cl_b)]
    X_ba = X_train[(y_train == cl_b) & (y_train_pred == cl_a)]
    X_bb = X_train[(y_train == cl_b) & (y_train_pred == cl_b)]

    plt.figure(figsize=(8,8))
    plt.subplot(221); plot_digits(X_aa[:25], images_per_row=5)
    plt.subplot(222); plot_digits(X_ab[:25], images_per_row=5)
    plt.subplot(223); plot_digits(X_ba[:25], images_per_row=5)
    plt.subplot(224); plot_digits(X_bb[:25], images_per_row=5)

I get the following error:

    ---------------------------------------------------------------------------
    NameError                                 Traceback (most recent call last)
    <ipython-input-91-df1c82686923> in <module>()
          1 plt.figure(figsize=(8,8))
    ----> 2 plt.subplot(221); plot_digits(X_aa[:25], images_per_row = 5)
          3 plt.subplot(222); plot_digits(X_ab[:25], images_per_row=5)
          4 plt.subplot(223); plot_digits(X_ba[:25], images_per_row=5)
          5 plt.subplot(224); plot_digits(X_bb[:25], images_per_row=5)
    
    NameError: name 'plot_digits' is not defined
I searched online but can't find resources on this plot_digits function. Can you help?

**Comment by ageron** [comment]
Hi @batblah ,

This function is defined in the Jupyter notebook (in cell `In 8`):

```python
# EXTRA
def plot_digits(instances, images_per_row=10, **options):
    size = 28
    images_per_row = min(len(instances), images_per_row)
    images = [instance.reshape(size,size) for instance in instances]
    n_rows = (len(instances) - 1) // images_per_row + 1
    row_images = []
    n_empty = n_rows * images_per_row - len(instances)
    images.append(np.zeros((size, size * n_empty)))
    for row in range(n_rows):
        rimages = images[row * images_per_row : (row + 1) * images_per_row]
        row_images.append(np.concatenate(rimages, axis=1))
    image = np.concatenate(row_images, axis=0)
    plt.imshow(image, cmap = matplotlib.cm.binary, **options)
    plt.axis("off")
```

Make sure you run the cells in the Jupyter notebooks 
in the right order, everything should work fine.

Hope this helps,
Aurélien

**Comment by Parikshit22** [comment]
thank you so much.

**Comment by batblah** [comment]
Thanks for reply.

**Comment by XxAakashxX** [comment]
Hey after using defining that function i am getting this new zero divisibility error!
```
`---------------------------------------------------------------------------
ZeroDivisionError                         Traceback (most recent call last)
<ipython-input-64-46cb86a220bd> in <module>
      2 plt.subplot(221);plot_digits(X_aa[:25],images_per_row = 5)
      3 plt.subplot(222);plot_digits(X_ab[:25],images_per_row=5)
----> 4 plt.subplot(223);plot_digits(X_ba[:25],images_per_row = 5)
      5 plt.subplot(224);plot_digits(X_bb[:25],images_per_row=5)
      6 plt.show()

<ipython-input-63-a42fe1f80d92> in plot_digits(instances, images_per_row, **options)
      4     images_per_row = min(len(instances), images_per_row)
      5     images = [instance.reshape(size,size) for instance in instances]
----> 6     n_rows = (len(instances) - 1) // images_per_row + 1
      7     row_images = []
      8     n_empty = n_rows * images_per_row - len(instances)

ZeroDivisionError: integer division or modulo by zero`
```

**Comment by Euphoride** [comment]
Hi @XxAakashxX!

So it seems that when we define `cl_a` and `cl_b`, from now on we have to define them as characters and not integers (as the prediction labels are characters and not integers)

So in your code, replace
`cl_a, cl_b = 3, 5`

with 

`cl_a, cl_b = '3', '5'`

Hope this helps!

**Comment by elevenHeY** [comment]
Hello,

i defined **cl_a** and **cl_b** as integers and changed the **def_plot_digits** to:


def plot_digits(instances, images_per_row=10, **options):
    size = 28
    images_per_row = min(len(instances), images_per_row)
    images = [instance.reshape(size,size) for instance in instances]
    **if images_per_row == 0:
       images_per_row = 0.1
    else:
        images_per_row = images_per_row
        pass**
    n_rows = (len(instances) - 1) // images_per_row + 1
    row_images = []
    n_empty = n_rows * images_per_row - len(instances)
    images.append(np.zeros((size, size * n_empty)))
    for row in range(n_rows):
        rimages = images[row * images_per_row : (row + 1) * images_per_row]
        row_images.append(np.concatenate(rimages, axis=1))
    image = np.concatenate(row_images, axis=0)
    plt.imshow(image, cmap = matplotlib.cm.binary, **options)
    plt.axis("off")


and it works!

**Comment by kian79** [comment]
Hi,
Thanks for your answers, but after doing everything I get the following error.
`---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-68-68452429f4e7> in <module>
      1 plt.figure(figsize=(8,8))
----> 2 plt.subplot(221); plot_digits(X_aa[:25],images_per_row=5)
      3 plt.subplot(222); plot_digits(X_ab[:25],images_per_row=5)
      4 plt.subplot(223); plot_digits(X_ba[:25],images_per_row=5)
      5 plt.subplot(224); plot_digits(X_bb[:25],images_per_row=5)

<ipython-input-67-1cbdcaecf053> in plot_digits(instances, images_per_row, **options)
      2     size = 28
      3     images_per_row = min(len(instances), images_per_row)
----> 4     images = [instance.reshape(size,size) for instance in instances]
      5     n_rows = (len(instances) - 1) // images_per_row + 1
      6     row_images = []

<ipython-input-67-1cbdcaecf053> in <listcomp>(.0)
      2     size = 28
      3     images_per_row = min(len(instances), images_per_row)
----> 4     images = [instance.reshape(size,size) for instance in instances]
      5     n_rows = (len(instances) - 1) // images_per_row + 1
      6     row_images = []

AttributeError: 'str' object has no attribute 'reshape'`

**Comment by ageron** [comment]
Hi @kian79 ,
It looks like `X_aa` contains strings, which is very weird. Could you please double check that the code is exactly like in the notebook? I just tried running the notebook in Colab, it works fine:
https://colab.research.google.com/github/ageron/handson-ml/blob/master/03_classification.ipynb

**Comment by ageron** [comment]
You may want to pull the latest version of the notebooks?
Also, note that there is now a second edition of the book, you might want to look into it (especially for the 2nd part of the book using TensorFlow). All the code examples are open source, you can check them out at:
https://github.com/ageron/handson-ml2

**Comment by sivadhulipala1999** [comment]
Hello, 

I was facing the issue pointed out by @kian79. What worked for me was the redefinition of plot_digits function. 

`def plot_digits(instances, images_per_row=10, **options):
    size = 28
    images_per_row = min(len(instances), images_per_row)
    images = [np.array(instances.iloc[i]).reshape(size, size) for i in range(instances.shape[0])] #change done here 
    
    if images_per_row == 0:
       images_per_row = 0.1
    
    n_rows = (len(instances) - 1) // images_per_row + 1
    row_images = []
    n_empty = n_rows * images_per_row - len(instances)
    images.append(np.zeros((size, size * n_empty)))
    for row in range(n_rows):
        rimages = images[row * images_per_row : (row + 1) * images_per_row]
        row_images.append(np.concatenate(rimages, axis=1))
    image = np.concatenate(row_images, axis=0)
    plt.imshow(image, cmap = plt.cm.binary, **options)
    plt.axis("off")`



Hope this helps!

**Comment by sivadhulipala1999** [comment]
Hello, 

I was facing the same issue as @kian79. What worked for me was the redefinition of plot_digits function. 

`def plot_digits(instances, images_per_row=10, **options):
    size = 28
    images_per_row = min(len(instances), images_per_row)
    images = [np.array(instances.iloc[i]).reshape(size, size) for i in range(instances.shape[0])] #change done here
    
    if images_per_row == 0:
       images_per_row = 0.1
    
    n_rows = (len(instances) - 1) // images_per_row + 1
    row_images = []
    n_empty = n_rows * images_per_row - len(instances)
    images.append(np.zeros((size, size * n_empty)))
    for row in range(n_rows):
        rimages = images[row * images_per_row : (row + 1) * images_per_row]
        row_images.append(np.concatenate(rimages, axis=1))
    image = np.concatenate(row_images, axis=0)
    plt.imshow(image, cmap = plt.cm.binary, **options)
    plt.axis("off")`

Calling the reshape method on each instance directly might have been the problem. Converting each row of pixels in the image to a numpy array and then calling the reshape method is what fixed the issue here.

**Comment by sivadhulipala1999** [comment]
Hello,

I was facing the same issue as @kian79. What worked for me was the redefinition of plot_digits function.

`def plot_digits(instances, images_per_row=10, **options):
    size = 28
    images_per_row = min(len(instances), images_per_row)
    images = [np.array(instances.iloc[i]).reshape(size, size) for i in range(instances.shape[0])]
    
    if images_per_row == 0:
       images_per_row = 0.1
    
    n_rows = (len(instances) - 1) // images_per_row + 1
    row_images = []
    n_empty = n_rows * images_per_row - len(instances)
    images.append(np.zeros((size, size * n_empty)))
    for row in range(n_rows):
        rimages = images[row * images_per_row : (row + 1) * images_per_row]
        row_images.append(np.concatenate(rimages, axis=1))
    image = np.concatenate(row_images, axis=0)
    plt.imshow(image, cmap = plt.cm.binary, **options)
    plt.axis("off")`



Calling the reshape method on each instance directly might have been the problem. Converting each row of pixels in the image to a numpy array and then calling the reshape method is what fixed the issue here.

**Comment by ageron** [comment]
Hi @sivadhulipala1999 ,

Thanks for your feedback. It looks like your dataset is a Pandas DataFrame, when it should be a NumPy array. This is probably due to a change in the function `fetch_openml()` which occurred in Scikit-Learn 0.24: it now returns a DataFrame by default. To prevent this from happening (and hopefully fix the issue), you should pass `as_frame=False` when calling the `fetch_openml()` function. I fixed this a couple months ago in the notebooks, so you can just `git pull` the latest code.

Hope this helps.

**Comment by lamwin24** [comment]
> Hi, Thanks for your answers, but after doing everything I get the following error.
> 
> ```
> `---------------------------------------------------------------------------
> AttributeError                            Traceback (most recent call last)
> <ipython-input-68-68452429f4e7> in <module>
>       1 plt.figure(figsize=(8,8))
> ----> 2 plt.subplot(221); plot_digits(X_aa[:25],images_per_row=5)
>       3 plt.subplot(222); plot_digits(X_ab[:25],images_per_row=5)
>       4 plt.subplot(223); plot_digits(X_ba[:25],images_per_row=5)
>       5 plt.subplot(224); plot_digits(X_bb[:25],images_per_row=5)
> 
> <ipython-input-67-1cbdcaecf053> in plot_digits(instances, images_per_row, **options)
>       2     size = 28
>       3     images_per_row = min(len(instances), images_per_row)
> ----> 4     images = [instance.reshape(size,size) for instance in instances]
>       5     n_rows = (len(instances) - 1) // images_per_row + 1
>       6     row_images = []
> 
> <ipython-input-67-1cbdcaecf053> in <listcomp>(.0)
>       2     size = 28
>       3     images_per_row = min(len(instances), images_per_row)
> ----> 4     images = [instance.reshape(size,size) for instance in instances]
>       5     n_rows = (len(instances) - 1) // images_per_row + 1
>       6     row_images = []
> 
> AttributeError: 'str' object has no attribute 'reshape'
> ```


It works!

cl_a, cl_b = 3,5
X_aa = np.array(X_train[(y_train == cl_a) & (y_train_pred == cl_a)])  
X_ab = np.array(X_train[(y_train == cl_a) & (y_train_pred == cl_b)])  
X_ba = np.array(X_train[(y_train == cl_b) & (y_train_pred == cl_a)]) 
X_bb = np.array(X_train[(y_train == cl_b) & (y_train_pred == cl_b)])  

plt.figure(figsize=(8,8))
plt.subplot(2,2,1); plot_digits(X_aa[:25], images_per_row=5)
plt.subplot(2,2,2); plot_digits(X_ab[:25], images_per_row=5)
plt.subplot(2,2,3); plot_digits(X_ba[:25], images_per_row=5)
plt.subplot(2,2,4); plot_digits(X_bb[:25], images_per_row=5)
plt.show()

**Comment by rahulsingh04** [comment]
# Note that the label is a string. Most ML algorithms expect numbers, so let’s cast y to integer:

y = y.astype(np.uint8)
y


covert the string to the integer:-
