### ISSUE TITLE
Format on last line of Chapter 14, solution to problem 7 incorrect

### ISSUE THREAD

**Issue by hhummel** [ageron/handson-ml#266]
You have 1.00% as probability Reber string is correct, but should be 1.00

Estimated probability that these are Reber strings:
BPBTSSSSSSSSSSSSXXTTTTTVPXTTVPXTTTTTTTVPXVPXVPXTTTVVETE: 0.04%
BPBTSSSSSSSSSSSSXXTTTTTVPXTTVPXTTTTTTTVPXVPXVPXTTTVVEPE: 1.00%

**Comment by ageron** [comment]
Good catch @hhummel , thanks.  Just fixed this.
