### ISSUE TITLE
Saver not working on Chapter 14 problem 7

### ISSUE THREAD

**Issue by hhummel** [ageron/handson-ml#267]
On Ubuntu I get an error from this line:

```python
saver.save(sess, "my_reber_classifier")
```

Should be:

```python
saver.save(sess, "./my_reber_classifier")
```

**Comment by ageron** [comment]
Thanks again @hhummel , fixed.

**Comment by tetsuyasu** [comment]
You respond better to issues than pull request.  I canceled the pull request which I made last week about the same issue.
Thank you for fixing it.
