### ISSUE TITLE
Chapter 16 OpenGymAi 

### ISSUE THREAD

**Issue by FarhanSajid7861** [ageron/handson-ml#278]
Hello,
When I am trying to import MsPacman, for some reason even though I ran pip-install gym, it says that I am missing the dependencies for Atari-py. 

```python
env = gym.make('MsPacman-v0')
```
```
gym.error.DependencyNotInstalled: No module named 'atari_py'.
(HINT: you can install Atari dependencies by running 'pip install gym[atari]'.)
```

With that following, error, when I ran that code, it won't install, and I was wondering if you could help with all your wisdom. Thanks so much for this great book regardless.

**Comment by ageron** [comment]
Hi @FarhanSajid7861 ,
Thanks for your question and your kind words.  When you run `pip install gym`, it only installs the base library.  For some of the environments, like the Atari environments such as MsPacMan, you need to install other libraries as well on your system. Please follow the instructions here: https://github.com/openai/gym#installation .

Note that it is only available on MacOSX or Ubuntu, not Windows.

I hope this helps,
Aurélien

**Comment by ageron** [comment]
Hi @FarhanSajid7861 , just out of curiosity, did my answer solve your problem?

**Comment by FarhanSajid7861** [comment]
Ops, I am so sorry, I was meaning to terminate this, I was actually trying to run the Mspacman code before finishing the chapter, at the end you clearly showed how to install the dependencies. It was my curosity, because I saw the Github code before finishing the chapter. But it worked perfectly fine. Sorry for the late reply. 
Great book once again.
