### ISSUE TITLE
request solution chapter 3 - standardScaler() 

### ISSUE THREAD

**Issue by alberthasudungan** [ageron/handson-ml#279]
Hai I request solution for chapter 3 practice, I wrote as this: 
 
```python
from sklearn.preprocessing import StandardScaler 
scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train.astype(np.float64))
cross_val_score(sgd_clf, X_train_scaled, y_train, cv=3, scoring="accuracy")
```

and then the output: 

```
MemoryError                               Traceback (most recent call last)
<ipython-input-70-96d9dde478da> in <module>()
      1 from sklearn.preprocessing import StandardScaler
      2 scaler = StandardScaler()
----> 3 X_train_scaled = scaler.fit_transform(X_train.astype(np.float64))
      4 cross_val_score(sgd_clf, X_train_scaled, y_train, cv=3, scoring="accuracy")
```

MemoryError: 

I try to simulate to transform X_train first and then performing cross value afterwards, but still error. I audited again `sgd_clf`, `X_train`, `y_train`, and they are all good. Error occurred when I display `X_train_scaled`. I request if there is any solution for this issue.

**Comment by ageron** [comment]
Hi @alberthasudungan ,

Thanks for your question.  You are getting an memory error, this is quite weird because your code looks good, and the MNIST dataset is not large at all, so it should easily fit in memory multiple times.  How much RAM does your computer have? Perhaps you have some other application using up all the RAM? Try to reboot your computer, look at your system's memory monitor to ensure that very little memory is used, then only start this Jupyter notebook. If the problem persists, then you may have a problem with your hardware. Alternatively, it may be because you loaded a different dataset than MNIST? Can you confirm that it is MNIST? Could you please tell me what `X_train.shape` is? Or perhaps it's a bug in your Python/NumPy/Scikit-Learn installation. What versions are you using? Could you please try to update all your libraries?

Hope this helps,
Aurélien

**Comment by ageron** [comment]
Hi @alberthasudungan , are you still experiencing the OOM issue?

**Comment by alberthasudungan** [comment]
@ageron i try to check again actually my computer was on windows version x86. I tried to run in version x64, it is all good. Thanks

**Comment by luvaihassanali** [comment]
@ageron I am having same issue on x64. On task manager memory is 22% (16GB RAM) and X_train.shape = (60000, 784). Python version 3.7.0, NumPy 1.15.1 and SciKit-Learn 0.19.2. Any help would be appreciated.

**Comment by ageron** [comment]
This sounds like a bug in one of these libraries.  The code looks good to me.   Could you please create a small python file that just loads MNIST and applies the StandardScaler, and run it independently to see if the same issue occurs?  I just want to rule out Jupyter.

**Comment by luvaihassanali** [comment]
> This sounds like a bug in one of these libraries. The code looks good to me. Could you please create a small python file that just loads MNIST and applies the StandardScaler, and run it independently to see if the same issue occurs? I just want to rule out Jupyter.


Thanks for the reply, I created this python file:
```
import numpy as np
from sklearn.datasets import fetch_mldata
from sklearn.linear_model import SGDClassifier
from sklearn.model_selection import cross_val_score, cross_val_predict
from sklearn.preprocessing import StandardScaler

mnist = fetch_mldata('MNIST original')
X, y = mnist["data"], mnist["target"]
X_train, X_test, y_train, y_test = X[:60000], X[60000:], y[:60000], y[60000:]

shuffle_index = np.random.permutation(60000)
X_train, y_train = X_train[shuffle_index], y_train[shuffle_index]
print("X_train.shape: ", X_train.shape)

y_train_5 = (y_train == 5)
y_test_5 = (y_test == 5)

sgd_clf = SGDClassifier(random_state=42, max_iter=5, tol=None)
sgd_clf.fit(X_train, y_train_5)
sgd_clf.predict([X[36000]])

scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train.astype(np.float64))
print(cross_val_score(sgd_clf, X_train_scaled, y_train, cv=3, scoring = 'accuracy'))
```
This was the output:
```
C:\Users\Luvai\Desktop\ml\env\Scripts>python mnist_test.py
C:\Users\Luvai\Desktop\ml\env\lib\site-packages\sklearn\feature_extraction\text.py:17: DeprecationWarning: Using or importing the ABCs from 'collections' instead of from 'collections.abc' is deprecated, and in 3.8 it will stop working
  from collections import Mapping, defaultdict
X_train.shape:  (60000, 784)
[0.91086783 0.91124556 0.90748612]
```

**Comment by ageron** [comment]
Thanks @luvaihassanali ,
Ouch, this seems to confirm that the problem comes from Jupyter since the same code works fine outside of it.  Could you please run the following command in a terminal and copy/paste the output here?

```shell
jupyter troubleshoot
```

Thanks,
Aurélien

**Comment by BerzinsU** [comment]
I managed to get same memory error.
What was the solution here?

**Comment by luvaihassanali** [comment]
¯\_(ツ)_/¯... I just completed it in a separate .py file

**Comment by BerzinsU** [comment]
I got it running by switching to MacOS. Seems there's specific problem with Jupyter on Win

**Comment by samaujs** [comment]
Hi Ageron,

  I have tried to create a separate python script file and execute as per "luvaihassanali" comments above on a "Ubuntu 18.04.1 LTS (GNU/Linux 4.15.0-1032-aws x86_64)" machine.  But, I have still have the same MemoryError problem with outputs as follow :

Traceback (most recent call last):
  File "mnist_test.py", line 35, in <module>
    X_train_scaled = scaler.fit_transform(X_train.astype(np.float64))
  File "/home/ubuntu/ml/VirtualEnv/env/lib/python3.6/site-packages/sklearn/base.py", line 462, in fit_transform
    return self.fit(X, **fit_params).transform(X)
  File "/home/ubuntu/ml/VirtualEnv/env/lib/python3.6/site-packages/sklearn/preprocessing/data.py", line 625, in fit
    return self.partial_fit(X, y)
  File "/home/ubuntu/ml/VirtualEnv/env/lib/python3.6/site-packages/sklearn/preprocessing/data.py", line 649, in partial_fit
    force_all_finite='allow-nan')
  File "/home/ubuntu/ml/VirtualEnv/env/lib/python3.6/site-packages/sklearn/utils/validation.py", line 598, in check_array
    array = np.array(array, dtype=dtype, order=order)
MemoryError

**Comment by horizonSky** [comment]
Maybe there is not enough memory. Use the 'free -h' command to see.

**Comment by samaujs** [comment]
Got it.  Thanks.
