### ISSUE TITLE
Chapter 16: MsPacman stops learning

### ISSUE THREAD

**Issue by Varsius** [ageron/handson-ml#284]
I tried running your example code from the notebook for playing MsPacman using the DQN-Algorithm, but I have a problem. I let it train several times for days, even with double the iterations, but it keeps getting stuck by a little bit above a Max-Q of 200 and does not improve anymore. What am I doing wrong?

**Comment by ageron** [comment]
Hi @Varsius,

You are probably not doing anything wrong, it's just that RL is pretty unstable, and tremendously hard to debug and fine-tune.  Check out this [interesting post](https://www.alexirpan.com/2018/02/14/rl-hard.html?lipi=urn%3Ali%3Apage%3Ad_flagship3_detail_base%3BCaARZ7gIQFawbgp5PuyLkw%3D%3D) by Alex Irpan who works at Google in the Brain Robotics team. It's really critical about Deep RL, yet insightful and constructive.

You can run the program multiple times, and sometimes it just doesn't learn anything, and other times it gets reasonably good (at least running away from the ghosts, but not trying to find pellets located far away, unfortunately). However, maybe it's not just that "RL is unstable", perhaps there's a bug in my code. I looked for a few hours and I didn't find anything wrong, but perhaps some fresh eyes would help. :)

Cheers,
Aurélien

**Comment by Varsius** [comment]
Thank you very much for your answer @ageron !
