### ISSUE TITLE
StandardScaler与tree_based Algorithm

### ISSUE THREAD

**Issue by point6013** [ageron/handson-ml#292]
when applying tree_based Algorithm , StandardScaler is often not used to process the data?

**Comment by ageron** [comment]
Hi @point6013 ,
Thanks for your question.  Indeed, scaling the features is typically not necessary when using tree-based algorithms.  For example, if there is just one input feature x1, and the training set contains 2 instances, one from the positive class with value x1=10, and the other from the negative class with the value x1=1000, then the decision tree's learning algorithm will try various thresholds located right in the middle of the possible values, so in this case it will try (10 + 1000)/2 = 505, and that's where the decision boundary between the two classes will be.

If you scaled the features, you would get the same result. Indeed, the mean of 10 and 1000 is 505, and the standard deviation is 495, so after scaling, the first instance would have x1_scaled = (10 - 505)/495 = -1, and the second instance would have x1_scaled = (1000-505)/495 = +1.  The decision tree would learn a decision boundary right in the middle between -1 and +1, so at x1_scaled = 0.  Once you unscale this, you realize it's the same boundary as above: 0 * 495 + 505 = 505.

So decision trees and random forests typically do not require any scaling of the input features, it's one of their many benefits.

Hope this helps,
Aurélien
