### ISSUE TITLE
What is the test_image = 2 * test_image - 1 line doing? 

### ISSUE THREAD

**Issue by iamycee** [ageron/handson-ml#293]
For the inputs to be between [-1, 1] for the pretrained inception animal classification task, the line used to scale the images is: test_image = 2 * test_image - 1 
But this does not scale the inputs between -1 and 1, does it? 
Why is it used?

**Comment by ageron** [comment]
Hi @iamycee ,

Good question.  The test image is initially scaled between 0 and 1.  Multiplying by 2 scales it between 0 and 2, and then subtracting 1 ends up with a range from -1 to 1.  In short, it converts the range [0, 1] to the range [-1, 1].

Hope this helps,
Aurélien

**Comment by iamycee** [comment]
Alright, I did not take into consideration that the original image was scaled between 0 and 1, makes sense now! Thanks for the support. Btw love your book!!
