### ISSUE TITLE
AttributeError: 'OneHotEncoder' object has no attribute 'categories_'

### ISSUE THREAD

**Issue by lidozhang** [ageron/handson-ml#294]
when i use the from future_encoders import OneHotEncoder, this error come out, why??

**Comment by ageron** [comment]
Hi @lidozhang ,

I'm guessing you did not fit the `OneHotEncoder`?  The learned parameters (whose name finished with an underscore) are created by the `fit()` method (or other `fit_*()` methods).

See this example:

```pycon
In [1]: from future_encoders import OneHotEncoder

In [2]: enc = OneHotEncoder()

In [3]: enc.fit([["A", "B"], ["A", "C"], ["B", "C"]])
Out[3]:
OneHotEncoder(categories='auto', dtype=<class 'numpy.float64'>,
       handle_unknown='error', sparse=True)

In [4]: enc.categories_
Out[4]: [array(['A', 'B'], dtype=object), array(['B', 'C'], dtype=object)]

In [5]: enc2 = OneHotEncoder()

In [6]: enc2.categories_
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-6-f81736b15790> in <module>()
----> 1 enc2.categories_

AttributeError: 'OneHotEncoder' object has no attribute 'categories_'
```

As you can see, `enc` has a `categories_` attribute, because I called `fit()` first, but `enc2` does not have this attribute, because I did not call `fit()`.

Hope this helps,
Aurélien

**Comment by lidozhang** [comment]
**hello Aurélien,
thank you very much for your help,following is our detail.
As you see,  the Out[3] works well, that indicate the OneHotEncoder is ok, 
i am confused ,why there is no attribute 'categories_'**

from sklearn.pipeline import Pipeline
from sklearn.preprocessing import StandardScaler
from sklearn.pipeline import FeatureUnion
from future_encoders import OneHotEncoder

cat_attribute= list(data_train.select_dtypes(['object']).columns.values)

catagory_pipeline = Pipeline([
        ("select_catagory", ColumnsSelector(cat_attribute)),
        ("cat_encoder", OneHotEncoder(sparse=False))
    ])


In [3]：
cat_encoder = catagory_pipeline.named_steps["cat_encoder"]
cat_encoder

Out[3]:    OneHotEncoder(categories='auto', dtype=<class 'numpy.float64'>,handle_unknown='error', sparse=False)

In [4]: cat_encoder.categories_

Out[4]:
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-198-6a732d268754> in <module>()
      1 for i in range(7):
----> 2     catagory_onehot_attribs += list(catagory_onehot_encoder.categories_[i])
      3 
      4 attributes = num_attribute + catagory_pipeline_attribs

AttributeError: 'OneHotEncoder' object has no attribute 'categories_'
