### ISSUE TITLE
How to apply the housing model in chapter 2 to a real life case ?

### ISSUE THREAD

**Issue by NourdineMazali** [ageron/handson-ml#295]
Hi Aurélien,

Thank you for the amazing book, just finished chapter 2, so far I find it practical, engaging and really straight to the point.
In relation to the housing model in chapter 2, how can I apply the model to a real life case, let's say I have a district's (longitude, latitude, housing_median_age ... ) how can I use the model to predict the housing price for that specific district ? I am probably looking for a technical solution .i.e,
request(parameters) =>response(housing price)
Hope my question makes some sense.

Thank you

**Comment by ageron** [comment]
Hi @NourdineMazali ,
Thanks, I'm glad you enjoy the book so far!  If you have a new district (longitude, latitude, etc.), you can make a prediction using your model's `predict()` method.  Note that this method takes a 2D array (i.e., either a 2D NumPy array or matrix, or a python 2D structure such as a list of lists, or a Pandas DataFrame).  If you want to make a prediction for a single district, the 2D array will contain a single row, for example:

```python
y_pred = model.predict([[123.5, 42.3, 35.5, ...]])
```

Hope this helps.

**Comment by NourdineMazali** [comment]
Merci bien @ageron , this is exactly what I was looking for, again congrats for the amazing book.
