### ISSUE TITLE
Chapter 2: does the algorithm performs better than humans?

### ISSUE THREAD

**Issue by JPFrancoia** [ageron/handson-ml#296]
Hello,

I'm reading the book at the moment and I think it's fantastic. I just finished chapter 2, and at this point, I have a question regarding the performance of the algorithm VS human performance.

Once the estimator is fully trained and optimized, its RMSE is about 49,000$. In section 2.2, it is said  that experts have an error rate of 15%. Does it mean that whatever the value of the house, experts will have an error rate of 15%? I imagine so. So for a house costing 450k, the error would be 67.5k. For cheaper houses, it would be ways less, and will actually go under the RMSE of our estimator.

So, which one is better in this case? Also, is the model sufficiently good enough so that a company would prefer it over humans?

**Comment by ageron** [comment]
Hi @JPFrancoia ,
Thanks for your kind words! :)
Great question, indeed, human performance is better than our best model, in this example.  The automated system might still be worthwhile if it allows the experts to concentrate on more interesting and/or profitable projects. ML does not always reach superhuman level, but even sub-human systems can be worthwhile.
Hope this helps!

**Comment by JPFrancoia** [comment]
>  human performance is better than our best model, in this example.

Is it all the time, or is it only for the cheaper houses?

Thank you for your answer anyway. It's always best to know the limitations of the model. Is there any way (for his example) that a model could beat the humans?

**Comment by ageron** [comment]
I'm not sure, I have not investigated much further.  I'd be interested if you manage to squeeze better performance from another model. :)

**Comment by JPFrancoia** [comment]
Thanks! Maybe I'll try one day, atm I was just curious if you knew about something better.
