### ISSUE TITLE
Is there a github repository with examples in python

### ISSUE THREAD

**Issue by Niceno** [ageron/handson-ml#298]
Hi all,

I am using the book from "Hands-On Machine Learning with Scikit-Learn & TensorFlow" by A. Geron, and am wondering if there is a repository which gives samples from the book in "pure" python form, rather then embedded in jupyter notebooks?

I am eager to try the examples, but am unable to properly run jupyter for a number of issues (installations, versions, dependencies, warnings ... it drives me crazy) and am not even sure if I want to use learn and use jupyter after all?

I did manage to extract the code for first example from the jupyter environment with copy and paste, but maybe it was already by someone for all examples?

    Thanks,

    Bojan

**Comment by ageron** [comment]
Hi @Niceno ,
I'm sorry you are experiencing difficulties with Jupyter.  If you managed to get it started, you can save the Jupyter notebook to Python:  File > Download as... Python (.py).
That said, you may run into problems with Matplotlib, as it requires configuring a graphics backend.  Moreover, you will need to add a bunch of `print()` calls to display the outputs you need.
Another option may be to use a docker environment, with everything already setup?
Hope this helps,
Aurélien

**Comment by Niceno** [comment]
Hi @ageron , thanks for reply.  Yes, I see your point.  In the long run I am obviously better of getting acquainted with Jupyter :+1: 

By the way, I am really loving the book.  The examples you give are amazing and thought provoking.  I am enjoying every page of it.  Excellent work!

Cheers,

Bojan

**Comment by magicmathmandarin** [comment]
by g
YvL C xt g ycl is
  GE

Rug o是 v 可以of
B
ronztyy
Doyg有谢ie rugby le Gucc
谷
