### ISSUE TITLE
mnist dataset

### ISSUE THREAD

**Issue by charles-bu** [ageron/handson-ml#301]
hi, 

I just noticed that the mnist dataset was removed from the sklearn and tensorflow basic datasets. therefore, it brings the trouble in doing the example of the chapter 3. 

I will be grateful if you could help to revised the code for our continuing using the mnist as the example. 

best regard,

Charles

**Comment by ctlevi** [comment]
In fact, it gives a 500 internal server error which makes it even more confusing.

**Comment by r-ichi** [comment]
just use:

   from sklearn.datasets import fetch_mldata
   mnist = fetch_mldata('MNIST original')
   mnist

works with sklearn version 0.19.1
check your version with:

   import sklearn
   sklearn.__version__

**Comment by ageron** [comment]
Scikit-Learn used to download MNIST from mldata.org, which was unfortunately pretty unstable, and was eventually shutdown. You can still use `fetch_mldata()` if you downloaded the dataset before mldata.org was shut down, as it will use the dataset stored in your cache. However, since Scikit-Learn 0.20, you should use `fetch_openml()` instead:

```python
from sklearn.datasets import fetch_openml
mnist = fetch_openml('mnist_784', version=1, cache=True)
```

For most cases, this should work fine. However, it does not return the exact same dataset as `fetch_mldata()` did. Indeed, the targets are now strings instead of unsigned 8-bit integers, and also it returns the unsorted MNIST dataset, whereas `fetch_mldata()` returned the dataset sorted by target (the training set and the test test were sorted separately). In general, this is fine, but if you want to get the exact same results as before, you need to sort the dataset using the following function:

```python
def sort_by_target(mnist):
    reorder_train = np.array(sorted([(target, i) for i, target in enumerate(mnist.target[:60000])]))[:, 1]
    reorder_test = np.array(sorted([(target, i) for i, target in enumerate(mnist.target[60000:])]))[:, 1]
    mnist.data[:60000] = mnist.data[reorder_train]
    mnist.target[:60000] = mnist.target[reorder_train]
    mnist.data[60000:] = mnist.data[reorder_test + 60000]
    mnist.target[60000:] = mnist.target[reorder_test + 60000]

try:
    from sklearn.datasets import fetch_openml
    mnist = fetch_openml('mnist_784', version=1, cache=True)
    mnist.target = mnist.target.astype(np.int8) # fetch_openml() returns targets as strings
    sort_by_target(mnist) # fetch_openml() returns an unsorted dataset
except ImportError:
    from sklearn.datasets import fetch_mldata
    mnist = fetch_mldata('MNIST original')
mnist["data"], mnist["target"]
```

I'm updating all the notebooks that use `fetch_mldata()` to use `fetch_openml()` instead.
Hope this helps.

**Comment by ageron** [comment]
Also note that TensorFlow's method to load MNIST was also deprecated. :(

```python
from tensorflow.examples.tutorials.mnist import input_data # DEPRECATED!
mnist = input_data.read_data_sets("/tmp/data/")
```

Fortunately, Keras also has a method to load MNIST, and since it is now part of TensorFlow (in tf.keras), you can use:

```python
from tensorflow.keras.datasets import mnist
(X_train, y_train), (X_test, y_test) = mnist.load_data()
```

The main differences are as follows:


|  | `fetch_mldata()`  | `fetch_openml()` | TensorFlow (deprecated) | Keras |
| ---- | ------------- | ------------- | ------------- | ------------- |
| Sorted by label | Yes | No | No | No |
| Image dtype | uint8 (0 to 255) | float64 (0.0 to 255.0) | float32 (0.0 to 1.0) | uint8 (0 to 255) |
| Image shape | [784] | [784] | [784] | [28, 28] |
| Label dtype | float (0.0 to 9.0) | string ('0' to '9') | uint8 (0 to 9) | uint8 (0 to 9) |
| Split | No split: 0..70000 | No split: 0..70000 | Validation 0..4999, Train 5000..59999, Test 60000..69999 | Train 0..59999, Test 60000..69999 |

**Comment by charles-bu** [comment]
you may try this one for the sklearn udpate

conda update scikit-learn

meanwhile, the mnist is still available so far. as the data is going to be not available very soon, I convert it as csv file via pandas to save it local for avoiding further trouble.

**Comment by ramana997** [comment]
fetch_openml()  gave the following error on my Windows 10 machine.
"jsondecodeerror: Expecting value: line 1 column 1 (char 0)".

Then I upgraded  scikitl-learn from 0.20.0 to 0.20.2. This solved the problem and  fetch_openml() worked fine.

**Comment by abhishekjain98** [comment]
@RedemptionC  try conda update anaconda
Then your whole anaconda will be updated with latest versions of libraries

**Comment by marco82ger** [comment]
Hi, 
I am having some trouble downloading MNIST dataset.
I am using the current code on github:
`    from sklearn.datasets import fetch_openml
    mnist = fetch_openml('mnist_784', version=1, cache=True)

    mnist.target = mnist.target.astype(np.int8) # fetch_openml() returns targets as strings
    sort_by_target(mnist) # fetch_openml() returns an unsorted dataset`
but i get:
`JSONDecodeError: Expecting ',' delimiter: line 3 column 121541 (char 121542)`
Can you help me?

**Comment by el-grudge** [comment]
Same issue here, as marco82ger

**Comment by el-grudge** [comment]
appears to be working now

**Comment by ageron** [comment]
If the problem happens in `fetch_openml()` then I see two possibilities:

* Perhaps the dataset was corrupted during download, and now it's in the cache so it never works. You can check if this is the reason by running `fetch_openml()` with `cache=False`. If it works, then it means your cache is corrupted, so you should clear Scikit-Learn's openml cache: just delete the directory: `$HOME/scikit_learn_data/openml`. After that, restart Python and try again.
* Or else it might be a data corruption on the server side. Perhaps it was fixed after a while, which would explain why it started working again for @el-grudge .
Hope this helps.

**Comment by aakashsharan** [comment]
for me, cache=True isn't working even after deleting the directory,
cache=False is working though.

**Comment by ageron** [comment]
Thanks for your feedback @aakashsharan , what error message do you get when using `cache=True`? Perhaps make sure you have the access rights to the `$HOME/scikit_learn_data` directory, and that you have enough space on disk?

**Comment by aakashsharan** [comment]
Sorry for the late response.
Yes issue was with the access rights. Thanks.

**Comment by gruckion** [comment]
> my sklearn.**version** is 0.19
> and after"conda update scikitlearn",it still can't update to 2.0
> is there any other ways i can get the mnist dataset?

Download the file manually?

**Comment by aakashsharan** [comment]
Try tf.keras.datasets.mnist.load_data() https://www.tensorflow.org/api_docs/python/tf/keras/datasets/mnist/load_data

**Comment by SalmanCode** [comment]
Hey.

I get this error when cache=False

"MemoryError: Unable to allocate array with shape (54950000,) and data type float64"

While when cache=True

![image](https://user-images.githubusercontent.com/19824744/68020935-dee5ca80-fcc1-11e9-9659-cd20c149a853.png)

**Comment by ageron** [comment]
Hi @SalmanCode ,

Thanks for your feedback. It looks like you're running out of RAM. You need to close as many applications as you can to free up some RAM. And close as many tabs as possible in your browser. If it still fails, then try rebooting your computer. If it still fails, then I'm afraid you either have some bad software using up all your RAM, or you need to install more RAM on your computer.

Hope this helps,
Aurélien

**Comment by SalmanCode** [comment]
It worked. Thanks a lot sir. 
P.S. Just wanted you to know that your feedback are of great help. Keep up the great work :)

**Comment by SalmanCode** [comment]
Hey @ageron . I wasn't sure I should post this question separately or make it part of this thread. Sorry new to this.

Anyways, your advice worked fine. Initially I had many unwanted tabs and memory usage. After closing them, dataset loading worked fine. However, in the later code, the memory issue keeps popping up whenever making large arrays. Even though now I have minimal tabs and my memory usage is around 50%. My system has 8GB RAM. Do you think is it a system's limitation issue or I am doing something wrong. 
![image](https://user-images.githubusercontent.com/19824744/68186040-ee685a80-ffc4-11e9-9a3a-e1f844b39113.png)

**Comment by ageron** [comment]
Hi @SalmanCode ,
In theory 8GB of RAM should be enough, so I'm guessing your system must have a lot of programs running in the background. Perhaps try looking at the task manager (to open it, press "Control-Shift-Esc" on Windows), switch to the "Processes" tab to see a list of everything running on your computer, including both visible programs and background processes, and sort by RAM usage. Make sure you close any program that uses a lot of RAM and that you don't need. In particular, if you have opened several Jupyter notebooks, make sure you only run one at a time and you close the ones that you are not using.
Also, you can try deleting large data structures that you don't need anymore. For example, once you don't need `X_train_folds` anymore, you can run `del X_train_folds`.
But the simplest solution may just be to purchase 8 more GB of RAM.
Hope this helps.

**Comment by AnasK95** [comment]
It first returned "Memory error" . 
on rerunning it returned
"urlopen error [Errno 2] No such file or directory"

**Comment by ageron** [comment]
Hi @AnasK95 ,
Happy new year! Which line is causing these problems? Is it the call to `fetch_openml()`?

**Comment by Richard-Cao226** [comment]
> Scikit-Learn used to download MNIST from mldata.org, which was unfortunately pretty unstable, and was eventually shutdown. You can still use `fetch_mldata()` if you downloaded the dataset before mldata.org was shut down, as it will use the dataset stored in your cache. However, since Scikit-Learn 0.20, you should use `fetch_openml()` instead:
> 
> ```python
> from sklearn.datasets import fetch_openml
> mnist = fetch_openml('mnist_784', version=1, cache=True)
> ```
> 
> For most cases, this should work fine. However, it does not return the exact same dataset as `fetch_mldata()` did. Indeed, the targets are now strings instead of unsigned 8-bit integers, and also it returns the unsorted MNIST dataset, whereas `fetch_mldata()` returned the dataset sorted by target (the training set and the test set were sorted separately). In general, this is fine, but if you want to get the exact same results as before, you need to sort the dataset using the following function:
> 
> ```python
> def sort_by_target(mnist):
>     reorder_train = np.array(sorted([(target, i) for i, target in enumerate(mnist.target[:60000])]))[:, 1]
>     reorder_test = np.array(sorted([(target, i) for i, target in enumerate(mnist.target[60000:])]))[:, 1]
>     mnist.data[:60000] = mnist.data[reorder_train]
>     mnist.target[:60000] = mnist.target[reorder_train]
>     mnist.data[60000:] = mnist.data[reorder_test + 60000]
>     mnist.target[60000:] = mnist.target[reorder_test + 60000]
> 
> try:
>     from sklearn.datasets import fetch_openml
>     mnist = fetch_openml('mnist_784', version=1, cache=True)
>     mnist.target = mnist.target.astype(np.int8) # fetch_openml() returns targets as strings
>     sort_by_target(mnist) # fetch_openml() returns an unsorted dataset
> except ImportError:
>     from sklearn.datasets import fetch_mldata
>     mnist = fetch_mldata('MNIST original')
> ```
> 
> I'm updating all the notebooks that use `fetch_mldata()` to use `fetch_openml()` instead.
> Hope this helps.
I used the same code as you, but
I got this error: urllib.error.HTTPError: HTTP Error 400: Bad Request
Any idea what's wrong?

**Comment by Richard-Cao226** [comment]
My code: dataset = datasets.fetch_openml('mnist 784', version=1, cache=True)
I got this error: urllib.error.HTTPError: HTTP Error 400: Bad Request

Any idea what's wrong?

**Comment by AnasK95** [comment]
Hi @ageron,
New year wishes to you as well!.. Sorry for the late reply.
Yes it was the fetch_openml() call that was causing the error. I later tried the code (even the original fetch_mldata('MNIST original') ) on Google collab and it ran pretty well.

**Comment by princessyinfen** [comment]
Hi @ageron,
I know this is not a new issue. However, I still having problem to access the MNIST data. The error is shown in the attached image below. Do you think you can help me? Thank you!
![image](https://user-images.githubusercontent.com/62480202/77233413-7f705480-6ba7-11ea-82ba-448c0780ef8d.png)

**Comment by harshmalviya7** [comment]
from sklearn.datasets import fetch_openml
mnist=fetch_openml("mnist_784",version=1,cache=True)
---------------------------------------------------------------------------
MemoryError                               Traceback (most recent call last)
<ipython-input-42-6d6b34d2ef1f> in <module>
----> 1 mnist=fetch_openml("mnist_784",version=1,cache=True)

C:\ProgramData\Anaconda3\lib\site-packages\sklearn\datasets\openml.py in fetch_openml(name, version, data_id, data_home, target_column, cache, return_X_y)
    641                           k in data_columns + target_column}
    642 
--> 643     X, y = _convert_arff_data(arff['data'], col_slice_x, col_slice_y, shape)
    644 
    645     is_classification = {col_name in nominal_attributes

C:\ProgramData\Anaconda3\lib\site-packages\sklearn\datasets\openml.py in _convert_arff_data(arff_data, col_slice_x, col_slice_y, shape)
    244             count = shape[0] * shape[1]
    245         data = np.fromiter(itertools.chain.from_iterable(arff_data),
--> 246                            dtype='float64', count=count)
    247         data = data.reshape(*shape)
    248         X = data[:, col_slice_x]

MemoryError: Unable to allocate 419. MiB for an array with shape (54950000,) and data type float64

**Comment by ageron** [comment]
@princessyinfen : the only reason I can see is if you have installed an old version of Scikit-Learn. Could you please make sure you have the latest version installed (e.g., run `pip install -U scikit-learn`).

@harshmalviya7 : it looks like your computer is running out of RAM. Perhaps try to close as many programs as you can, and close as many tabs in your browser as possible. This will recover a lot of RAM, and perhaps it will work then. If not, and if you're going to use your computer to run ML programs, I suggest you add more RAM to it. Or try using Colab (or any cloud VM) instead.

Hope this helps.

**Comment by crazyhyz** [comment]
> @princessyinfen : the only reason I can see is if you have installed an old version of Scikit-Learn. Could you please make sure you have the latest version installed (e.g., run `pip install -U scikit-learn`).
> 
> @harshmalviya7 : it looks like your computer is running out of RAM. Perhaps try to close as many programs as you can, and close as many tabs in your browser as possible. This will recover a lot of RAM, and perhaps it will work then. If not, and if you're going to use your computer to run ML programs, I suggest you add more RAM to it. Or try using Colab (or any cloud VM) instead.
> 
> Hope this helps.

I have the exact same issue as @harshmalviya7 , I only has python open. My RAM is 32GB, and my PyCharm usage is less than 1GB. I dont know why.

**Comment by theshanweerasinghe** [comment]
Hi!
I am having this issue with fetching the dataset. 

Here's the code I typed 

from sklearn.datasets import fetch_openml
mnist = fetch_openml('mnist_784', version=1)
mnist.keys()
dict_keys(['data','target','feature_names','DESCR','details','categories','url'])

Then the error comes as follows

NameError                                 Traceback (most recent call last)
<ipython-input-8-24c6cab41b21> in <module>
      2 mnist = fetch_openml('mnist_784', version=1, cache=True)
      3 mnist.keys()
----> 4 dict_keys(['data','target','feature_names','DESCR','details','categories','url'])

NameError: name 'dict_keys' is not defined

I tried adding the cache = True too but it gives the same error.

**Comment by jdaviestx** [comment]
FYI, when I tried the suggestion in comment #4

    reorder_train = np.array(sorted([(target, i) for i, target in enumerate(mnist.target[:60000])]))[:, 1]
        reorder_test = np.array(sorted([(target, i) for i, target in enumerate(mnist.target[60000:])]))[:, 1]
        mnist.data[:60000] = mnist.data[reorder_train]
        mnist.target[:60000] = mnist.target[reorder_train]
        mnist.data[60000:] = mnist.data[reorder_test + 60000]
        mnist.target[60000:] = mnist.target[reorder_test + 60000]

I got the error message:

    Traceback (most recent call last):
      File "<stdin>", line 1, in <module>
      File "/Users/jodavies/devl/test/ml/env/lib/python3.8/site-packages/pandas/core/frame.py", line 3030, in __getitem__
        indexer = self.loc._get_listlike_indexer(key, axis=1, raise_missing=True)[1]
      File "/Users/jodavies/devl/test/ml/env/lib/python3.8/site-packages/pandas/core/indexing.py", line 1266, in     _get_listlike_indexer
        self._validate_read_indexer(keyarr, indexer, axis, raise_missing=raise_missing)
      File "/Users/jodavies/devl/test/ml/env/lib/python3.8/site-packages/pandas/core/indexing.py", line 1308, in     _validate_read_indexer
        raise KeyError(f"None of [{key}] are in the [{axis_name}]")
    KeyError: "None of [Int64Index([    1,    21,    34,    37,    51,    56,    63,    68,    69,\n               75,\n            ...\n            59910, 59917, 59927, 59939, 59942, 59948, 59969, 59973, 59990,\n            59992],\n           dtype='int64', length=60000)] are in the [columns]"

My best guess is that the data was returned as a numpy array when the comment was written, but is returned as a dataframe now.  I changed it to:

    reorder_train = np.array(sorted([(target, i) for i, target in enumerate(mnist.target[:60000])]))[:, 1]
        reorder_test = np.array(sorted([(target, i) for i, target in enumerate(mnist.target[60000:])]))[:, 1]
        mnist.data.values[:60000] = mnist.data.values[reorder_train]
        mnist.target.values[:60000] = mnist.target.values[reorder_train]
        mnist.data.values[60000:] = mnist.data.values[reorder_test + 60000]
        mnist.target.values[60000:] = mnist.target.values[reorder_test + 60000]

and it worked for me.

**Comment by ageron** [comment]
Hi @jdaviestx ,
Since Scikit-Learn 0.24, `fetch_openml()` returns a Pandas DataFrame by default, instead of a NumPy array. This causes all sorts of issues in the notebook. Instead of working around each of these issues, I recommend adding `as_frame=False` as an argument to `fetch_openml()` to force it to return a NumPy array.
Hope this helps.

**Comment by Raoni-Silva** [comment]
Hi @ageron ... Yesterday `mnist = fetch_openml('mnist_784', version=1, cache=False, as_frame=False)` worked fine... but today i'm getting this error:


---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-19-45013a064c6e> in <module>()
----> 1 mnist = fetch_openml('mnist_784', version=1, cache=False, as_frame=False)
      2 mnist.target = mnist.target.astype(np.int8) # fetch_openml() returns targets as strings
      3 sort_by_target(mnist) # fetch_openml() returns an unsorted dataset

2 frames
/usr/local/lib/python3.7/dist-packages/sklearn/datasets/_openml.py in _get_json_content_from_openml_api(url, error_message, raise_if_error, data_home)
    166     # 412 error, not in except for nicer traceback
    167     if raise_if_error:
--> 168         raise ValueError(error_message)
    169     return None
    170 

ValueError: Dataset mnist_784 with version 1 not found.

**Comment by ageron** [comment]
@Raoni-Silva thanks for your feedback. If the problem is intermittent, then I believe it's just a server side problem (i.e., temporary problems at openml.org). I think you just need to retry. You can also pass `cache=True` to `fetch_openml()` to cache the dataset locally. This will ensure that after it works once, it will always work after that.
Hope this helps.

**Comment by Raoni-Silva** [comment]
@ageron ... Thanks a lot for the reply... Today it worked normally... I'm loving your book... Cheers from Brazil...

**Comment by cherifseye** [comment]
![Screen Shot 2021-12-07 at 8 47 56 AM](https://user-images.githubusercontent.com/74331175/145040755-083d4ed8-d099-48a6-838c-a6e820cb3390.png)
Hello I want to download the mnist dataset but I get this error, can you help me to fix this issue?
Thanks

**Comment by ageron** [comment]
Hi @cherifseye ,

Please see my answer to this question [here](https://github.com/ageron/handson-ml/issues/644).

**Comment by yashwantsahu221** [comment]
from sklearn.datasets import fetch_openml
import numpy as np

# Load MNIST dataset
mnist = fetch_openml('mnist_784', version=1, as_frame=False, parser='pandas')

# Get the data and target
X, y = mnist["data"], mnist["target"]

# Convert y to integers (if needed)
y = y.astype(np.uint8)

# Check shapes
print(f"X.shape: {X.shape}")
print(f"y.shape: {y.shape}")
