### ISSUE TITLE
"docker-compose up" is fail

### ISSUE THREAD

**Issue by tetsuyasu** [ageron/handson-ml#305]
This happens on both Mac and Ubuntu.
Do you have any idea to fix this?

$ docker-compose up
Starting handson-ml ... done
Attaching to handson-ml
handson-ml    | Traceback (most recent call last):
handson-ml    |   File "/opt/conda/lib/python3.6/site-packages/traitlets/traitlets.py", line 528, in get
handson-ml    |     value = obj._trait_values[self.name]
handson-ml    | KeyError: 'allow_remote_access'
handson-ml    | 
handson-ml    | During handling of the above exception, another exception occurred:
handson-ml    | 
handson-ml    | Traceback (most recent call last):
handson-ml    |   File "/opt/conda/lib/python3.6/site-packages/notebook/notebookapp.py", line 869, in _default_allow_remote
handson-ml    |     addr = ipaddress.ip_address(self.ip)
handson-ml    |   File "/opt/conda/lib/python3.6/ipaddress.py", line 54, in ip_address
handson-ml    |     address)
handson-ml    | ValueError: '' does not appear to be an IPv4 or IPv6 address
handson-ml    | 
handson-ml    | During handling of the above exception, another exception occurred:
handson-ml    | 
handson-ml    | Traceback (most recent call last):
handson-ml    |   File "/opt/conda/bin/jupyter-notebook", line 11, in <module>
handson-ml    |     sys.exit(main())
handson-ml    |   File "/opt/conda/lib/python3.6/site-packages/jupyter_core/application.py", line 266, in launch_instance
handson-ml    |     return super(JupyterApp, cls).launch_instance(argv=argv, **kwargs)
handson-ml    |   File "/opt/conda/lib/python3.6/site-packages/traitlets/config/application.py", line 657, in launch_instance
handson-ml    |     app.initialize(argv)
handson-ml    |   File "<decorator-gen-7>", line 2, in initialize
handson-ml    |   File "/opt/conda/lib/python3.6/site-packages/traitlets/config/application.py", line 87, in catch_config_error
handson-ml    |     return method(app, *args, **kwargs)
handson-ml    |   File "/opt/conda/lib/python3.6/site-packages/notebook/notebookapp.py", line 1629, in initialize
handson-ml    |     self.init_webapp()
handson-ml    |   File "/opt/conda/lib/python3.6/site-packages/notebook/notebookapp.py", line 1379, in init_webapp
handson-ml    |     self.jinja_environment_options,
handson-ml    |   File "/opt/conda/lib/python3.6/site-packages/notebook/notebookapp.py", line 158, in __init__
handson-ml    |     default_url, settings_overrides, jinja_env_options)
handson-ml    |   File "/opt/conda/lib/python3.6/site-packages/notebook/notebookapp.py", line 251, in init_settings
handson-ml    |     allow_remote_access=jupyter_app.allow_remote_access,
handson-ml    |   File "/opt/conda/lib/python3.6/site-packages/traitlets/traitlets.py", line 556, in __get__
handson-ml    |     return self.get(obj, cls)
handson-ml    |   File "/opt/conda/lib/python3.6/site-packages/traitlets/traitlets.py", line 535, in get
handson-ml    |     value = self._validate(obj, dynamic_default())
handson-ml    |   File "/opt/conda/lib/python3.6/site-packages/notebook/notebookapp.py", line 872, in _default_allow_remote
handson-ml    |     for info in socket.getaddrinfo(self.ip, self.port, 0, socket.SOCK_STREAM):
handson-ml    |   File "/opt/conda/lib/python3.6/socket.py", line 745, in getaddrinfo
handson-ml    |     for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
handson-ml    | socket.gaierror: [Errno -2] Name or service not known
handson-ml exited with code 1

**Comment by lvnilesh** [comment]
Pinning `continuumio/anaconda3:5.2.0` in `Dockerfile` like this is a workaround
```
FROM continuumio/anaconda3:5.2.0
```

**Comment by tetsuyasu** [comment]
Great!
It's fixed.
Thank you!

**Comment by originx** [comment]
why not merge it so you have usable master?
