### ISSUE TITLE
How do we calculate the confidence score of an instance mask generated from a bottom-up approach?

### ISSUE THREAD

**Issue by yanfengliu** [ageron/handson-ml#313]
I know that to evaluate an instance segmentation algorithm using mAP, for each object we want to produce a mask and a confidence score associated with it. However, all the resources I found so far assume that a bounding box is produced first and then the mask is refined within it. It is easy to produce a confidence score for an object outlined by the bounding box because the output will be one number.  But if someone is using a bottom-up approach, meaning that each pixel is individually classified and then grouped together later on, how would we calculate the confidence score for that instance? Do we simply calculate the mean of the confidence scores for each pixel in the mask? Thanks!

**Comment by ageron** [comment]
You eventually need a score for the whole instance. With a bottom-up approach, I think computing the mean of the pixel confidence scores sounds like a reasonable approach.
