### ISSUE TITLE
Animation for the DQN in Chapter 16

### ISSUE THREAD

**Issue by StrangeTcy** [ageron/handson-ml#32]
This is not an issue as such but a request. In chapter 16, we spend a lot of time getting acquainted with reinforcement learning and finally train a decent DQN, but we don't really see it play Pacman.
I think it'd be good to reuse the code already present in the notebook and create a short animation of our DQN playing.
I tried to do it myself, but ran into difficulties while calling `action.eval()`.

**Comment by ageron** [comment]
Hi @StrangeTcy ,

That's a great suggestion! :+1:   I am adding this to my To-Do list (however, adding the solutions to the exercises of all chapters is higher priority and quite time consuming, so I can't promise I'll do this very soon).

Thanks!
Aurélien

**Comment by btchncamaro** [comment]
I gave it a try.  The animation is there, but my code always outputs the same decision (7 in my case).  I am still beginning, so of anybody has  some suggestions, let me know.

```
def display_game_play(model_path, n_max_steps = 2000):
    env = gym.make('MsPacman-v0')
    obs = env.reset()
    with tf.Session() as sess:
        saver.restore(sess, model_path)
        for step in range(n_max_steps):
            #evaluate what to do
            state = preprocess_observation(obs)
            q_values = critic_q_values.eval(feed_dict={X_state: [state]})  #maybe actor_q_values?

            action_val = np.argmax(q_values)

            print("\rstep: {}, action_val: {}".format(step, action_val), end="")
            obs, reward, done, info = env.step(action_val)
            env.render()

            if done:
                print("DONE - FAILED")
                break
    env.close()
    return

save_path = "./data/ch16/my_dqn.ckpt"
display_game_play(save_path)
```

**Comment by ageron** [comment]
I added test code after training in chapter 16, so you can now view Ms Pacman learning to play. Thanks for the great suggestion!
