### ISSUE TITLE
chapter 14 in 97

### ISSUE THREAD

**Issue by thephet** [ageron/handson-ml#320]
It should be " ".join([vocabulary[word_index][0]

it needs the [0] otherwise it complains about it being a tuple

**Comment by ageron** [comment]
Hi @thephet , thanks for your feedback.  This is odd, I tried running the code again, but I could not reproduce the error.  Could you please specify which versions of OS, python, NumPy and Scikit-Learn you are using? Could you please double-check that you have the latest version of the notebook as well, without any modifications?
Thanks!

**Comment by ageron** [comment]
Closing stale issue. Please reopen if the problem persists.
