### ISSUE TITLE
一、机器学习概览

### ISSUE THREAD

**Issue by Conta216** [ageron/handson-ml#322]
表1-1中第四行，第一列；“发过”应为“法国”

**Comment by ageron** [comment]
I'm sorry, I don't speak Chinese. Google translate tells me that your question is:

> The fourth row in Table 1-1, the first column; "facilitated" should be "France"

I suppose this is a problem in the Chinese translation of my book. Thanks for bringing it to my attention, I will forward this to O'Reilly so they can correct this.

Google translation of my answer:
我想这是我书中译本中的一个问题。感谢您引起我的注意，我将把它转发给O'Reilly，以便他们能解决这个问题。
