### ISSUE TITLE
Compute the usage of  RAM by the network when making single prediction for a single instance ?

### ISSUE THREAD

**Issue by s1782662** [ageron/handson-ml#324]
Below is the question picked from chapter 13

Consider a CNN composed of three convolutional layers, each with 3x3 kernels, a stride of 2 and SAME with padding. The lowest layers outputs 100 
features maps, the middle one outputs 200, and the top one outputs 400. The input images are RGB images of 200 x 300 pixels. 

1. What is the total number of parameters in the CNN ?
2. If we are using 32-bit floats, at least how much RAM will this network require when making a prediction for a single instance ?.
3. What about when training on a mini-batch of 50 images ?.

I) 
----------------------------------------------------------------------------------------------------------------
1.  The first convolutional layer has  
     
             Kernels = 3 x 3
             Inputs Channels = 3
             No of filters = 1 
     So each feature map has (3 x 3 x 3) x 1 = 27 weights + 1 bias = 28 weights
     So, for 100 feature maps, we have 28 * 100 = 2800 parameters

2. The second convolutional layer has 

           Input = 100  (i.e feature maps from previous layer)
           kernel = 3 x 3
           total weights = 3 * 3 * 100 = 900 + 1 (bias) = 901
          So, 1 feature map has 901 weights, then 200 feature maps has 901 * 200 = 180200 parameters

3. Similarly for third Convolutional layer has 720,400 parameters 
   
The total number of parameters are 720,400 + 180200 + 2800 = 903,400  parameters

II) 
---------------------------------------------------------------------------------------------------------
In the second question, there were two computations

         one computation from the previous question (4 * 903,400 = 3.4 MB) and
         other computation was 6 + 9 = 15 million bytes (about 14.3 MB) 

**Can you explain bit more clearly how did you compute the second computation (i.e 14.3 MB) ?.**

**Comment by ageron** [comment]
Hi @s1782662 ,
IIRC, there was an error in the solution of this exercise in the first releases of my book. The latest version is this:

> [...] First let's compute the feature map size for each layer. Since we are using a stride of 2 and SAME padding, the horizontal and vertical size of the feature maps are divided by 2 at each layer (rounding up if necessary), so as the input channels are 200 × 300 pixels, the first layer's feature maps are 100 × 150, the second layer's feature maps are 50 × 75, and the third layer's feature maps are 25 × 38. Since 32 bits is 4 bytes and the first convolutional layer has 100 feature maps, this first layer takes up 4 x 100 × 150 × 100 = 6 million bytes (about 5.7 MB, considering that 1 MB = 1,024 KB and 1 KB = 1,024 bytes). The second layer takes up 4 × 50 × 75 × 200 = 3 million bytes (about 2.9 MB). Finally, the third layer takes up 4 × 25 × 38 × 400 = 1,520,000 bytes (about 1.4 MB). However, once a layer has been computed, the memory occupied by the previous layer can be released, so if everything is well optimized, only 6 + 3 = 9 million bytes (about 8.6 MB) of RAM will be required (when the second layer has just been computed, but the memory occupied by the first layer is not released yet). But wait, you also need to add the memory occupied by the CNN's parameters. We computed earlier that it has 903,400 parameters, each using up 4 bytes, so this adds 3,613,600 bytes (about 3.4 MB). The total RAM required is (at least) 12,613,600 bytes (about 12.0 MB).

Hope this helps.

**Comment by Zackhardtoname** [comment]
Why not close the issue? I can confirm the answer is correctly adjusted. @ageron

**Comment by hilasha2** [comment]
Is it possible to do a 'same' padding with inputs of sizes 200*300 though? 
I'll explain myself and use 10 as the input's width or height dimension as it is equivalent to 200 and 300.
Stride s = 2.
kernal width/height k = 3
(I put a dollar to represent a kernel going over the input. It simply has similar dimensions to a numeric character)
| 1 | 2 | 3 | 4 | 5 | 6 | 7 | 8 | 9 | 10 |
| $ | $ | $ |    |    |    |    |    |    |     |
          | $ | $ | $ |    |    |    |    |     |
                    | $ | $ | $ |    |    |     |
                              | $ | $ | $ |     |
                                        | $ | $  | 0 |
