### ISSUE TITLE
  End-to-end Machine Learning project: Dataframe shape changes after transformer pipeline.

### ISSUE THREAD

**Issue by Neha55** [ageron/handson-ml#325]
Hi, 

I am getting different shapes for `some_data_prepared` and `housing_prepared`. I think it is due to the *OneHotEncoder* in the cat_pipeline. In `some_data` we get only few categories and hence it tends to add only those many columns. Which is giving me an error in prediction, because the model is fitted on different shape. 
Could you please suggest me on this?

Thanks.

**Comment by pjiang01** [comment]
Ran into exactly the same issue and look forward to comments from the Author/Editor. Thanks.

**Comment by ageron** [comment]
Sorry for the delay, I have been traveling a lot lately. I'll run tests and let you know if I can reproduce the issue using Scikit-Learn 0.20 instead of 0.19.

**Comment by ageron** [comment]
I updated the code to use the new `OneHotEncoder` and `ColumnTransformer` classes.  I think it fixes this issue.  Please reopen if you still experience the problem.
Thanks!
