### ISSUE TITLE
Ch-1 Duplicate entries in oecd_bli_2015.csv

### ISSUE THREAD

**Issue by onlinejudge95** [ageron/handson-ml#327]
While executing 
`oecd_df = oecd.pivot(index='Country', columns='Indicator', values='Value')` 
in `prepare_country_stats` an error is thrown `ValueError: Index contains duplicate entries, cannot reshape`. 
Upon examining the CSV file, the coulmn `Country` + `Indicator` does have duplicates so the indexing would error out.
I downloaded the file from the following url
[OECD URL](https://raw.githubusercontent.com/ageron/handson-ml/master/datasets/lifesat/oecd_bli_2015.csv)

**Comment by ageron** [comment]
Hi @onlinejudge95 ,
I tried to reproduce this problem, but everything worked fine on my end. Can you please make sure you are using the latest version of the notebook without any modifications, and that you have the latest versions of Scikit-Learn, Pandas, NumPy, etc.?

**Comment by ageron** [comment]
Closing stale issue. Please reopen if the problem persists.
