### ISSUE TITLE
Deprecation warning of Imputer Class in Chapter 2 early release of new book

### ISSUE THREAD

**Issue by natiqvahabov** [ageron/handson-ml#330]
Hi,  I'm reading your early release book in safaribooksonline, and in Chapter 2 you use Imputer class  from sklearn.preprocessing library, but it raised DeprecationWarning, and Imputer class will be removed after sklearn version 0.22. SimpleImputer from sklearn.impute library will substitute current Imputer. For preventing future issues it should be perfect if you replace
`from sklearn.preprocessing import Imputer`
`imputer = Imputer(strategy="median")` 

with
`from sklearn.impute import SimpleImputer`
`imputer = SimpleImputer(strategy="median")`

Thanks for writing such a wonderful book, good lucks in your future works.

**Comment by ageron** [comment]
Thanks @natiqvahabov and @onlinejudge95 for your feedback, I really appreciate it. I will update the book and notebooks to use `SimpleImputer` instead of `Imputer`.

**Comment by ageron** [comment]
Done! Thanks for your feedback!
