### ISSUE TITLE
update README.md

### ISSUE THREAD

**Issue by mchoimis** [ageron/handson-ml#331]
Hi, 
When activating a newly created environment on Anaconda,  `$ source activate <env_name>` doesn't seem to work (on Windows at least). Instead, Anaconda prompt suggests using `$ conda activate <env_name>`. 

Here's what I found on StackOverflow: https://stackoverflow.com/questions/49600611/python-anaconda-should-i-use-conda-activate-or-source-activate-in-linux. Maybe need to update Readme.md? 

Thanks a lot for the great work!

**Comment by ageron** [comment]
Thanks for your feedback. Indeed, `conda activate` seems to be the recommended way to go since Anaconda 4.4.
