### ISSUE TITLE
Chapter 8 Iris feature plots

### ISSUE THREAD

**Issue by r-ichi** [ageron/handson-ml#333]
I guess the labels of the plot are wrong, since the features being used are X[0] and X[1], that correspond to Sepal length and width respectively, not Petal length and width... so then:

```python
plt.figure(figsize=(9, 3.5))

plt.subplot(121)`
plt.plot(X[y==0, 0], X[y==0, 1], "yo", label="Iris-Setosa")
plt.plot(X[y==1, 0], X[y==1, 1], "bs", label="Iris-Versicolor")
plt.plot(X[y==2, 0], X[y==2, 1], "g^", label="Iris-Virginica")
plt.xlabel("Petal length", fontsize=14)
plt.ylabel("Petal width", fontsize=14)
plt.legend(fontsize=12)
```

The `xlabel` and `ylabel` should be:

```python
plt.xlabel("Sepal length", fontsize=14)
plt.ylabel("Sepal width", fontsize=14)
```

Or am I missing something?

**Comment by ageron** [comment]
Hi @r-ichi ,
Good catch, thanks, it should be Sepal instead of Petal, I will fix this asap.

**Comment by r-ichi** [comment]
:) !

**Comment by ageron** [comment]
I ended up fixing the code to use the petal length & width for consistency with the other chapters.
Thanks again for your feedback!
