### ISSUE TITLE
Chapter 2, End-to-End Machine Learning Project 

### ISSUE THREAD

**Issue by ZavierLyu** [ageron/handson-ml#339]
I couldn't fetch the data for the project, and the author's source code even also failed. There could be some problems with the database or the source. I am a freshman. Can anyone help me to handle this?
![image](https://user-images.githubusercontent.com/35328826/50539860-7706b500-0bc2-11e9-9e22-708633a9d24e.png)

**Comment by ageron** [comment]
Hi @ZavierLyu ,

It looks like your Python installation is not quite finished, since it cannot open an SSL connection (to download the data using HTTPS).

Did you follow the installation instructions on the project's home page? In particular:


> Any Python 3 version should be fine, preferably 3.5 or 3.6 (TensorFlow support for Python 3.7 is coming soon). If you don't have Python 3, I recommend installing it (Python ≥2.6 should work, but it is deprecated so Python 3 is preferable). To do so, you have several options: on Windows or MacOSX, you can just download it from python.org. On MacOSX, you can alternatively use MacPorts or Homebrew. If you are using Python 3.6 on MacOSX, you need to run the following command to install the certifi package of certificates because Python 3.6 on MacOSX has no certificates to validate SSL connections (see this StackOverflow question):
> 
> $ /Applications/Python\ 3.6/Install\ Certificates.command
> 

In short, I think you just need to open a terminal and run the command `/Applications/Python\ 3.6/Install\ Certificates.command`

Then restart Jupyter and try again.

Hope this helps,
Aurélien

**Comment by ZavierLyu** [comment]
@ageron Thanks for such detailed explanation, sorry to bother you with my little issue. My problem's been solved. Really appreciate what you did for the book and these teachings.

**Comment by federicodifresco** [comment]
@ageron Thanks! It was very useful.

**Comment by BigDataPlayers** [comment]
Installed python 3.7 through brew. Also tried $pip3 install --upgrade certifi. 

Still don't see Python directory under Application. I am on OSX 10.15.1. /Library has Python directory but no install or certificates. Please advise. Thanks.

**Comment by tamersalama** [comment]
@BigDataPlayers what issues do you have? Can you run python from the terminal?

**Comment by BigDataPlayers** [comment]
Thanks for checking in. I’ve switched back to Python 3.7.5. It’s all working now. The SSL Certificate issue has been resolved.

**Comment by FifteenTen** [comment]
![VirtualBox_Ubuntu-FifteenTen_10_03_2022_09_14_08](https://user-images.githubusercontent.com/101308109/157655880-2518379d-f92e-43d3-b661-588876278702.png)

Can you please help on this ?

**Comment by ageron** [comment]
Hi @FifteenTen ,

You seem to be running on Ubuntu, right? Are you running a MacOSX virtual machine using VirtualBox?

I'm not sure what you're trying to do with the `pip install` command, normally you shouldn't have to do that, only run the `Install\ Certificates.command` script (I think you may be missing a space after the backslash).

In any case, what problem did you initially run into? I'd be happy to help, but you must give me much more details.

**Comment by FifteenTen** [comment]
IHello @ageron ,
You seem to be running on Ubuntu, right? Are you running a MacOSX virtual machine using VirtualBox? - Yes.
Is the Install should directory?
Python is installed at /usr/bin/python3.8
So issue is if I am trying to install any package then it will give above error.
I gave an example.

**Comment by ageron** [comment]
Thanks for the details. This issue doesn't seem related to this project, it looks like a Python installation issue. But I can try to help.

Did you try adding the space? `Install\ Certificates.command` instead of `Install\Certificates.command`? Your screenshot shows the latter, which is wrong.

**Comment by FifteenTen** [comment]
this is the latest one
fteenten@fifteenten-VirtualBox:/$ Install\ Certificates.command
Install Certificates.command: command not found
fifteenten@fifteenten-VirtualBox:/$

**Comment by ageron** [comment]
Hi @FifteenTen ,
The `Install\ Certificates.command` script is normally located in the `/Applications/Python\ 3.8/` directory, so you need to enter the full path:

```
/Applications/Python\ 3.8/Install\ Certificates.command
```

If you are new to the command line, then I kindly suggest you watch a intro video to command lines, such as [this one](https://www.youtube.com/watch?v=ogWoUU2DXBU).

Hang in there, it will work eventually! 👍

**Comment by FifteenTen** [comment]
You can have look here is the Application directory available in my mac
system
[image: Screenshot 2022-03-30 at 4.08.17 PM.png]

So it seems that there is no such python file.
Could you please help me on it.


*Best Regards *



*Ramesh Chand Rebari+91 85618 21525LinkedIn* :
www.linkedin.com/in/ramesh-chand-rebari-3959b9131

**Comment by FifteenTen** [comment]
Hi
Here is the screenshot from the virtual machine
[image: Screenshot from 2022-03-30 16-19-49.png]
Here you can the applications folder.
Thanks
*Best Regards *



*Ramesh Chand Rebari+91 85618 21525LinkedIn* :
www.linkedin.com/in/ramesh-chand-rebari-3959b9131

**Comment by FifteenTen** [comment]
Now it is solved, Thanks Ageron.

*Best Regards *



*Ramesh Chand Rebari+91 85618 21525LinkedIn* :
www.linkedin.com/in/ramesh-chand-rebari-3959b9131
