### ISSUE TITLE
CH 2: fit_transform() or transform() in Pipeline?

### ISSUE THREAD

**Issue by ZavierLyu** [ageron/handson-ml#341]
Hi~

I really like the book and also the author's enthusiasm to help readers. And there are some points confusing me.
In the introduction towards Pipeline, you used `fit_transform(housing)` to make the `housing_prepared`, however, in the final page you used `transform(X_test)` instead. I am wondering the difference between `transform()` and `fit_transform` in Pipeline, how the `transform` works without `fit`?

Former:
``` python
num_attribs = list(housing_num)
cat_attribs = ["ocean_proximity"]

full_pipeline = ColumnTransformer([
        ("num", num_pipeline, num_attribs),
        ("cat", OneHotEncoder(), cat_attribs),
    ])

housing_prepared = full_pipeline.fit_transform(housing) # Here was fit_transform().
```
Latter:
``` python
final_model = grid_search.best_estimator_

X_test = strat_test_set.drop("median_house_value", axis=1)
y_test = strat_test_set["median_house_value"].copy()

X_test_prepared = full_pipeline.transform(X_test) # Here was transform().
final_predictions = final_model.predict(X_test_prepared)

final_mse = mean_squared_error(y_test, final_predictions)
final_rmse = np.sqrt(final_mse)
```
And the result is quite different, when I used `transform` for the test, the RMSE was **4799**; while I used `fit_transform`, the RMSE was **6359**.

**Comment by ZavierLyu** [comment]
@ageron I got your point. Very lucid explanation and appropriate example. Thanks so much.

**Comment by abhishekjain98** [comment]
Hello @ZavierLyu 
please tell me how your RMSE is 4799?
mine comes out to be 48310.

**Comment by ZavierLyu** [comment]
@abhishekjain98 
I think that was generated randomly in some extent. I changed the random_state=42 to my own lucky number. So, I think it doesn't matter.
