### ISSUE TITLE
Chapter 2: use of Ordinal Encoder for ordinal attributes

### ISSUE THREAD

**Issue by GMalaguti** [ageron/handson-ml#348]
@ageron extremely useful book to get into machine learning problems!

After having implemented Chapter 2 following your notebook, I wanted to apply what I learned on a different dataset (Kaggle's House Prices competition).

I want to apply the Ordinal Encoder to a set of attributes, but now giving the mappings between categories and numerical values (e.g. 'good', 'average', 'bad' mapped into 2, 1, 0), but I don't understand how to do that from this page:
https://scikit-learn.org/stable/modules/generated/sklearn.preprocessing.OrdinalEncoder.html
Even looking at the User Guide did not help...

I have also found this other page:
http://contrib.scikit-learn.org/categorical-encoding/ordinal.html
where it becomes clear to me how to pass the mapping to the encoder, but I think this is not the same encoder as the previous link, since it is in a different class. I am a bit confused...

Should I use OneHOt Encoder even if I can interpret the categories as ordered?

**Comment by GMalaguti** [comment]
Hi @ageron ,
thank you for the hints and the fast reply!

I tried your example:
`>>> encoder = OrdinalEncoder(categories=[["bad", "average", "good"]])
>>> encoder.fit_transform([["good"], ["bad"], ["bad"], ["average"]])
array([[2.],
       [0.],
       [0.],
       [1.]])`

**Comment by GMalaguti** [comment]
Hi @ageron ,
thank you for the hints and the fast reply!

I tried your example without a NumPy array, but also this does not work for me, maybe for my Scikit version (0.19):
```
>>> encoder = OrdinalEncoder(categories=[["bad", "average", "good"]])
>>> encoder.fit_transform([["good"], ["bad"], ["bad"], ["average"]])
...
ValueError: Unsorted categories are not yet supported
```

I also found out that there is the `replace` function. Would that be an alternative option? I can pass the mapping and the attributes involved. The most tricky part should be to create a transformer to include that into the pipeline.

**Comment by ageron** [comment]
Hi @GMalaguti ,
No problem! :)
I highly recommend you upgrade to Scikit-Learn 0.20.  It introduces the `ColumnTransformer` which greatly simplifies pipelines when different features need different proprocessing operations, and it improves encoding categories (and of course, it adds much more).
Cheers,
Aurélien

**Comment by GMalaguti** [comment]
Hi @ageron ,
with the new version of Scikit-Learn it works properly!
I am still struggling to include the OrdinalEncoder in conjunction with ColumnTrnasformer into my pipeline... but this is another problem.
Thanks for the hints!

**Comment by siddley1001** [comment]
I was wondering if it was possible to provide a list of dictionaries to establish orders for specific columns. I was thinking this would be useful in a column transformer pipeline
