### ISSUE TITLE
The error term added to the dataset in Chapter 4 is not Guassian

### ISSUE THREAD

**Issue by LiquPy** [ageron/handson-ml#351]
I must say it's a wonderful book. However, in Chapter 4, under "The Normal Equation" section, the error term generated using np.random.rand() is not distributed Gaussian but uniform(0, 1).
In order to generate a Gaussian error term you may use np.random.normal(loc=0, scale=1., size(100))

**Comment by LiquPy** [comment]
Also, the parameters obtained from the actual function are 4.215, and 2.770 but they are referred to as 3.865, and 3.139 in the text right below the Python output (Refer to under Fig. 4-1).

**Comment by ageron** [comment]
Thanks a lot for your kind words and your useful feedback, I'll look into this today.

**Comment by LiquPy** [comment]
Great! I noticed the data generated for Polynomial Regression has the same issue. Although, it is not mentioned there that the error term is distributed Gaussian.

**Comment by LiquPy** [comment]
Thanks for replying. I double checked again, it was my bad, you have used "rand**n**()" not "rand()" which is correct. My second comment is still valid. Check that one please.
