### ISSUE TITLE
Chapter 2: ModuleNotFoundError: No module named 'future_encoders'

### ISSUE THREAD

**Issue by Hussain73** [ageron/handson-ml#352]
Thanks for the great book, currently I'm reading the second chapter and I am testing your code as I am going through the chapter.  I came across your bellow code:

try:
    from sklearn.preprocessing import future_encoders
except ImportError:
    from future_encoders import future_encoders # Scikit-Learn < 0.20

And it did gave me an error as follow:

ImportError                               Traceback (most recent call last)
<ipython-input-66-cd369f8d7f83> in <module>()
      1 try:
----> 2     from sklearn.preprocessing import future_encoders
      3 except ImportError:

ImportError: cannot import name 'future_encoders'

During handling of the above exception, another exception occurred:

ImportError                               Traceback (most recent call last)
<ipython-input-66-cd369f8d7f83> in <module>()
      1 try:
----> 2     from sklearn.preprocessing import future_encoders
      3 except ImportError:

ImportError: cannot import name 'future_encoders'

I am using Python 3.6.8 and SK learn V.  0.20.2.  So what could be the problem?

**Comment by ageron** [comment]
Hi @Hussain73 ,

Thanks for your question.  I think you may have modified the code by mistake, because your code is different from the one in the original notebook.  The original notebook contains code like this (cell 49):

```python
try:
    from sklearn.impute import SimpleImputer # Scikit-Learn 0.20+
except ImportError:
    from sklearn.preprocessing import Imputer as SimpleImputer
```

or like this (cell 60):

```python
try:
    from sklearn.preprocessing import OrdinalEncoder
except ImportError:
    from future_encoders import OrdinalEncoder # Scikit-Learn < 0.20
```

or like that (cell 63):

```python
try:
    from sklearn.preprocessing import OrdinalEncoder # just to raise an ImportError if Scikit-Learn < 0.20
    from sklearn.preprocessing import OneHotEncoder
except ImportError:
    from future_encoders import OneHotEncoder # Scikit-Learn < 0.20
```

or like this (cell 73):

```python
try:
    from sklearn.compose import ColumnTransformer
except ImportError:
    from future_encoders import ColumnTransformer # Scikit-Learn < 0.20
```

Hope this helps!

**Comment by Hussain73** [comment]
@ageron Thanks for your great feedback.  Its true I had copied cell 60 by mistake.  Its working now.  Thanks .

**Comment by salmeghlef** [comment]
I am using python 3.7 and sklearn version 0.19. It shows the same error as seen in the attached screen shot.
![‏لقطة الشاشة ١٤٤١-٠٣-١٧ في ٩ ١٥ ٣٧ م](https://user-images.githubusercontent.com/45724031/68884737-d4e1b400-0724-11ea-9756-9534eebd1e71.png)

**Comment by ageron** [comment]
Hi @salmeghlef ,
The simplest solution is probably to update Scikit-Learn to the latest version (or at least 0.20).
Alternatively, you can download the `future_encoders.py` file from this project (at the root of the project), and make sure you place it in the same directory as the notebook.
Hope this helps.

**Comment by salmeghlef** [comment]
Thanks a lot for your quick response. That is right, when I downloaded the last version of sklearn, it works just fine. However, you wrote < .20 as a comment on the code. Indeed, this fool me that the version should be "<" which means less. Any way, thanks a lot. I am just wondering to know where to see the project on my local machine after I did clone it. My machine is mac os and I installed anaconda3. I burn jupyter notebook from the terminal but not sure where it exactly installed since I just post some command on terminal and the destination for downloading is a vague to me.

**Comment by ageron** [comment]
Hi @salmeghlef ,
I'm glad it worked! :)
When you open up your terminal, you are typically located in your home directory, which on MacOSX is /Users/your_login (if you are unsure about your login name, try opening a Terminal and typing `whoami`, this will display your login name). If you ran the `git clone` command right there, then it will be located in `/Users/your_login/handson-ml`.  If you can't find this directory in the Finder, then you can try opening the Finder menu: Go > Go to Folder... and then type the path /Users/your_login/handson-ml. You can also open the Finder preferences, and ensure that your login name is checked in the "Sidebar" tab. This will make it easy to open your home folder in just one click from the side bar in the Finder.
 
Some useful commands in the Terminal:

* `whoami` : tells you what your login is.
* `pwd` : tells you what the current directory is.
* `ls` :  lists the content of the current directory
* `ls -l` : lists files with more details, in the form of a list
* `ls -la` : same but also lists hidden files (which are files whose name starts with a dot).
* `cd` : change the current directory to your home directory (/Users/your_login)
* `cd /Users/your_login/handson-ml` : changes the current directory to this directory.
* `cd ..` : go "up" one directory (e.g., go from /a/b/c/d to /a/b/c).

Hope this helps!

**Comment by salmeghlef** [comment]
Thank you so much. You made it easy to me.
