### ISSUE TITLE
Chapter 10 Using Plain Tensorflow

### ISSUE THREAD

**Issue by maryamashoori** [ageron/handson-ml#353]
Hey Aurelien,
In `neuron_layer` function when you define `stddev`, `n_neurons` is dropped from the equation.
Did you mean to define stddev as `2/np.sqrt(n_inputs+n_neurons)`?
I wonder if it was on purpose (converge faster?) or was just missed?

**Comment by ageron** [comment]
Hi @maryamashoori , great question, thanks!
He initialization is indeed `2 / np.sqrt(n_inputs+n_neurons)`.
However, it's frequent to have many consecutive dense layers with the same number of neurons (e.g., several dense layers with 100 neurons each), in which case these layers have `n_inputs == n_neurons`, except for the very first one. When `n_inputs == n_neurons`, the equation simplifies to `2 / np.sqrt(2 * n_inputs)`, or equivalently `np.sqrt(2 / n_inputs)`. I believe this is what I had in mind, but I wrote `2 / np.sqrt(n_inputs)` instead, by mistake.
I'll use `2 / np.sqrt(n_inputs+n_neurons)`, it will be clearer. :)
Thanks again!
