### ISSUE TITLE
can't see the graph within jupyter

### ISSUE THREAD

**Issue by kiruthihan10** [ageron/handson-ml#358]
I use jupyter on anaconda interface. Even when I use 
`from tensorflow_graph_in_jupyter import show_graph`
`show_graph(tf.get_default_graph())`
It is not showing graph, instead it is showing a white blank box
What should I do??
![graph_error](https://user-images.githubusercontent.com/47429159/52433003-f8daee00-2b31-11e9-8834-6a70c1df9345.png)

**Comment by ageron** [comment]
Hi @kiruthihan10 ,
Yes, this `show_graph()` function is really a hack, it does not work on all browsers, and it has been broken a few times already, plus it relies on a 3rd party TensorBoard server which may be down, so I decided to drop this approach altogether in the 2nd edition of my book, and follow the "correct" path: using your own TensorBoard server. Check out the TensorBoard section in [this notebook](https://github.com/ageron/handson-ml2/blob/master/10_neural_nets_with_keras.ipynb), around cells 84 to 97, in particular the `tb()` function and the text just before that.
This way you can easily visualize any graph, using your own TensorBoard server.
Hope this helps,
Aurélien
