### ISSUE TITLE
Chapter 3: ValueError: The number of classes has to be greater than one; got 1 class

### ISSUE THREAD

**Issue by pin0S** [ageron/handson-ml#360]
Hello, 

When I run the following: 

`from sklearn.linear_model import SGDClassifier`
`sgd_clf = SGDClassifier(tol=None, max_iter=5, random_state=42)`
`sgd_clf.fit(X_train, y_train_5)`

I get the error `ValueError: The number of classes has to be greater than one; got 1 class`

I'm sure both classes y_train_5 and y_test_5 are set up correctly as I have run in the course notebook and my own. 

Can anyone point me in the right direction for a solution?

**Comment by ageron** [comment]
Hi @pin0S ,

The error message says that there's just one class in `y_train_5`.  Could you please print the output of:

```python
np.unique(y_train_5)
```

There should be more than one value in the resulting array.
If not, then perhaps what happened is that you used `fetch_openml()` to download MNIST, and it returns labels as strings so when you defined `y_train_5 = (y_train == 5)`, it results an array full of `False`. A solution is to cast `y_train` to int8: `y_train = y_train.astype(np.int8)` (which is what I do in the notebook, just after loading the data).

Hope this helps,
Aurélien

**Comment by pin0S** [comment]
Hi @ageron 

Thanks for coming back so quick and apologies I have only got around to it now. 

You were correct I had missed the to int8. I was looking at the old notebook and not the newer one. 

Cheers, 

Pete

**Comment by eapotapov** [comment]
Hi @ageron 

I did the same mistake, thought that "We prefer numbers" was something optional, skipped and then forgot that I did it. Maybe different wording will help people like us in the next edition.

P.S. The book is amazing btw, thanks!

![image](https://user-images.githubusercontent.com/46503464/61836910-4a084100-ae37-11e9-97ea-a90eedc2e4cd.png)

**Comment by ageron** [comment]
Hi @eapotapov ,
Thanks for your feedback and your kind words. Indeed "We prefer numbers" was not a great way to phrase this, I'll fix it.
Cheers!

**Comment by FritzPeleke** [comment]
I also started working with machine learning of recent(real programming in general) and I missed the conversion to integer part:).
i am working with the book, I must say it is wonderful, I don't regret a cent of my money. Thanks a lot, @ageron. God bless

**Comment by ageron** [comment]
Thanks for your kind words Fritz! :)

**Comment by umeshhello12** [comment]
![ddd](https://user-images.githubusercontent.com/43229966/62699512-4bbc3200-b9fd-11e9-9786-65568e04d135.JPG)
The number of classes has to be greater than one; got 1 class
Please help me sir

**Comment by corvettettt** [comment]
@umeshhello12 @ageron 
Hi guys, The targets of  'MNIST' dataset downloaded are string digit. So you just need to change to 
y_train_5 = (y_train == '5')
y_test_5 = (y_test == '5')

**Comment by renil0210** [comment]
> Hi @pin0S ,
> 
> The error message says that there's just one class in `y_train_5`. Could you please print the output of:
> 
> ```python
> np.unique(y_train_5)
> ```
> 
> There should be more than one value in the resulting array.
> If not, then perhaps what happened is that you used `fetch_openml()` to download MNIST, and it returns labels as strings so when you defined `y_train_5 = (y_train == 5)`, it results an array full of `False`. A solution is to cast `y_train` to int8: `y_train = y_train.astype(np.int8)` (which is what I do in the notebook, just after loading the data).
> 
> Hope this helps,
> Aurélien

yeah it worked!!

**Comment by triumphMe** [comment]
> @umeshhello12 @ageron
> Hi guys, The targets of 'MNIST' dataset downloaded are string digit. So you just need to change to
> y_train_5 = (y_train == '5')
> y_test_5 = (y_test == '5')

love you babe

**Comment by Dawood88** [comment]
> @umeshhello12 @ageron
> Hi guys, The targets of 'MNIST' dataset downloaded are string digit. So you just need to change to
> y_train_5 = (y_train == '5')
> y_test_5 = (y_test == '5')

Thank you man

**Comment by CodingWillow** [comment]
Hi @ageron, thank you so much ! You just saved me from another potential misery lol 
(I often fall into the ML rabbit hole and there seems to be no exit...)

**Comment by AnkitSingh700** [comment]
> Hi @ageron
> 
> Thanks for coming back so quick and apologies I have only got around to it now.
> 
> You were correct I had missed the to int8. I was looking at the old notebook and not the newer one.
> 
> Cheers,
> 
> Pete

Hi @pin0S : Where's the link for the new notebook you're referring to? As I can see only the older notebook in the link: https://github.com/ageron/handson-ml2

**Comment by ageron** [comment]
Hi @AnkitSingh700 ,

I think @pin0S was referring to the [first edition's notebook](https://github.com/ageron/handson-ml/blob/master/03_classification.ipynb) as the "older notebook", and to the [second edition's notebook](https://github.com/ageron/handson-ml2/blob/master/03_classification.ipynb) as the "newer one".

In short, to load MNIST, the new notebook runs this code (in cells 2, 3, and 8):


```python
from sklearn.datasets import fetch_openml

mnist = fetch_openml('mnist_784', version=1, as_frame=False)
X, y = mnist["data"], mnist["target"]
y = y.astype(np.uint8)
```

**Comment by AnkitSingh700** [comment]
Hi @ageron : Thank you so much for your response. One more place where I'm getting stuck is:
In Exercise 2 code on Data Augmentation, on running:
knn_clf = KNeighborsClassifier(**grid_search.best_params_),
I am getting the error message:
---------------------------------------------------------------------------
NameError                                 Traceback (most recent call last)
<ipython-input-295-d0b40ad06e04> in <module>
----> 1 knn_clf = KNeighborsClassifier(**grid_search.best_params_)

NameError: name 'grid_search' is not defined

**Comment by ageron** [comment]
Hi @AnkitSingh700 ,
The error says that `grid_search` is not defined. Since it's defined a few cells above the code you're trying to run, the only explanations I can think of are (1) the cells were not executed in order, or (2) they were modified.
Could you please ensure that you are running the original notebook, or at least that these cells are not modified? Also, please make sure you run the cells in order.
Hope this helps.
