### ISSUE TITLE
Page 52 book code and Chapter 2 Notebook Code - Is this an error?

### ISSUE THREAD

**Issue by bruparel** [ageron/handson-ml#37]
The paragraph at the top of page 52 of your book says "The following code creates an income category attribute by dividing the median income by 1.5 ....., and then merging all the categories greater than 5 into category 5"
housing["income_cat"].where(housing["income_cat"] < 5, 5.0, inplace=True)

Is this an error or an incorrect statement?  It seems to me that the where clause is trying to do the exact opposite, i.e., the condition should be > 5 instead of < 5.?  Please explain.  Also, let me know if this is not the right place to ask questions.  If not then where should I ask...

**Comment by ageron** [comment]
Hi Bharat,

Good question, this is the right place to ask. The code is actually correct, but you are not the first to ask the question, so I guess it must be counter intuitive: the `where()` method returns the items of the `DataFrame` where the condition holds, or else it returns the alternate value (`5.0` in this case) (see the [documentation of where()](https://pandas.pydata.org/pandas-docs/stable/generated/pandas.DataFrame.where.html)).

I hope you are enjoying the book:
Aurélien

**Comment by bruparel** [comment]
Thanks Aurelien.  The book is "Excellent." The Jupyter Notebooks are an ideal complement to the text.

**Comment by riarangogi** [comment]
Hi!

Yes, the book is great. I have one question, "... income category attribute by dividing the median income by 1.5" why 1.5?,thebook say "to limit the number of income categories" but I don't understand why 1.5?

**Comment by odlin2010** [comment]
yes,why 1.5?

**Comment by ageron** [comment]
Thanks for your kind words @bruparel and @riarangogi !  :)

Regarding the choice of 1.5: you want neither too few nor too many categories. For example, suppose you want to sample 1000 people to estimate what candidate the overall population is going to vote for. Suppose you know that a person's sex has a big influence on the vote, then you probably want to make sure that there's exactly the same ratio of each sex in your sample as in the overall population, so about 51.3% female and 48.7% male, hence you need to sample 513 female and 487 male. Now if you are confident that a person's income is also a big factor in the vote, then you might want to do stratified sampling on this variable as well. However, it's a bit harder: the income is more or less a continuous variable, so you first need to define the strata (i.e., income categories) that you will use. One extreme approach would be to define the strata using each income percentile: for example, you could have a stratum with the top 1% income, another with the 98-99th percentile, another with the 97-98th percentile, and so on. In this example, you would end up with 2 strata for the sex and 100 strata for the income, so a total of 200 strata. This would not be very good: you would probably have a hard time finding out what is the percentage of the overall population that falls within each stratum, and it would be hard as well finding the right amount of people from each stratum (even though each stratum would contain on average 5 people, you might end up searching for a long time to fill in all the strata).  Conversely, you could decide to go for the other extreme and have just 2 income strata: below the median income or above it.  This would be okay, but a bit too coarse, and it would certainly be (slightly) better to have a few more income categories, perhaps 4 or 5. They wouldn't necessarily be defined as percentiles: for example, you might want to define a stratum just for the people who are on the minimum wage.
This is just to give you an intuition, but sampling is actually a pretty complex topic, there are [whole books](http://onlinelibrary.wiley.com/doi/10.1002/9781118162934.ch11/summary) about it! In short, you want to make sure you only create strata for the most important variables for your task, and that you don't have too many of them (and of course that your sample size is large enough and that your sampling methodology does not introduce any bias, and so on).

Now, coming back to chapter 2: without dividing by some number, there were a bit too many income categories, some of which only had very few instances. So I decided to divide by some value to reduce the number of categories: dividing by 2 was a bit too much, I ended up with too few categories, so I tried a middle ground, 1.5, and I was happy with it.  It wasn't the best possible methodology, but my goal was just to demonstrate how to do stratified sampling from a technical point of view, not necessarily to explain sampling methodology in depth, that's a complex topic, outside of the scope of my book.

Hope this helps,
Aurélien

**Comment by riarangogi** [comment]
It's perfect, your explanation was very clear. I'm reading the book and would like to have help when I don't understand a concept. It's possible?

**Comment by ageron** [comment]
Sure, I'm happy to help when I can (can't guarantee a quick response, but I'll do my best).  :)

**Comment by rustysmith44** [comment]
ageron, I'm so stuck it's ridiculous.. I'm following along in the book and stuck on page 52 because jupyter keeps giving me a invalid syntax regarding    housing["income_cat"] = np.ceil(housing["median_income"]) / 1.5)   

Has there been a correction to this piece of code?  If not, any idea why I can't get it to run?

Thank you!
-Rusty

**Comment by rustysmith44** [comment]
I'm also getting a key error for 'income_cat'    I think from the code:  housing["income_cat"].where(housing["income_cat] < 5, 5.0, inplace=True)

Thank you for any help you can offer.
Rusty

**Comment by diegoquintanav** [comment]
> ageron, I'm so stuck it's ridiculous.. I'm following along in the book and stuck on page 52 because jupyter keeps giving me a invalid syntax regarding housing["income_cat"] = np.ceil(housing["median_income"]) / 1.5)
> 
> Has there been a correction to this piece of code? If not, any idea why I can't get it to run?
> 
> Thank you!
> -Rusty

You probably want  `np.ceil(housing["median_income"] / 1.5)`,  you have an extra `)` in the middle.

**Comment by ageron** [comment]
Hi @rustysmith44 , as @diegoquintanav pointed out (thanks, btw), the first code example has an extra ) before / 1.5, which should be removed. In the second code example, you have a missing " after the second `income_cat`.

**Comment by SurayaAtouraya** [comment]
I am also getting a KeyError, however my syntax is correct, specifically on the two code lines of page 52.
