### ISSUE TITLE
Chapter 2 - TypeError: object of type 'CategoricalDtype' has no len()

### ISSUE THREAD

**Issue by Rahul954** [ageron/handson-ml#378]
While running below code

```python
from sklearn.model_selection import StratifiedShuffleSplit
split=StratifiedShuffleSplit(n_splits=1,test_size=0.2, random_state=42)
for train_index, test_index in split.split(housing, housing["income_cat"]):
    strat_train_set = housing.loc[train_index]
    strat_test_set = housing.loc[test_index]
```

it gives below error

```python
if hasattr(array, "dtypes") and len(array.dtypes):
TypeError: object of type 'CategoricalDtype' has no len()
```

**Comment by Zram** [comment]
I have the same error =(

**Comment by Rahul954** [comment]
Hello Zram,

If you come across the solution. Please post it.

Else we can wait for someone who has done it successfully to post it.

I believe there will be hundreds who would have done it correctly.

I will also try hard on it.

Regards,
Rahul

**Comment by ageron** [comment]
Hi @Rahul954 ,
I tried to reproduce the problem, but I couldn't.  My guess is that it's a problem with the version of Pandas or NumPy you are using.  Could you please upgrade NumPy and Pandas to the latest version and try again?
Also, could you please paste the full stacktrace, not just the two lines, it would help understand where the bug comes from.
Thanks!

**Comment by Rahul954** [comment]
Hello Aurelien,

I am feeling excited that I got a reply from you. I really appreciate your work from the bottom of my heart that you took out some time from your precious time.

I have fixed it. These are two codes:



___________Not Working _______________________________________________



#To support both python 2 and python 3
from __future__ import division, print_function, unicode_literals
from IPython import get_ipython
#Future statements are special -- they change how your Python module is parsed, which is why they must be at the top of the file. They give new -- or different -- meaning to words or symbols in your file. 
#print_function is the module containing the new implementation of 'print' as per how it is behaving in python v3.

#common imports

#IPython has a set of predefined ‘magic functions’ that you can call with a command line style syntax. There are two kinds of magics, line-oriented and cell-oriented. Line magics are prefixed with the % character and work much like OS command-line calls: they get as an argument the rest of the line, where arguments are passed without parentheses or quotes. Lines magics can return results and can be used in the right hand side of an assignment. Cell magics are prefixed with a double %%, and they are functions that get as an argument not only the rest of the line, but also the lines below it in a separate argument.
#%matplotlib inline sets the backend of matplotlib to the 'inline' backend:
#With this backend, the output of plotting commands is displayed inline within frontends like the Jupyter notebook, directly below the code cell that produced it. The resulting plots will then also be stored in the notebook document.
#When using the 'inline' backend, your matplotlib graphs will be included in your notebook, next to the code. It may be worth also reading How to make IPython notebook matplotlib plot inline for reference on how to use it in your code.
get_ipython().magic('matplotlib inline')
import matplotlib as mpl
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
import sklearn.linear_model
import os

#The OS module in Python provides a way of using operating system dependent functionality. 
#The functions that the OS module provides allows you to interface with the underlying operating system that Python is running on – be that Windows, Mac or Linux. 
#You can find important information about your location or about the process. 




# to make this notebook's output stable across runs
np.random.seed(42)

#To plot pretty figures
#Matplotlib also provides a couple of convenience functions for modifying rc settings. The matplotlib.rc() command can be used to modify multiple settings in a single group at once, using keyword arguments: import matplotlib as mpl   mpl.rc('lines', linewidth=2, color='r')
mpl.rc('axes', labelsize=14)
mpl.rc('xtick',labelsize=12)
mpl.rc('ytick',labelsize=12)
#Get or set the current tick locations and labels of the x-axis.


## Where to save the figures
PROJECT_ROOT_DIR = "."
CHAPTER_ID = "fundamentals"

def save_fig(fig_id, tight_layout=True):
    path = os.path.join(PROJECT_ROOT_DIR, "images", CHAPTER_ID, fig_id + ".png")
    print("Saving figure", fig_id)
    if tight_layout:
        plt.tight_layout()
    plt.savefig(path, format='png', dpi=300)
    
    #The DPI matters a great deal when we use imshow(..) somewhere on the figure. These bitmaps get rasterised down as they get embedded into the SVG. With the default DPI, the results are even worse than what we see on the screen, definitely unsuitable for publications. 

# Ignore useless warnings (see SciPy issue #5998)
import warnings
warnings.filterwarnings(action="ignore", message="^internal gelsd")






#################  GET THE DATA ###################################################

import tarfile
from six.moves import urllib

DOWNLOAD_ROOT="https://raw.githubusercontent.com/ageron/handson-ml/master/"
HOUSING_PATH=os.path.join("datasets","housing")
HOUSING_URL=DOWNLOAD_ROOT + "datasets/housing/housing.tgz"

def fetch_housing_data(housing_url=HOUSING_URL,housing_path=HOUSING_PATH):
    if not os.path.isdir(housing_path):
        os.makedirs(housing_path)
    tgz_path=os.path.join(housing_path,"housing.tgz")
    urllib.request.urlretrieve(housing_url,tgz_path)
    housing_tgz=tarfile.open(tgz_path)
    housing_tgz.extractall(path=housing_path)
    housing_tgz.close()
    
fetch_housing_data()


def load_housing_data(housing_path=HOUSING_PATH):
    csv_path = os.path.join(housing_path,"housing.csv")
    return pd.read_csv(csv_path)

housing = load_housing_data()
print(housing.head())

print(housing.info())

housing['ocean_proximity'].value_counts()

print (housing.describe())

###############################################################################

#bins : integer or sequence or ‘auto’, optional
#If an integer is given, bins + 1 bin edges are calculated and returned, consistent with numpy.histogram().
#If bins is a sequence, gives bin edges, including left edge of first bin and right edge of last bin. In this case, bins is returned unmodified.
#All but the last (righthand-most) bin is half-open. In other words, if bins is:
#[1, 2, 3, 4] then the first bin is [1, 2) (including 1, but excluding 2) and the second [2, 3). The last bin, however, is [3, 4], which includes 4.

get_ipython().magic('matplotlib inline')
housing.hist(bins=50, figsize=(20,15))
save_fig("attribute_histogram_plots")
plt.show()
#Matplotlib allows the aspect ratio, DPI and figure size to be specified when the Figure object is created, 
#using the figsize and dpi keyword arguments. figsize is a tuple of the width and height of the 
#figure in inches, and dpi is the dots-per-inch (pixel per inch). To create an 800x400 pixel, 100 dots-per-inch
 #figure, we can do:
#fig = plt.figure(figsize=(8,4), dpi=100)
 
 
###################################################################################
 
# To make this notebook's output identical ta each step
np.random.seed(42)

def split_train_test(data, test_ratio):
    shuffled_indices = np.random.permutation(len(data))
    test_set_size= int(len(data) * test_ratio)
    test_indices = shuffled_indices[:test_set_size]
    train_indices = shuffled_indices[test_set_size:]
    return data.iloc[train_indices], data.iloc[test_indices]

train_set, test_set = split_train_test(housing, 0.2)
print(len(train_set),"Train +", len(test_set), "Test")


#from zlib import crc32 
#For applications that require data compression, the functions in this module allow compression and decompression, using the zlib library. 
#zlib.crc32(data[, value])
#Computes a CRC (Cyclic Redundancy Check) checksum of data. If value is present, it is used as the starting value of the checksum; otherwise, a fixed default value is used. This allows computing a running checksum over the concatenation of several inputs. The algorithm is not cryptographically strong, and should not be used for authentication or digital signatures. Since the algorithm is designed for use as a checksum algorithm, it is not suitable for use as a general hash algorithm.
def split_train_test_by_id(data, test_ratio, id_column):
    ids = data[id_column]
    in_test_set = ids.apply(lambda id_: test_set_check(id_, test_ratio))
    return data.loc[~in_test_set], data.loc[in_test_set]

import hashlib
def test_set_check(identifier, test_ratio, hash=hashlib.md5):
    return hash(np.int64(identifier)).digest()[-1] < 256 * test_ratio

housing_with_id = housing.reset_index() #adds an index column
train_set, test_set = split_train_test_by_id(housing_with_id, 0.2, "index")

housing_with_id["id"] = housing["longitude"] * 1000 + housing["latitude"]
train_set, test_set = split_train_test_by_id(housing_with_id, 0.2, "id")

print(test_set.head())

###############################################################################

housing["median_income"].hist()

housing["income_cat"] = pd.cut(housing["median_income"],
       bins=[0.0,1.5,3.0,4.5,6.0,np.inf],
       labels=[1,2,3,4,5])

print(housing["income_cat"])

print(housing["income_cat"].value_counts())

housing["income_cat"].hist()

#######################################################################

from sklearn.model_selection import StratifiedShuffleSplit

split = StratifiedShuffleSplit(n_splits=1, test_size=0.2, random_state=42)
for train_index, test_index in split.split(housing, housing["income_cat"]):
    strat_train_set = housing.loc[train_index]
    strat_test_set = housing.loc[test_index]
    

#print(strat_test_set["income_cat"].value_counts() / len(strat_test_set))


#print(housing["income_cat"].value_counts()/len(housing))

_______________________________________________________________________________

___________________Working ____________________________________________________

(base) [root@rrathore Machine_Learning_Scikit_Tensorflow]# cat Chapter2.py 
#To support both python 2 and python 3
from __future__ import division, print_function, unicode_literals
from IPython import get_ipython
#Future statements are special -- they change how your Python module is parsed, which is why they must be at the top of the file. They give new -- or different -- meaning to words or symbols in your file. 
#print_function is the module containing the new implementation of 'print' as per how it is behaving in python v3.

#common imports

#IPython has a set of predefined ‘magic functions’ that you can call with a command line style syntax. There are two kinds of magics, line-oriented and cell-oriented. Line magics are prefixed with the % character and work much like OS command-line calls: they get as an argument the rest of the line, where arguments are passed without parentheses or quotes. Lines magics can return results and can be used in the right hand side of an assignment. Cell magics are prefixed with a double %%, and they are functions that get as an argument not only the rest of the line, but also the lines below it in a separate argument.
#%matplotlib inline sets the backend of matplotlib to the 'inline' backend:
#With this backend, the output of plotting commands is displayed inline within frontends like the Jupyter notebook, directly below the code cell that produced it. The resulting plots will then also be stored in the notebook document.
#When using the 'inline' backend, your matplotlib graphs will be included in your notebook, next to the code. It may be worth also reading How to make IPython notebook matplotlib plot inline for reference on how to use it in your code.
get_ipython().magic('matplotlib inline')
import matplotlib as mpl
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
import sklearn.linear_model
import os

#The OS module in Python provides a way of using operating system dependent functionality. 
#The functions that the OS module provides allows you to interface with the underlying operating system that Python is running on – be that Windows, Mac or Linux. 
#You can find important information about your location or about the process. 




# to make this notebook's output stable across runs
np.random.seed(42)

#To plot pretty figures
#Matplotlib also provides a couple of convenience functions for modifying rc settings. The matplotlib.rc() command can be used to modify multiple settings in a single group at once, using keyword arguments: import matplotlib as mpl   mpl.rc('lines', linewidth=2, color='r')
mpl.rc('axes', labelsize=14)
mpl.rc('xtick',labelsize=12)
mpl.rc('ytick',labelsize=12)
#Get or set the current tick locations and labels of the x-axis.


## Where to save the figures
PROJECT_ROOT_DIR = "."
CHAPTER_ID = "fundamentals"

def save_fig(fig_id, tight_layout=True):
    path = os.path.join(PROJECT_ROOT_DIR, "images", CHAPTER_ID, fig_id + ".png")
    print("Saving figure", fig_id)
    if tight_layout:
        plt.tight_layout()
    plt.savefig(path, format='png', dpi=300)
    
    #The DPI matters a great deal when we use imshow(..) somewhere on the figure. These bitmaps get rasterised down as they get embedded into the SVG. With the default DPI, the results are even worse than what we see on the screen, definitely unsuitable for publications. 

# Ignore useless warnings (see SciPy issue #5998)
import warnings
warnings.filterwarnings(action="ignore", message="^internal gelsd")






#################  GET THE DATA ###################################################

import tarfile
from six.moves import urllib

DOWNLOAD_ROOT="https://raw.githubusercontent.com/ageron/handson-ml/master/"
HOUSING_PATH=os.path.join("datasets","housing")
HOUSING_URL=DOWNLOAD_ROOT + "datasets/housing/housing.tgz"

def fetch_housing_data(housing_url=HOUSING_URL,housing_path=HOUSING_PATH):
    if not os.path.isdir(housing_path):
        os.makedirs(housing_path)
    tgz_path=os.path.join(housing_path,"housing.tgz")
    urllib.request.urlretrieve(housing_url,tgz_path)
    housing_tgz=tarfile.open(tgz_path)
    housing_tgz.extractall(path=housing_path)
    housing_tgz.close()
    
fetch_housing_data()


def load_housing_data(housing_path=HOUSING_PATH):
    csv_path = os.path.join(housing_path,"housing.csv")
    return pd.read_csv(csv_path)

housing = load_housing_data()
print(housing.head())

print(housing.info())

housing['ocean_proximity'].value_counts()

print (housing.describe())

###############################################################################

#bins : integer or sequence or ‘auto’, optional
#If an integer is given, bins + 1 bin edges are calculated and returned, consistent with numpy.histogram().
#If bins is a sequence, gives bin edges, including left edge of first bin and right edge of last bin. In this case, bins is returned unmodified.
#All but the last (righthand-most) bin is half-open. In other words, if bins is:
#[1, 2, 3, 4] then the first bin is [1, 2) (including 1, but excluding 2) and the second [2, 3). The last bin, however, is [3, 4], which includes 4.

get_ipython().magic('matplotlib inline')
housing.hist(bins=50, figsize=(20,15))
save_fig("attribute_histogram_plots")
plt.show()
#Matplotlib allows the aspect ratio, DPI and figure size to be specified when the Figure object is created, 
#using the figsize and dpi keyword arguments. figsize is a tuple of the width and height of the 
#figure in inches, and dpi is the dots-per-inch (pixel per inch). To create an 800x400 pixel, 100 dots-per-inch
 #figure, we can do:
#fig = plt.figure(figsize=(8,4), dpi=100)
 
 
###################################################################################
 
# To make this notebook's output identical ta each step
np.random.seed(42)

#def split_train_test(data, test_ratio):
#    shuffled_indices = np.random.permutation(len(data))
#    test_set_size= int(len(data) * test_ratio)
#    test_indices = shuffled_indices[:test_set_size]
#    train_indices = shuffled_indices[test_set_size:]
#    return data.iloc[train_indices], data.iloc[test_indices]

#train_set, test_set = split_train_test(housing, 0.2)
#print(len(train_set),"Train +", len(test_set), "Test")


#from zlib import crc32 
#For applications that require data compression, the functions in this module allow compression and decompression, using the zlib library. 
#zlib.crc32(data[, value])
#Computes a CRC (Cyclic Redundancy Check) checksum of data. If value is present, it is used as the starting value of the checksum; otherwise, a fixed default value is used. This allows computing a running checksum over the concatenation of several inputs. The algorithm is not cryptographically strong, and should not be used for authentication or digital signatures. Since the algorithm is designed for use as a checksum algorithm, it is not suitable for use as a general hash algorithm.

import hashlib


def test_set_check(identifier, test_ratio, hash=hashlib.md5):
    return hash(np.int64(identifier)).digest()[-1] < 256 * test_ratio

def split_train_test_by_id(data, test_ratio, id_column,hash=hashlib.md5):
    ids = data[id_column]
    in_test_set = ids.apply(lambda id_: test_set_check(id_, test_ratio))
    return data.loc[~in_test_set], data.loc[in_test_set]




housing_with_id = housing.reset_index() #adds an index column
train_set, test_set = split_train_test_by_id(housing_with_id, 0.2, "index")

housing_with_id["id"] = housing["longitude"] * 1000 + housing["latitude"]
train_set, test_set = split_train_test_by_id(housing_with_id, 0.2, "id")

print(test_set.head())

###############################################################################



housing["median_income"].hist()

housing["income_cat"]=np.ceil(housing["median_income"]/1.5)
housing["income_cat"].where(housing["income_cat"] < 5,5.0,inplace=True)

#housing["income_cat"] = pd.cut(housing["median_income"],
#       bins=[0.0,1.5,3.0,4.5,6.0,np.inf],
#       labels=[1,2,3,4,5])

print(housing["income_cat"])

print(housing["income_cat"].value_counts())

#housing["income_cat"].hist()

#######################################################################

from sklearn.model_selection import StratifiedShuffleSplit

split = StratifiedShuffleSplit(n_splits=1, test_size=0.2, random_state=42)
for train_index, test_index in split.split(housing, housing["income_cat"]):
    strat_train_set = housing.loc[train_index]
    strat_test_set = housing.loc[test_index]
    

print(strat_test_set["income_cat"].value_counts() / len(strat_test_set))


print(housing["income_cat"].value_counts()/len(housing))



    
______________________________________________________________________________




The first code which is not working is on github. Then I read the book again and made modifications according to the book which worked perfectly.



I will really appreciate it that since you are extending your both arms to help learners like us to post the code which is working perfectly for you for all the chapters. It will really help a lot to save time. Though after making mistakes I learn some new things. 


Regards,
Rahul Rathore

**Comment by Zram** [comment]
> housing["income_cat"]=np.ceil(housing["median_income"]/1.5)
> housing["income_cat"].where(housing["income_cat"] < 5,5.0,inplace=True)
> 
> #housing["income_cat"] = pd.cut(housing["median_income"],

Wow Thanx mate it works!

**Comment by ageron** [comment]
Hi @Rahul954 ,

Thanks for your feedback, and for your very kind words! :)  I'm glad you find the solution to the problem.

I recently replaced the code to compute the `income_cat` column, it worked for me, but I'll double check and I'll add a comment. Perhaps it does not work with all versions of Pandas? Did you upgrade to the latest version of Pandas? If not, what version are you using?

Also, when I asked for the full stacktrace, I meant the exception stacktrace, not the full code (thanks @Zram for identifying the delta, I wasn't sure what the difference was between the non-working code and the working code). For example, if I define a simple function like this:

```python
def f(x):
    return 10 / x
```

Then a stacktrace would look like this:

```
>>> f(0)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "<stdin>", line 2, in f
ZeroDivisionError: division by zero
```

Note that in github (Markdown format), you can surround code examples with \`\`\` . You can also add the language at the beginning to get syntax highlighting:

\`\`\`python
your code
goes here
\`\`\`

Hope this helps,
Aurélien

**Comment by ageron** [comment]
I can confirm that everything works fine for me using Pandas 0.24.1.

**Comment by ageron** [comment]
Perhaps it's a Python 2 issue? Which version of Python are you using? Run this command:

```python
import sys

print(sys.version)
```

If you are using Python 2, then you should really migrate to Python 3 (if possible 3.7, and at least 3.5).  Python 2 is going do end its life on January 1st 2020, so it's best to migrate to Python 3 as soon as possible.

**Comment by Zram** [comment]
> 
> 
> Perhaps it's a Python 2 issue? Which version of Python are you using? Please run this command:
> 
> ```python
> import sys
> 
> print(sys.version)
> ```
> 
> If you are using Python 2, then you should really migrate to Python 3 (if possible 3.7, and at least 3.5). Python 2 is going do end its life on January 1st 2020, so it's best to migrate to Python 3 as soon as possible.

I'm using Python 3.
The scikit-learn version is 0.20.1.
The pandas version is 0.23.4.
The numpy version is 1.15.4.

Error looks like
### 

> TypeError                                 Traceback (most recent call last)
> <ipython-input-37-9730d791daa8> in <module>
>       2 
>       3 split = StratifiedShuffleSplit(n_splits=1, test_size=0.2, random_state=42)
> ----> 4 for train_index, test_index in split.split(housing, housing["income_cat"]):
>       5     strat_train_set = housing.loc[train_index]
>       6     strat_test_set = housing.loc[test_index]
> 
> ~\Anaconda3\lib\site-packages\sklearn\model_selection\_split.py in split(self, X, y, groups)
>    1771         to an integer.
>    1772         """
> -> 1773         y = check_array(y, ensure_2d=False, dtype=None)
>    1774         return super(StratifiedShuffleSplit, self).split(X, y, groups)
>    1775 
> 
> ~\Anaconda3\lib\site-packages\sklearn\utils\validation.py in check_array(array, accept_sparse, accept_large_sparse, dtype, order, copy, force_all_finite, ensure_2d, allow_nd, ensure_min_samples, ensure_min_features, warn_on_dtype, estimator)
>     478     # DataFrame), and store them. If not, store None.
>     479     dtypes_orig = None
> --> 480     if hasattr(array, "dtypes") and len(array.dtypes):
>     481         dtypes_orig = np.array(array.dtypes)
>     482 
> 
> TypeError: object of type 'CategoricalDtype' has no len()

**Comment by Rahul954** [comment]
Hello @ageron ,

I am using below version.

print(sys.version)
3.7.1 (default, Dec 14 2018, 19:28:38) 
[GCC 7.3.0]

Python3.7

pd.__version__
Out[6]: '0.23.4'

np.version.version
Out[9]: '1.15.4'


print(sklearn.__version__)
0.20.1

Regards,
Rahul

**Comment by Zram** [comment]
I just tested the code with the scikit-learn version is 0.19.0 and it works. The problem seems in new version of scikit-learn

**Comment by ageron** [comment]
Aha! Indeed, @Zram , I managed to reproduce the bug with Scikit-Learn 0.20.1, and only with that version. I tried 0.20.0, 0.20.2, 0.20.3 and 0.19.0.

So the bottom line is: you can either use the `pd.where()` solution like in the book, or you can use the `pd.cut()` version as long as you are not using Scikit-Learn 0.20.1.

To upgrade:

```bash
pip3 install -U scikit-learn
```

Thanks for your help in fixing this issue! Please close this issue if the problem is fixed.

**Comment by Rahul954** [comment]
Hello,

Thanks for your help.

I am closing it.

Regards,
Rahul

**Comment by choym92** [comment]
Hello Aurelien,

Love your work so much!! I am digging through it. Thanks Rahul for this post as well :)
I came across same exact issue and was discouraged moving on from CH2 due to not being able to debug.

As above, scikit 20.1 -> 20.3 solved it.

Appreciate both of you.
