### ISSUE TITLE
Chapter-2 Custom Transformers

### ISSUE THREAD

**Issue by Aimech** [ageron/handson-ml#389]
Hello @ageron 

So, after setting up the class CombinedAttributesAdder, when I create the object "attr_adder", I get the following error:

---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-57-1c53188eba24> in <module>()
     18 
     19 
---> 20 attr_adder = CombinedAttributesAdder(add_bedrooms_per_room=False)
     21 housing_extra_attribs = attr_adder.transform(housing.values)

TypeError: object() takes no parameters

I am not sure what is the main cause of this error. Kindly help.

Also, great book. :)

**Comment by ageron** [comment]
Thanks @Aimech ,
It looks like the `CombinedAttributesAdder` is just an instance of the `object` class? Could you please ensure you are using exactly the same code as in the notebook? In particular, make sure the indentation is correct.

```python
from sklearn.base import BaseEstimator, TransformerMixin

# get the right column indices: safer than hard-coding indices 3, 4, 5, 6
rooms_ix, bedrooms_ix, population_ix, household_ix = [
    list(housing.columns).index(col)
    for col in ("total_rooms", "total_bedrooms", "population", "households")]

class CombinedAttributesAdder(BaseEstimator, TransformerMixin):
    def __init__(self, add_bedrooms_per_room = True): # no *args or **kwargs
        self.add_bedrooms_per_room = add_bedrooms_per_room
    def fit(self, X, y=None):
        return self  # nothing else to do
    def transform(self, X, y=None):
        rooms_per_household = X[:, rooms_ix] / X[:, household_ix]
        population_per_household = X[:, population_ix] / X[:, household_ix]
        if self.add_bedrooms_per_room:
            bedrooms_per_room = X[:, bedrooms_ix] / X[:, rooms_ix]
            return np.c_[X, rooms_per_household, population_per_household,
                         bedrooms_per_room]
        else:
            return np.c_[X, rooms_per_household, population_per_household]

attr_adder = CombinedAttributesAdder(add_bedrooms_per_room=False)
```

**Comment by Aimech** [comment]
Thanks, @ageron for the help.

I was being silly while defining the class constructor. It's working now.

Thanks once again.

**Comment by naazsadaf** [comment]
Are you taking suresh sir's classes for bda
