### ISSUE TITLE
Apply for translation of the Chinese version, I hope to get authorization! 

### ISSUE THREAD

**Issue by jiangzhonglian** [ageron/handson-ml#390]
Hello, Mr. Aurelian Gijon:

##  📚Documentation

Hello everyone, we are [ApacheCN](http://www.apachecn.org), an open source community in China that focuses on big data and artificial intelligence.

Ten months ago, several people inside our organization heard that the book "Hands-on Machine Learning with Scikit-Learn and TensorFlow" was great! Therefore, while learning and translating, I hope that more Chinese people will know this valuable book, and it will be convenient for them to review later.

Compiled URL: <https://hand2st.apachecn.org>

I was surprised that the translation was originally used for learning. It was read and studied by many people in China. I am really happy to tell Mr. Aurelian Gijon about this good thing.

We are very willing to continue to do some Chinese localization for this project. If possible, please give us some authorization (for example: allow us to continue to translate, afraid of misunderstanding, I explain: this and we have no economic interests, just pure open source, translation and knowledge sharing). If you feel that our translation is OK, we are also happy to submit a Chinese version to your GitHub project for consolidation.

ApacheCN - 片刻

**Comment by ageron** [comment]
Hi @jiangzhonglian ,
Thanks for your kind words, I am glad that your ApacheCN community is enjoying my book.
A Chinese edition of my book is actually already available here: https://homl.info/getchinese
I hope you will enjoy this translation.
I will ask O'Reilly what they think about a second translation, they have the rights on the translations, so I am not the one deciding. You can also write to them at rights@oreilly.com
Hope this helps,
Aurélien

**Comment by jiangzhonglian** [comment]
Thank you, I will email you immediately to explain our situation.
