### ISSUE TITLE
Chapter 2 Training and Evaluating on the training set: Error, shapes not aligned

### ISSUE THREAD

**Issue by Aimech** [ageron/handson-ml#393]
Hi @ageron ,

After preparing the transformed version of some_data using `full_pipeline.transform()`.  I am getting the following error:

```python
some_data = housing.iloc[:5]
some_labels = housing_labels.iloc[:5]
some_data_prepared = full_pipeline.transform(some_data)
print("Predictions:", lin_reg.predict(some_data_prepared))
```

```
ValueError                                Traceback (most recent call last)
<ipython-input-83-5b80b83d416d> in <module>()
      2 some_labels = housing_labels.iloc[:5]
      3 some_data_prepared = full_pipeline.transform(some_data)
----> 4 print("Predictions:", lin_reg.predict(some_data_prepared))

C:\Program Files (x86)\Microsoft Visual Studio\Shared\Anaconda3_64\lib\site-packages\sklearn\linear_model\base.py in predict(self, X)
    254             Returns predicted values.
    255         """
--> 256         return self._decision_function(X)
    257 
    258     _preprocess_data = staticmethod(_preprocess_data)

C:\Program Files (x86)\Microsoft Visual Studio\Shared\Anaconda3_64\lib\site-packages\sklearn\linear_model\base.py in _decision_function(self, X)
    239         X = check_array(X, accept_sparse=['csr', 'csc', 'coo'])
    240         return safe_sparse_dot(X, self.coef_.T,
--> 241                                dense_output=True) + self.intercept_
    242 
    243     def predict(self, X):

C:\Program Files (x86)\Microsoft Visual Studio\Shared\Anaconda3_64\lib\site-packages\sklearn\utils\extmath.py in safe_sparse_dot(a, b, dense_output)
    138         return ret
    139     else:
--> 140         return np.dot(a, b)
    141 
    142 

ValueError: shapes (5,13) and (15,) not aligned: 13 (dim 1) != 15 (dim 0)
```

Also, the shape of the `housing_prepared` is (16512, 15) instead of 16.

Kindly help in figuring out what causes this anomaly.

Regards,
Karan(@aimech)

**Comment by ageron** [comment]
Hi @Aimech ,
Thanks for your feedback.  Could you please make sure you have the latest versions of Scikit-Learn and Pandas (and you might as well make sure you also have the latest versions of NumPy and Matplotlib). You can upgrade using pip:

```bash
pip3 install -U scikit-learn pandas numpy matplotlib
```

Then make sure you have the latest version of the notebook (`git pull`) and restart the Jupyter kernel and run the notebook from the start.

Hope this helps,
Aurélien

**Comment by Aimech** [comment]
Hi Aurélien,

Yes, you were right. I hadn't updated these libraries in a while. Thanks to you, I am now done with Chapter 2. And I can move on to the subsequent chapters now.

I really appreciated you helping us learners like this, on every step.

Keep up the good work.

Thanks, once again.
Karan
