### ISSUE TITLE
Binder link is broken

### ISSUE THREAD

**Issue by victorakabutu** [ageron/handson-ml#4]
Binder link leads to a page which requires password. Text on the page reads:

Token authentication is enabled. You need to open the notebook server with its first-time login token in the URL, or enable a password in order to gain access. The command:

jupyter notebook list

will show you the URLs of running servers with their tokens, which you can copy and paste into your browser. For example:

Currently running servers:
http://localhost:8888/?token=c8de56fa... :: /Users/you/notebooks

Or you can paste just the token value into the password field on this page.

Cookies are required for authenticated access to notebooks.

**Comment by ageron** [comment]
Thanks for your feedback. Unfortunately, Binder seems to be down way too often, so I decided to drop it.
It's such a great project, but oh well...
