### ISSUE TITLE
Chapter 2 - deprecated import of pandas module

### ISSUE THREAD

**Issue by martynoconnor** [ageron/handson-ml#40]
In chapter two, the cell which imports the scatter matrix from pandas uses deprecated call to do so:

`from pandas.tools.plotting import scatter_matrix

attributes = ["median_house_value", "median_income", "total_rooms",
              "housing_median_age"]
scatter_matrix(housing[attributes], figsize=(12, 8))
save_fig("scatter_matrix_plot")`

This returns the warning:

`/home/martyn/anaconda2/lib/python2.7/site-packages/ipykernel/__main__.py:5: FutureWarning: 'pandas.tools.plotting.scatter_matrix' is deprecated, import 'pandas.plotting.scatter_matrix' instead.`

It is remedied by simply deleting the tools. in after the "from pandas"

**Comment by ageron** [comment]
Hi @martynoconnor, thanks for your feedback.

You are right that the import path is deprecated, but only in Pandas 0.20.  The notebooks are based on Pandas 0.19 (see `requirements.txt`).  However, I'm currently thinking about upgrading the libraries, in particular to upgrade to TensorFlow 1.2.  When I do that I'll make sure to fix the import path, thanks for the heads up!

Cheers,
Aurélien

**Comment by salutatio** [comment]
With Pandas 0.20, you can use this : 

from pandas.plotting import scatter_matrix
attributes = ["median_house_value", "median_income", "total_rooms",
"housing_median_age"]
scatter_matrix(housing[attributes], figsize=(12, 8))
