### ISSUE TITLE
Chapter 2 dataset URL not found

### ISSUE THREAD

**Issue by pgmcr** [ageron/handson-ml#403]
When running the fetch_housing_data() in chapter 2, I get this error:
---------------------------------------------------------------------------
HTTPError                                 Traceback (most recent call last)
<ipython-input-8-2aa5507aa879> in <module>
      8     housing_tgz.close()
      9 
---> 10 fetch_housing_data()

<ipython-input-8-2aa5507aa879> in fetch_housing_data(housing_url, housing_path)
      3         os.makedirs(housing_path)
      4     tgz_path = os.path.join(housing_path, "housing.tgz")
----> 5     urllib.request.urlretrieve(housing_url, tgz_path)
      6     housing_rgz = tarfile.open(tgz_path)
      7     housing_tgz.extractall(path=houseing_path)

c:\users\...\appdata\local\programs\python\python37-32\lib\urllib\request.py in urlretrieve(url, filename, reporthook, data)
    245     url_type, path = splittype(url)
    246 
--> 247     with contextlib.closing(urlopen(url, data)) as fp:
    248         headers = fp.info()
    249 

c:\users\...\appdata\local\programs\python\python37-32\lib\urllib\request.py in urlopen(url, data, timeout, cafile, capath, cadefault, context)
    220     else:
    221         opener = _opener
--> 222     return opener.open(url, data, timeout)
    223 
    224 def install_opener(opener):

c:\users\...\appdata\local\programs\python\python37-32\lib\urllib\request.py in open(self, fullurl, data, timeout)
    529         for processor in self.process_response.get(protocol, []):
    530             meth = getattr(processor, meth_name)
--> 531             response = meth(req, response)
    532 
    533         return response

c:\users\...\appdata\local\programs\python\python37-32\lib\urllib\request.py in http_response(self, request, response)
    639         if not (200 <= code < 300):
    640             response = self.parent.error(
--> 641                 'http', request, response, code, msg, hdrs)
    642 
    643         return response

c:\users\...\appdata\local\programs\python\python37-32\lib\urllib\request.py in error(self, proto, *args)
    567         if http_err:
    568             args = (dict, 'default', 'http_error_default') + orig_args
--> 569             return self._call_chain(*args)
    570 
    571 # XXX probably also want an abstract factory that knows when it makes

c:\users\...\appdata\local\programs\python\python37-32\lib\urllib\request.py in _call_chain(self, chain, kind, meth_name, *args)
    501         for handler in handlers:
    502             func = getattr(handler, meth_name)
--> 503             result = func(*args)
    504             if result is not None:
    505                 return result

c:\users\...\appdata\local\programs\python\python37-32\lib\urllib\request.py in http_error_default(self, req, fp, code, msg, hdrs)
    647 class HTTPDefaultErrorHandler(BaseHandler):
    648     def http_error_default(self, req, fp, code, msg, hdrs):
--> 649         raise HTTPError(req.full_url, code, msg, hdrs, fp)
    650 
    651 class HTTPRedirectHandler(BaseHandler):

HTTPError: HTTP Error 404: Not Found

When trying to visit the housing_url I get a 404 too.

**Comment by ageron** [comment]
Hi @pgmcr ,

Thanks for your feedback.  Could you please print the housing_url and copy the value here?

**Comment by pgmcr** [comment]
The URL was [https://github.com/ageron/handson-ml/blob/master/datasets/housing/housing.tgz?raw=true](https://raw.githubusercontent.com/ageron/handson-ml/master/datasets/housing/housing.tgz)
Today the URL works fine, but I replaced it with [https://github.com/ageron/handson-ml/blob/master/datasets/housing/housing.tgz?raw=true](https://github.com/ageron/handson-ml/blob/master/datasets/housing/housing.tgz?raw=true)

**Comment by ageron** [comment]
Hi @pgmcr,
I'm glad it works now. I don't see the difference between the two URLs.
The notebook uses the following URL:

```
https://raw.githubusercontent.com/ageron/handson-ml/master/datasets/housing/housing.tgz
```

Both your URL and this one seem to work fine. Not sure what went wrong. I'm closing this issue but feel free to reopen it if you still experience some problems.

**Comment by top-engineer** [comment]
Hi,

the DOWNLOAD_ROOT url in the book does not work. Running the "fetch_housing_data()" function returns a 404 
"https://raw.githubusercontent.com/ageron/handson-ml/master/"

HTTPError: HTTP Error 404: Not Found

**Comment by ageron** [comment]
Hi @top-engineer ,

I just double-checked, everything works fine for me:

```python
import os
import tarfile
import urllib

DOWNLOAD_ROOT = "https://raw.githubusercontent.com/ageron/handson-ml/master/"
HOUSING_PATH = os.path.join("datasets", "housing")
HOUSING_URL = DOWNLOAD_ROOT + "datasets/housing/housing.tgz"

def fetch_housing_data(housing_url=HOUSING_URL, housing_path=HOUSING_PATH):
    os.makedirs(housing_path, exist_ok=True)
    tgz_path = os.path.join(housing_path, "housing.tgz")
    urllib.request.urlretrieve(housing_url, tgz_path)
    housing_tgz = tarfile.open(tgz_path)
    housing_tgz.extractall(path=housing_path)
    housing_tgz.close()

fetch_housing_data()
```

Could you please run the code above and confirm that it works for you? If so, could you please double-check your code, as it probably differs slightly from this code.

Hope this helps.

**Comment by edwardmfho** [comment]
As @ageron mentioned in his comment above, the following code should work, sorry for a repetitive comment:

`DOWNLOAD_ROOT = "https://raw.githubusercontent.com/ageron/handson-ml/master/"
HOUSING_PATH = os.path.join("datasets",'housing')
HOUSING_URL = DOWNLOAD_ROOT + "datasets/housing/housing.tgz"`
