### ISSUE TITLE
Chapter 2, Traning and evaluating , Numpy shape incompatibility

### ISSUE THREAD

**Issue by rbnphlp** [ageron/handson-ml#408]
Hi ,
Thank you for the awesome book ! 
I am working through the code , and keep getting a error :
![Screenshot from 2019-04-17 16-41-27](https://user-images.githubusercontent.com/14616621/56301424-ae787d80-612f-11e9-97e5-47bf9174f070.png)

![Screenshot from 2019-04-17 16-47-07](https://user-images.githubusercontent.com/14616621/56301821-79b8f600-6130-11e9-9854-bd63e5f15737.png)
The problem is I have a different size of np.array returned for the training dataset (20 colums), and for the 5 instances(18) . I am guessing this is because  5 rows only contained (3/5) ocean proximity categories and the encoder only worked for those . I am not sure what the best way to go about resolving this  other than having more trainign data

Thank you!

**Comment by ageron** [comment]
Hi @rbnphlp ,

Thanks for your kind words and your question. Apparently you are not running the correct code. In the notebook, I used this:

```python
some_data_prepared = full_pipeline.transform(some_data)
```

But your code uses this (`fit_transform()` instead of `transform()`):

```python
some_data_prepared = full_pipeline.fit_transform(some_data)
```

The only data you should fit is the training data. You should not fit validation data, test data or new data. `some_data` is new data, so you should not call `fit_transform()`.

Hope this helps,
Aurélien

**Comment by rbnphlp** [comment]
> Hi @rbnphlp ,
> 
> Thanks for your kind words and your question. Apparently you are not running the correct code. In the notebook, I used this:
> 
> ```python
> some_data_prepared = full_pipeline.transform(some_data)
> ```
> 
> But your code uses this (`fit_transform()` instead of `transform()`):
> 
> ```python
> some_data_prepared = full_pipeline.fit_transform(some_data)
> ```
> 
> The only data you should fit is the training data. You should not fit validation data, test data or new data. `some_data` is new data, so you should not call `fit_transform()`.
> 
> Hope this helps,
> Aurélien
