### ISSUE TITLE
Chapter 10 - AttributeError: module 'tensorflow' has no attribute 'keras'

### ISSUE THREAD

**Issue by Rahul954** [ageron/handson-ml#410]
Hello,

I am getting below error when I am running program in chapter 10.
AttributeError: module 'tensorflow' has no attribute 'keras'

~~ Getting error for this line ~~~
(X_train, y_train), (X_test, y_test) = tf.keras.datasets.mnist.load_data()

~~~

Traceback (most recent call last):

  File "<ipython-input-9-ec8c1f97086d>", line 1, in <module>
    runfile('/root/Machine_Learning_Scikit_Tensorflow/Chapter10.py', wdir='/root/Machine_Learning_Scikit_Tensorflow')

  File "/root/anaconda3/lib/python3.6/site-packages/spyder_kernels/customize/spydercustomize.py", line 786, in runfile
    execfile(filename, namespace)

  File "/root/anaconda3/lib/python3.6/site-packages/spyder_kernels/customize/spydercustomize.py", line 110, in execfile
    exec(compile(f.read(), filename, 'exec'), namespace)

  File "/root/Machine_Learning_Scikit_Tensorflow/Chapter10.py", line 154, in <module>
    (X_train, y_train), (X_test, y_test) = tf.keras.datasets.mnist.load_data()

AttributeError: module 'tensorflow' has no attribute 'keras'



Python Version is 3.6
However, upon checking tensorflow version it shows error like below:
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
tf.VERSION
Traceback (most recent call last):

  File "<ipython-input-10-2e1b684706ab>", line 1, in <module>
    tf.VERSION

AttributeError: module 'tensorflow' has no attribute 'VERSION'

tf.__version__
Traceback (most recent call last):

  File "<ipython-input-11-65996cac02ec>", line 1, in <module>
    tf.__version__

AttributeError: module 'tensorflow' has no attribute '__version__'

~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~


I had installed Tensorflow 1.9 as below
~~~~~
 conda install tensorflow=1.9
conda install tensorflow-gpu=1.9

~~~~~

I have also tried to install Keras

Regards,
Rahul Rathore

**Comment by Rahul954** [comment]
Closing it as with the same installation as yesterday it worked like a charm. The only thing I did today was to power on my laptop and run the program.

**Comment by ageron** [comment]
Hi @Rahul954 ,
Conda allows multiple virtual environments.  Perhaps you were using a different environment? After rebooting, Conda typically goes back to the base environment. This is the environment that conda itself is installed in, so usually you don't want to install anything else in this environment.
You can check which environments are available by running `conda env list`. There will be a `*` next to the active environment. To switch environment, you can try `conda activate my_env` (assuming you want to activate the environment named `my_env`). You can type `conda activate base` or simply `conda activate` to go back to the base environment.
Hope this helps.
