### ISSUE TITLE
Chapter 2: ordinal feature engineering

### ISSUE THREAD

**Issue by igor-kozlov** [ageron/handson-ml#418]
Hello Aurélien,

What is the best way to engineer ordinal features?

Say I have a DataFrame of colors:
```
df = pd.DataFrame([['red'], ['green'], ['yellow']], columns=['colors'])
```
and I want to encode them according to their wavelength 

Color | Wavelength
-- | --
Green | 500 nm
Yellow | 565 nm
Orange | 590 nm
Red | 625 nm

I was going to use OrdinalEncoder from https://scikit-learn.org/stable/modules/generated/sklearn.preprocessing.OrdinalEncoder.html , but it doesn't allow mapping (only ordering of categories).

Thus, I see the following alternatives:
1. To write a custom encoder, say using FunctionTransformer https://scikit-learn.org/stable/modules/generated/sklearn.preprocessing.FunctionTransformer.html#sklearn.preprocessing.FunctionTransformer
2. To use Ordinal encoder from http://contrib.scikit-learn.org/categorical-encoding/ordinal.html
3. To use apply https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.apply.html#pandas.DataFrame.apply or applymap https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.applymap.html before starting to construct a Pipeline.

Please let me know what would be the preferred method.

Thank you,

Igor

P.S.
It seems to me that the mapping functionality should be quite frequently used for feature engineering, isn't it? I am surprised that it is not included in the sklearn and exists as an external http://contrib.scikit-learn.org project. Do you know the reasons behind it?

References:
https://github.com/ageron/handson-ml/issues/348
https://github.com/ageron/handson-ml/issues/349

**Comment by igor-kozlov** [comment]
Thank you very much, @ageron, this is great help!

P.S.
I believe that ```sorted``` was applied on ```wavelengths``` for aesthetic reasons. :-)

**Comment by ageron** [comment]
My pleasure! :)
I thought that the `OrdinalEncoder` expected sorted categories, which is why I sorted the wavelengths (by name, not by wavelength). But I just tried removing `sorted()` and it still works, so I guess the `OrdinalEncoder` doesn't care about the order. Cool!
