### ISSUE TITLE
Ch 2 page 59

### ISSUE THREAD

**Issue by Akash0305** [ageron/handson-ml#423]
Sir pls explain how computing logarithm of attributes helps to solve the problem of tail-heavy distribution ?

**Comment by ageron** [comment]
Great question! Many ML algorithms perform better when the input features have the same scale, and have a roughly Gaussian distribution with the same mean and scale (usually mean 0 and scale 1).
If an input feature does not look Gaussian at all (e.g., it has a tail-heavy distribution), then it's often a good idea to transform it to make it look more Gaussian.

For example, the distribution plotted on the left is tail-heavy, but once I compute its log, it becomes (close to) Gaussian:

![image](https://user-images.githubusercontent.com/76661/57564205-c5328d00-73da-11e9-9e84-ec133d119a25.png)

If you want to play around with this figure, here is the code I used to generate it:

```python
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline  # in Jupyter only

x = np.random.randn(10000) * 2 + 5
x = x * np.exp(x / 5)

plt.figure(figsize=(10, 4))
plt.subplot(1,2,1)
plt.hist(x, bins=200)
plt.xlabel("x", fontsize=14)
plt.ylabel("distribution", fontsize=14)
plt.axis([0, 60, 0, 350])
plt.subplot(1,2,2)
plt.hist(np.log(x), bins=200)
plt.xlabel("log(x)", fontsize=14)
plt.ylabel("distribution", fontsize=14)
plt.axis([0, 6, 0, 300])
```

**Comment by Akash0305** [comment]
Awesome

**Comment by Akash0305** [comment]
Awesome
