### ISSUE TITLE
Ch 2 page no. 61 Imputer shows DeprecationWarning

### ISSUE THREAD

**Issue by Akash0305** [ageron/handson-ml#424]
What is the alternative and how to use it ?

**Comment by ageron** [comment]
Hi @Akash0305 ,
Indeed, the deprecation warning says:

> DeprecationWarning: Class Imputer is deprecated; Imputer was deprecated in version 0.20 and will be removed in 0.22. Import impute.SimpleImputer from sklearn instead.

As the message says, you should just use `sklearn.impute.SimpleImputer` instead.
Hope this helps!
