### ISSUE TITLE
Ch 02: creating a DF based on the Imputer output

### ISSUE THREAD

**Issue by genemishchenko** [ageron/handson-ml#426]
Hi Aurelien,

You have the following code in the book and in the Jupyter note to create a transformed data frame based on the output of the Imputer (and of the StratifiedShuffleSplit before that):
`housing_tr = pd.DataFrame(X, columns=housing_num.columns)`
This is not OK, I think, because the indices are still shuffled and the above statement resets them, which will be problematic if we want to to join the numerical predictors' data back with the categories and labels.

You DO have the version of the data frame constructor call with the "index" parameter in the Jupyter note:
```
housing_tr = pd.DataFrame(X, columns=housing_num.columns,
                          index = list(housing.index.values))
```
But it comes before the version of the statement where the index is reset.

I don't think this really breaks anything, because in the note and in the book you're moving on to explaining how to build the more automated transformation pipelines where we don't have to deal with NumPy array conversions, but I just wanted to point it out.

Thank you for writing such an awesome book!

**Comment by ageron** [comment]
Hi @genemishchenko ,
Thanks a lot for your feedback. Great point. In the book & notebook, I don't use the index (as you point out), which is why I left it out, but you're right that I should probably add a note about this. I'll update the book & notebook, thanks again!
