### ISSUE TITLE
Chapter 14: Why is OutputProjectionWrapper not working with SimpleRNNCell

### ISSUE THREAD

**Issue by kusur** [ageron/handson-ml#429]
Dear @ageron 

I am trying to replicate the time series example given in the Jupyter notebook using OutputProjectionWrapper. My code is as follows:- 

```python
OutputProjectionWrapper_graph = tf.Graph()
with OutputProjectionWrapper_graph.as_default():
    X = tf.placeholder(dtype=tf.float32,shape=(None,n_steps,n_inputs))
    y = tf.placeholder(dtype=tf.float32,shape=(None,n_steps,n_outputs))
    rnn_cell = tf.contrib.rnn.OutputProjectionWrapper(tf.keras.layers.SimpleRNNCell(units=n_neurons
                                                                                    ,activation='relu'
                                                                                    ,dtype=tf.float32)
                                                      ,output_size=n_outputs)
    rnn_outputs,state = tf.keras.layers.RNN(rnn_cell,return_sequences=True,return_state=True)(X)
    loss = tf.reduce_mean(tf.square(y - rnn_outputs))
    optimizer = tf.train.AdamOptimizer(learning_rate=learning_rate)
    training_op = optimizer.minimize(loss)
    init = tf.global_variables_initializer()
    saver = tf.train.Saver()
```

I am getting the following error:- 
```python
AttributeError: 'SimpleRNNCell' object has no attribute 'zero_state'
```

However, if I substitute the code with the following value of `rnn_cell` - 
```python
rnn_cell = tf.contrib.rnn.OutputProjectionWrapper(tf.nn.rnn_cell.BasicRNNCell(num_units=n_neurons,activation=tf.nn.relu),output_size=n_outputs)
```

Then everything seems to work fine. 

The problem that I am facing is that Tensorflow says that 
```python
tf.nn.rnn_cell.BasicRNNCell
``` 
[is equivalent to](https://www.tensorflow.org/api_docs/python/tf/nn/rnn_cell/BasicRNNCell) 
```python 
tf.keras.layers.SimpleRNNCell
```
Then is there any equivalent of `zero_state` in `tf.keras.layers.SimpleRNNCell`? 

Any help would be appreciated.

Thanks

**Comment by ageron** [comment]
Hi @kusur,

Thanks for your question.

`tf.nn.rnn_cell.BasicRNNCell` offers the same functionality as `tf.keras.layers.SimpleRNNCell`, but the two are not interchangeable.

There are actually two different RNN APIs in TensorFlow 1.x: the "classic" RNN API, and the Keras RNN API. The 1st edition of my book only covers the classic RNN API (as tf.keras did not exist when I wrote the book). In TensorFlow 2, the class RNN API will be deprecated. If you plan to use TF 1.x for a long time, then you're fine, you can use either APIs. But if you plan to migrate to TF 2 anytime soon, I recommend you start migrating your code to tf.keras, as much as possible.

If you want some examples of how to build an RNN using tf.keras (which will work both in TF 1.x, and in TF 2), you can check out the notebooks for the 2nd edition of my book, especially the [RNN notebook](https://github.com/ageron/handson-ml2/blob/master/15_processing_sequences_using_rnns_and_cnns.ipynb).

Hope this helps.

**Comment by kusur** [comment]
Thanks @ageron for your help. I went through your notebook for the second edition. Surprisingly, I didn't find `OutputProjectionWrapper` there. I liked this wrapper as it simplified the code to a great extent (I don't know if using this construct is a good practice or not). So, does this mean that `tf.keras.layers.SimpleRNNCell` can't be used with `OutputProjectionWrapper`?

**Comment by ageron** [comment]
Hi @kusur ,
Great question: if you use a `Dense` layer after a recurrent layer, it will automatically be applied at each time step, which is equivalent to the `OutputProjectionWrapper` (but more efficient, as it actually runs a single matrix multiplication operation).
Hope this helps.

**Comment by kusur** [comment]
Understood! Closing the issue
