### ISSUE TITLE
Where's the method fetch_batch() used in chapter 9? 

### ISSUE THREAD

**Issue by rezacsedu** [ageron/handson-ml#43]
Hi,

I have purchased this book from Amazon. But where's the method fetch_batch() function used in chapter 9? I tried but couldn't found.

**Comment by ageron** [comment]
Hi @rezacsedu,
I tried to keep the book's code samples as concise as possible, and in a few cases I left some functions out when they did not add any important information.  In these cases you can always find the code in the corresponding Jupyter notebook in this project.  The `fetch_batch()` function is defined in cell 48 in [09_up_and_running_with_tensorflow.ipynb](https://github.com/ageron/handson-ml/blob/master/09_up_and_running_with_tensorflow.ipynb).
I hope you are enjoying the book!  :)
Hope this helps,
Aurélien
