### ISSUE TITLE
有关决策树

### ISSUE THREAD

**Issue by JerryQiang** [ageron/handson-ml#432]
1.10.6中有处泛化错写为泛华。

1.10.7.数学表达 
	图示被嵌套到```py ```中，无法显示。

1.10.7.1. 分类标准
	有个公式是信息熵的表达式，不是交叉熵。

**Comment by ageron** [comment]
I'm sorry, but I cannot read Chinese, and Google translate's translation is not accurate enough for me to answer your question:

> In 1.10.6, there is a generalization misunderstanding as pan-China.
> 
> 1.10.7. Mathematical expression
> The icon is nested inside py and cannot be displayed.
> 
> 1.10.7.1. Classification criteria
> One formula is an expression of information entropy, not cross entropy.

If anyone can read Chinese and translate to English, I would really appreciate it.
