### ISSUE TITLE
'module' object is not callable in Chapter-2 In[71]

### ISSUE THREAD

**Issue by anktkr** [ageron/handson-ml#437]
when I run the code
`    from sklearn import pipeline
    from sklearn.preprocessing import StandardScaler
    num_pipeline = pipeline([
        ('imputer',Imputer(strategy="median")),
        ('attradder',combinedattadder()),
        ('stdscalar',StandardScaler(copy=True, with_mean=True, with_std=True)),
    ])
`
I get the error

`      ----> 5     ('stdscalar',StandardScaler(copy=True, with_mean=True, with_std=True)),`

     `  TypeError: 'module' object is not callable`

How to solve this?
Thank you!

**Comment by ageron** [comment]
Hi @anktkr,

Thanks for your question.

Your pipeline import should be:

```python
from sklearn.pipeline import Pipeline
```

And then use `Pipeline` instead of `pipeline`.

Hope this helps.
