### ISSUE TITLE
PCA Leading to Increased Training Time

### ISSUE THREAD

**Issue by ndalton12** [ageron/handson-ml#44]
Hi,

I've been following the book and I really like the content so far. While going through Chapter 8, I tried the exercise (# 9) that asks you to reduce the dimensionality of the MNIST dataset and compare the training times of the original set and the reduced set on a random forest classifier. However, the reduced dataset takes significantly longer to train for me and results in much lower accuracy. However, It's certainly possible I've done something wrong. https://github.com/ndalton12/Python-Learning/blob/master/ML/Chapter8_Exercises/Chapter8_Exercises.ipynb  shows my code, which is based heavily on the examples from the chapter.

Any help or reasoning I'm missing is appreciated.

**Comment by ageron** [comment]
Hi @ndalton12 ,
As admiral Ackbar would say, it's a trap! ;-)
Reducing dimensionality sometimes reduces training time significantly, but in some cases it can actually lead to the reverse.  If you try a software regression classifier (using Scikit-Learn's `LogisticRegression` class), you will see that training gets a ×4 speedup on MNIST when using PCA.
I just added the solution to exercise 9 if you want to take a look.
Thanks for your kind words, I'm glad you are enjoying the book.
Cheers,
Aurélien

**Comment by Mauricio9** [comment]
???? mandou por engano
