### ISSUE TITLE
Cannot open TensorBoard

### ISSUE THREAD

**Issue by benech17** [ageron/handson-ml#440]
Hi !
I'm trying to open TensorBoard for my gradient descent but it doesn't work... 
I got a : 

> AttributeError: module 'tensorboard.util' has no attribute 'Retrier'

I'm on Win10 , Tensorflow (1.3.0) Tensorboard 1.13.1 ( already tried to upgrade tensorflow to 1.13.1) but still nothing....

My CMD was , like the book , 

> tensorboard --logdir tf_logs/

Don't know if it's related but my gradient descent works perfectly ...
I'm blocked on this part for 3 hours now .... HEELLPP

**Comment by ageron** [comment]
Hi @benech17 ,
Thanks for your question. It seems like it's an installation issue (multiple different versions of TensorBoard were installed).
When you get stuck on an error, I recommend search for the error message on Google: in this case, if you search for `"AttributeError: module 'tensorboard.util' has no attribute 'Retrier"`, the second result is seems like it's exactly the problem you're running into:
https://github.com/tensorflow/tensorboard/issues/2019

The solution is to uninstall all versions of tensorboard (e.g., tb-nightly and tensorboard), and then reinstall tensorboard. Also, TF 1.3.0 is really old, did you mean TF 1.13.0? If you have 1.3.0, I recommend upgrading.

Hope this helps.

**Comment by benech17** [comment]
Yes , I already search on google , naturally.. I have dowloaded TF 1.3.0 to follow exactly the book and not being disturb by a ' version - bug '

**Comment by ageron** [comment]
Thanks for your reply.  Did you try uninstalling all tensorboard version and reinstalling it?
I would recommend upgrading to TF 1.13.1: I'm not sure the latest version of tensorboard words with an old version of tensorflow.

**Comment by ageron** [comment]
Hi @benech17 ,
If the problem is fixed, could you please share what fixed it, it might help other users with the same issue.
Thanks!

**Comment by benech17** [comment]
the solution was exactly what you said. I realize it just at the moment because I didn't delete every versions of tensorboards (some was pretty well hidden)
Thanks !

**Comment by ageron** [comment]
Cool, thanks! All tensorboard packages I know of have either `tensorboard` or `tb` in their name, so the trick is to do:

```bash
python3 -m pip freeze | grep tensorboard
python3 -m pip freeze | grep tb
```

Then uninstall every one of them, then reinstall the one you want (usually `tensorboard`, or `tf-nightly` if you are using `tf-nightly*`).
