### ISSUE TITLE
Logistic Regression is just stats ?

### ISSUE THREAD

**Issue by benech17** [ageron/handson-ml#443]
Hi !
Following the iris DataSets exemples , I tried to make my first Logistic Regression. My X is the number of words in a sentence and I would like (with the help of other parameters but later) to find the probability that a sentence have to have a specific term ( named entities ). 
So in my stats I have some sentences with only 15 words that have it or sentences with 80 words that haven't. With only this parameter , it seems to be a little bit random. Not a real rule. 
That's why in my Logistic Regression , I find out a
 ````
log_reg.score(X,y) = 0.7666 
`````
 (didn't understand very well what it means )

and with this : 
````
X_new = np.linspace(20, 80,150).reshape(150,1)  #150 Sentences between 20 and 80 words 
y_proba = log_reg.predict_proba(X_new)
decision_boundary = X_new[y_proba[:, 1] >= 0.5][0]
````
I got  [68.32214765] for decision boundary with a max % of  0.57 ...

Am I doing something wrong ? Or We can justify these bad results only by the "not good enough" parameter ? 
All of this , makes me think that logistic regression is only stats (I think it's true actually, but I'm lost now )

**Comment by benech17** [comment]
it seems like it does

**Comment by ageron** [comment]
Hi @benech17 ,

Sorry for the late response, I was on vacation.
The `score()` method of a classifier returns the accuracy of the model over the given dataset. So `log_reg.score(X,y)` gives the accuracy of the `log_reg` model over the dataset `X`, `y`. In this case 76.66%. To know whether it's good or not, you have to compare this with the accuracy you would expect from a model that always predicts the most frequent class. So if only 20% of the sentences in the dataset have the named entity, then an accuracy of 76.66% is not that bad. However, if 76.66% of the sentences have the named entity, then the model isn't useful at all.
You're doing things right, technically, but I wouldn't expect too much accuracy from a model that only gets the number of words in a sentence as an input.
And yes, logistic regression is part of stats-land. :)
