### ISSUE TITLE
Chapter 7 mistake in Gradient Boosting with Early stopping

### ISSUE THREAD

**Issue by 123385918** [ageron/handson-ml#445]
in cell `In[44]` ,using `GradientBoostingRegressor`'s method `staged_predict()`

```python
bst_n_estimators = np.argmin(errors)
```

is not the best, because `np.argmin()` start from 0.
it should be
```python
bst_n_estimators = np.argmin(errors)+1.
```

the result in cell `In[47]` can prove.

![微信截图_20190606094818](https://user-images.githubusercontent.com/45360163/59001160-3e899800-8840-11e9-9626-273fa987abb0.png)

**Comment by ageron** [comment]
Good catch, thanks! :)
I'll fix this now.

**Comment by 123385918** [comment]
Thank you for responsing! but i have to say, _In[460_ has to run again because the plot still means 55 trees is the best.
