### ISSUE TITLE
FileNotFoundError: in Chapter 2 loading the data

### ISSUE THREAD

**Issue by FerCalatayud** [ageron/handson-ml#448]
![image](https://user-images.githubusercontent.com/25761314/59557583-0c480b00-8fa3-11e9-8ee4-9f502f989c75.png)

This is my exact code. This is the error I get:

FileNotFoundError: [Errno 2] File b'datasets/housing\\housing.csv' does not exist: b'datasets/housing\\housing.csv'

I've tried every PATH combination and nothing. I really don't know what is the problem.
The book is awesome, but I can't continue because of this small error.

**Comment by ageron** [comment]
Hi @FerCalatayud ,
Thanks for your question. I think you need to fix the definition of `HOUSING_PATH`. This is what is should be (see the notebook):

```python
HOUSING_PATH = os.path.join("datasets", "housing")
```

You are probably using Windows, which separates file paths with `\` (while Linux and MacOSX use `/`). To make the code portable, I used `os.path.join("datasets", "housing")`, which will return `datasets\housing` on Windows, and `datasets/housing` on Linux and MacOSX.

However, URLs use `/` no matter which system you are using. This is why the `DOWNLOAD_ROOT` and `HOUSING_URL` use `/`.

If it still fails after fixing this, make sure you are using Python 3, and that the file housing.csv is located in the `datasets\housing` directory in the same project as the Jupyter notebook.

Hope this helps.

**Comment by FerCalatayud** [comment]
Hi, thanks for the fast response Ageron.

It still doesn't work. You were correct, I'm using windows with python 3 on the jupyter notebook. 

With this URL I'm downloading the data from your repository on GitHub, right? so the housing.csv is located at datasets\housing, and not at the same directory as my jupyter notebook.

Now that I think about it, I could load the housing.csv and housing.tgz from my computer, right?

**Comment by FerCalatayud** [comment]
I changed the URL to my path where I have the data set on my PC, and it worked.

But the question remains, why does the URL doesn't work? I've tried everything, and it gives me either the error that I posted before or an "ERROR 404".

I even print the path before accessing it with ".read_csv()", click it and directs me to the right web page, but the code outputs an "ERROR 404"

**Comment by ageron** [comment]
Hi @FerCalatayud ,
There are two steps:
1. `fetch_housing_data()` downloads the data from the URL on my github repo (the URL must contain only slashes `/`)
2. `load_housing_data()` loads the CSV file that was just downloaded (the path must contain either slashes or backslashes depending on the O.S.).

I believe there were two problems in your initial code:
1. your code defines the `fetch_housing_data()` function but it never calls it. You should call `fetch_housing_data_()` before you call `load_housing_data()`.
2. your code used a mix of slashes and backslashes for the file path used by `load_housing_data()`.

Hope this helps.

**Comment by PythonUser1981** [comment]
Basically the correct code goes like this:

import os
import tarfile
from six.moves import urllib

DOWNLOAD_ROOT = "https://raw.githubusercontent.com/ageron/handson-ml/master/"
HOUSING_PATH = os.path.join("datasets", "housing")
HOUSING_URL = DOWNLOAD_ROOT + "datasets/housing/housing.tgz"

def fetch_housing_data(housing_url=HOUSING_URL, housing_path=HOUSING_PATH):
    if not os.path.isdir(housing_path):
        os.makedirs(housing_path)
    tgz_path = os.path.join(housing_path, "housing.tgz")
    urllib.request.urlretrieve(housing_url, tgz_path)
    housing_tgz = tarfile.open(tgz_path)
    housing_tgz.extractall(path=housing_path)
    housing_tgz.close()
    
fetch_housing_data()


import pandas as pd

def load_housing_data(housing_path=HOUSING_PATH):
    csv_path = os.path.join(housing_path, "housing.csv")
    return pd.read_csv(csv_path)



housing = load_housing_data()
housing.head()

**Comment by keyntaur** [comment]
> ### Basically the correct code goes like this:
> ### Make sure you indent the functions properly
> import os
> import tarfile
> from six.moves import urllib
> 
> DOWNLOAD_ROOT = "https://raw.githubusercontent.com/ageron/handson-ml/master/"
> HOUSING_PATH = os.path.join("datasets", "housing")
> HOUSING_URL = DOWNLOAD_ROOT + "datasets/housing/housing.tgz"
> 
> def fetch_housing_data(housing_url=HOUSING_URL, housing_path=HOUSING_PATH):
> if not os.path.isdir(housing_path):
> os.makedirs(housing_path)
> tgz_path = os.path.join(housing_path, "housing.tgz")
> urllib.request.urlretrieve(housing_url, tgz_path)
> housing_tgz = tarfile.open(tgz_path)
> housing_tgz.extractall(path=housing_path)
> housing_tgz.close()
> 
> fetch_housing_data()
> 
> import pandas as pd
> 
> def load_housing_data(housing_path=HOUSING_PATH):
> csv_path = os.path.join(housing_path, "housing.csv")
> return pd.read_csv(csv_path)
> 
> housing = load_housing_data()
> housing.head()

This helped me. The book implicitly indicates to call **fetch_housing_data()** in the text while your eyes follow what the code example is the book.

**Comment by ageron** [comment]
Thanks for your feedback @keyntaur . I've added an explicit call to `fetch_housing_data()` in the code example, so there will be less confusion for future readers. 👍

**Comment by MahsumKocabey** [comment]
> Hi @FerCalatayud ,
> Thanks for your question. I think you need to fix the definition of `HOUSING_PATH`. This is what is should be (see the notebook):
> 
> ```python
> HOUSING_PATH = os.path.join("datasets", "housing")
> ```
> 
> You are probably using Windows, which separates file paths with `\` (while Linux and MacOSX use `/`). To make the code portable, I used `os.path.join("datasets", "housing")`, which will return `datasets\housing` on Windows, and `datasets/housing` on Linux and MacOSX.
> 
> However, URLs use `/` no matter which system you are using. This is why the `DOWNLOAD_ROOT` and `HOUSING_URL` use `/`.
> 
> If it still fails after fixing this, make sure you are using Python 3, and that the file housing.csv is located in the `datasets\housing` directory in the same project as the Jupyter notebook.
> 
> Hope this helps.

The solution is:
Go to terminal press control+c to shut the kernel and write to the terminal:

$ sudo /Applications/Python\ 3.9/Install\ Certificates.command

Then re run the by writing "jupyter notebook". Thats it guys!
