### ISSUE TITLE
Chapter 2

### ISSUE THREAD

**Issue by jjf1218** [ageron/handson-ml#449]
Hi there,

I have not seen this issue in the issues section, and I was wondering if it has happened before. I'm currently trying to get the test data set, and I currently have this exact code from the book written:

```python
from sklearn.model_selection import StratifiedShuffleSplit

split = StratifiedShuffleSplit(n_splits=1, test_size=0.2, random_state=42)
for train_index, test_index in split.split(housing, housing["income_cat"]):
    strat_train_set = housing.loc[train_index]
    strat_test_set = housing.loc[test_index]
```

However, I keep getting the following error:

```
TypeError: object of type 'CategoricalDtype' has no len()
```
The full error is below:

![image](https://user-images.githubusercontent.com/36773696/59616900-55a77000-90f3-11e9-9272-ebd0dc9e2ca6.png)

I've checed plenty of times but I can't find any typos, nor can I figure out if something in a prior cell block is preventing this. I'm running a Jupyter notebook on a Windows machine (I have Anaconda installed). All of the other code blocks up until this point seem to work fine.

Loving the book btw!

Thanks,
Joey

**Comment by ageron** [comment]
Hi @jjf1218 ,

I'm really glad you're enjoying the book!  :)

You probably have Scikit-Learn 0.20.1 which had a bug, see issue #378 (when you search for issues on github, make sure to search for both open and closed issues). You just need to upgrade Scikit-Learn to the latest version, and everything should run fine.

Hope this helps,
Aurélien

**Comment by jjf1218** [comment]
Thanks for the reference! It now seems to be working.

Cheers!
Joey
