### ISSUE TITLE
Typo - Chapter 2 - Better evaluation using code-validation

### ISSUE THREAD

**Issue by etudor** [ageron/handson-ml#45]
There's a typo in the book: page 69. The code is presented as:

```
from sklearn.model_selection import cross_val_score
scores = cross_val_score(tree_reg, housing_prepared, housing_labels, scoring="neg_mean_squared_error", cv=10)
rmse_scores = np.sqrt(-scores) ### here is the typo, the variable should have been names: tree_rmse_scores
```
while on the second page, we have:
```
display_scores(tree_rmse_scores)
```
Variable: tree_rmse_scores does not exists. 

On Github the code is correct: [ch2 code project: In [79]](https://github.com/ageron/handson-ml/blob/master/02_end_to_end_machine_learning_project.ipynb)

![20170624_172225](https://user-images.githubusercontent.com/5428842/27510107-2be63236-5902-11e7-9a77-f6feb25208dd.jpg)

**Comment by ageron** [comment]
Hi @etudor ,
Thanks for your feedback.  Indeed this error exists in the first paper version.  I fixed it a few weeks ago, and the latest printed version is okay now (as well as the digital versions).
I hope you are enjoying the book!
Cheers,
Aurélien
