### ISSUE TITLE
Chapter 2: ReadError: file could not be opened successfully

### ISSUE THREAD

**Issue by ajpinel** [ageron/handson-ml#450]
Hello - I'm having problems decompressing the housing.tgz file with tar.  
I'm getting the following error: "ReadError: file could not be opened successfully"
Not sure why it's having problems decompressing the file.  I've copied/pasted from the notebook.  I'm on Windows.  Any help is greatly appreciated.

Below is the code and below that is the error message.

import os
import tarfile
from six.moves import urllib

DOWNLOAD_ROOT = "https://github.com/ageron/handson-ml/tree/master/"
HOUSING_PATH = "datasets/housing"
HOUSING_URL = DOWNLOAD_ROOT + HOUSING_PATH + "/housing.tgz"

def fetch_housing_data(housing_url=HOUSING_URL, housing_path=HOUSING_PATH):
    if not os.path.isdir(housing_path):
        os.makedirs(housing_path)
    tgz_path = os.path.join(housing_path, "housing.tgz")
    urllib.request.urlretrieve(housing_url, tgz_path)
    housing_tgz = tarfile.open(tgz_path)
    housing_tgz.extractall(path=housing_path)
    housing_tgz.close()

fetch_housing_data()

---------------------------------------------------------------------------
ReadError                                 Traceback (most recent call last)
<ipython-input-67-bd66b1fe6daf> in <module>
----> 1 fetch_housing_data()

<ipython-input-66-737bb9bdd27e> in fetch_housing_data(housing_url, housing_path)
     12     tgz_path = os.path.join(housing_path, "housing.tgz")
     13     urllib.request.urlretrieve(housing_url, tgz_path)
---> 14     housing_tgz = tarfile.open(tgz_path)
     15     housing_tgz.extractall(path=housing_path)
     16     housing_tgz.close()

~\Anaconda3\lib\tarfile.py in open(cls, name, mode, fileobj, bufsize, **kwargs)
   1576                         fileobj.seek(saved_pos)
   1577                     continue
-> 1578             raise ReadError("file could not be opened successfully")
   1579 
   1580         elif ":" in mode:

ReadError: file could not be opened successfully

**Comment by ageron** [comment]
Hi @ajpinel ,

Thanks for your question.  Please use the same code as in the notebook and the book:

```python
import os
import tarfile
from six.moves import urllib

DOWNLOAD_ROOT = "https://raw.githubusercontent.com/ageron/handson-ml/master/"
HOUSING_PATH = os.path.join("datasets", "housing")
HOUSING_URL = DOWNLOAD_ROOT + "datasets/housing/housing.tgz"

def fetch_housing_data(housing_url=HOUSING_URL, housing_path=HOUSING_PATH):
    if not os.path.isdir(housing_path):
        os.makedirs(housing_path)
    tgz_path = os.path.join(housing_path, "housing.tgz")
    urllib.request.urlretrieve(housing_url, tgz_path)
    housing_tgz = tarfile.open(tgz_path)
    housing_tgz.extractall(path=housing_path)
    housing_tgz.close()

fetch_housing_data()
```

Notice the differences (different HOUSING_URL, different HOUSING_PATH, etc.)

Hope this helps

**Comment by ajpinel** [comment]
Thanks, Aurélien.  That worked!

**Comment by bmahal268** [comment]
Hi Aurélien,

The code is identical to the one in the notebook, still getting the same error. Please help.

import os
import tarfile
from six.moves import urllib

DOWNLOAD_ROOT = "https://github.com/ageron/handson-ml/tree/master/"
HOUSING_PATH = os.path.join("datasets", "housing")
HOUSING_URL = DOWNLOAD_ROOT + "datasets/housing/housing.tgz"

def fetch_housing_data(housing_url=HOUSING_URL, housing_path=HOUSING_PATH):
    if not os.path.isdir(housing_path):
        os.makedirs(housing_path)
    tgz_path = os.path.join(housing_path, "housing.tgz")
    urllib.request.urlretrieve(housing_url, tgz_path)
    housing_tgz = tarfile.open(tgz_path)
    housing_tgz.extractall(path=housing_path)
    housing_tgz.close()

fetch_housing_data()

ReadError                                 Traceback (most recent call last)
<ipython-input-16-bd66b1fe6daf> in <module>()
----> 1 fetch_housing_data()

<ipython-input-4-e48f1026cdd8> in fetch_housing_data(housing_url, housing_path)
     12     tgz_path = os.path.join(housing_path, "housing.tgz")
     13     urllib.request.urlretrieve(housing_url, tgz_path)
---> 14     housing_tgz = tarfile.open(tgz_path)
     15     housing_tgz.extractall(path=housing_path)
     16     housing_tgz.close()

F:\Machine learning\Anaconda\lib\tarfile.py in open(cls, name, mode, fileobj, bufsize, **kwargs)
   1572                         fileobj.seek(saved_pos)
   1573                     continue
-> 1574             raise ReadError("file could not be opened successfully")
   1575 
   1576         elif ":" in mode:

ReadError: file could not be opened successfully

**Comment by ageron** [comment]
Hi @bmahal268 ,

Your code is not the same as in the book and the notebook. You are using:

```python
DOWNLOAD_ROOT = "https://github.com/ageron/handson-ml/tree/master/"
```

It should be:

```python
DOWNLOAD_ROOT = "https://raw.githubusercontent.com/ageron/handson-ml/master/"
```

Your version does not download the tarball, it downloads the HTML page that describes the tarball, this is why `tarfile.open()` fails.

Hope this helps.

**Comment by bmahal268** [comment]
Thank you very much Aurélien. That worked.

**Comment by viariasv** [comment]
the same thing happens with me but with another extension, the easy solution for zip files is:

```python
import zipfile

def fetch_bank_data(banking_url=BANK_URL, banking_path=DATA_PATH):
    if not os.path.isdir(banking_path):
        os.makedirs(banking_path)
    zip_path = os.path.join(banking_path, "bank.zip")
    urllib.request.urlretrieve(banking_url, zip_path)
    
    with zipfile.ZipFile(zip_path, 'r') as banking_zip:
        banking_zip.extractall(banking_path)

    banking_zip.close()
    
fetch_bank_data()
```

**Comment by Mapna** [comment]
Hi
When I use the exact link as mentioned in the code I get an HTTP Bad Request error:

400 Client Error: Bad Request for url: https://raw.githubusercontent.com/ageron/handson-ml/master/

Anyone else seeing this issue?

**Comment by AyEnEss** [comment]
Can you post your entire code please?

**Comment by Mapna** [comment]
Please find code below along with the error at the bottom:

import bs4,requests,lxml,re,urllib.request,tarfile


url_root="https://raw.githubusercontent.com/ageron/handson-ml/master/"
datafiles = '/datasets/housing/housing.tgz'
#url = url_root + datafiles
res = requests.get(url_root)
res.raise_for_status()

print(res.raise_for_status())

file='housing.tgz'
file_path = 'C:\\ML\\sklearn_tensorflow\\chapter2\\'
urllib.request.urlretrieve(url_root+datafiles,file_path+file )

print(file_path+file)
housing_tgz = tarfile.open(file_path+file, 'r')
housing_tgz.extractall(filepath)
housing_tgz.close()

-------------
---------------------------------------------------------------------------
HTTPError                                 Traceback (most recent call last)
<ipython-input-3-128ee11398d2> in <module>
      6 #url = url_root + datafiles
      7 res = requests.get(url_root)
----> 8 res.raise_for_status()
      9 
     10 print(res.raise_for_status())

~\Anaconda3\lib\site-packages\requests\models.py in raise_for_status(self)
    938 
    939         if http_error_msg:
--> 940             raise HTTPError(http_error_msg, response=self)
    941 
    942     def close(self):

HTTPError: 400 Client Error: Bad Request for url: https://raw.githubusercontent.com/ageron/handson-ml/master/

**Comment by AyEnEss** [comment]
for reference, here is the code I used which works for me
```
import tarfile
from six.moves import urllib
DOWNLOAD_ROOT = "https://raw.githubusercontent.com/ageron/handson-ml/master/" HOUSING_PATH = os.path.join("datasets", "housing") HOUSING_URL = DOWNLOAD_ROOT + "datasets/housing/housing.tgz"

def fetch_housing_data(housing_url=HOUSING_URL, housing_path=HOUSING_PATH): 
    '''Downloads the file at the given path'''
   
    os.makedirs(housing_path, exist_ok=True)
    tgz_path = os.path.join(housing_path, "housing.tgz")
    urllib.request.urlretrieve(housing_url, tgz_path)
    housing_tgz = tarfile.open(tgz_path)
    housing_tgz.extractall(path=housing_path)
    housing_tgz.close()
```
```

**Comment by Mapna** [comment]
ok I found the bug: the issue was with 
>>res = requests.get(url_root)

which should actually be (url_root+datafiles). The urlretrieve request part works fine and was able to download the file.  Thanks for your quick help.

**Comment by Ani-Samuh** [comment]
I am using the latest code as you have mentioned. I actually figured out the changes to the URL by going to your GitHub repository and locating the actual location of the housing.tgz file. The code is now downloading the file, but I still get an error saying "file could not be opened successfully". Basically it's downloading but not extracting.

**Comment by allifizzuddin89** [comment]
The file housing.tgz cannot be opened. Then I was decompressing it using peazip, it requires password. Please kindly share the password if available. I'm also failed to find it in your book. Thank you.

**Comment by EdwardVitor** [comment]
> Hi
> When I use the exact link as mentioned in the code I get an HTTP Bad Request error:
> 
> 400 Client Error: Bad Request for url: https://raw.githubusercontent.com/ageron/handson-ml/master/
> 
> Anyone else seeing this issue?

I encounter the same situation as you, how did you solve it

**Comment by thsohn** [comment]
import os
import tarfile
from urllib.request import urlretrieve
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np

DOWNLOAD_ROOT = "https://raw.githubusercontent.com/ageron/handson-ml2/master/"
HOUSING_PATH = os.path.join('datasets', 'housing')
HOUSING_URL = DOWNLOAD_ROOT + "datasets/housing/housing.tgz"


def fetch_housing_data(housing_url=HOUSING_URL, housing_path=HOUSING_PATH):
    os.makedirs(housing_path, exist_ok=True)
    tgz_path = os.path.join(housing_path, "housing.tgz")
    urlretrieve(housing_url, tgz_path)
    housing_tgz = tarfile.open(tgz_path)
    housing_tgz.extractall(path=housing_path)
    housing_tgz.close()


above code works for me..

**Comment by Schnomann** [comment]
simply change the path to "https://github.com/ageron/handson-ml2/blob/master/datasets/housing/housing.tgz?raw=true"

**Comment by ageron** [comment]
When in doubt, please check the Colab notebooks at https://homl.info/colab1 (1st edition), https://homl.info/colab2 (2nd edition), or https://homl.info/colab3 (3rd edition). All three should work fine, but of course I recommend the latest.

The 3rd edition code is this, I've tested it a lot, it should work fine:

```python
from pathlib import Path
import pandas as pd
import tarfile
import urllib.request

def load_housing_data():
    tarball_path = Path("datasets/housing.tgz")
    if not tarball_path.is_file():
        Path("datasets").mkdir(parents=True, exist_ok=True)
        url = "https://github.com/ageron/data/raw/main/housing.tgz"
        urllib.request.urlretrieve(url, tarball_path)
        with tarfile.open(tarball_path) as housing_tarball:
            housing_tarball.extractall(path="datasets")
    return pd.read_csv(Path("datasets/housing/housing.csv"))

housing = load_housing_data()
```

* If you still get an error, please delete `datasets/housing.tgz` and `datasets/housing`, and try again.
* If you still get an error after that, please check your Internet connection and/or try again later.
* If you get an SSL error, and you are running on MacOS, you probably need to install the SSL certificates (see this [StackOverflow question](https://stackoverflow.com/questions/27835619/urllib-and-ssl-certificate-verify-failed-error)). If you downloaded Python from the official website, then run /Applications/Python\ 3.8/Install\ Certificates.command in a terminal (change 3.8 to whatever version you installed). If you installed Python using MacPorts, run `sudo port install curl-ca-bundle` in a terminal.

Hope this helps!

**Comment by JiniNH** [comment]
Thank you. The 3rd edition was a big help to me.
