### ISSUE TITLE
Error when opening math_linear_algebra file

### ISSUE THREAD

**Issue by ajpinel** [ageron/handson-ml#453]
I receive an error (see below) when opening the file: **math_linear_algebra.ipynb** on Jupyter Notebook.  I'm downloading the file by right-clicking on "Save as link" from here:
https://github.com/ageron/handson-ml/blob/master/math_linear_algebra.ipynb
Any help is greatly appreciated.

**Error:**
Unreadable Notebook: C:\Users\apinel\Hands On Machine Learning Book\math_linear_algebra.ipynb NotJSONError("Notebook does not appear to be JSON: '\\n\\n\\n\\n\\n\\n<!DOCTYPE html>\\n<html lang...")

**Comment by IvanKuchin** [comment]
Try to clone whole project to local folder on your laptop and find the file you are interested in your local copy.

**Comment by ajpinel** [comment]
> Try to clone whole project to local folder on your laptop and find the file you are interested in your local copy.

Thanks, Ivan.  That worked.
