### ISSUE TITLE
MNIST MemoryError

### ISSUE THREAD

**Issue by i-taketoshi** [ageron/handson-ml#457]
i am getting the following error 03_classification.ipynb:
What am I missing?
Please help me.
```
try:
    from sklearn.datasets import fetch_openml
    mnist = fetch_openml('mnist_784', version=1, cache=True)
    mnist.target = mnist.target.astype(np.int8) # fetch_openml() returns targets as strings
    sort_by_target(mnist) # fetch_openml() returns an unsorted dataset
except ImportError:
    from sklearn.datasets import fetch_mldata
    mnist = fetch_mldata('MNIST original')
mnist["data"], mnist["target"]
```

Error message
```
---------------------------------------------------------------------------
MemoryError                               Traceback (most recent call last)
<ipython-input-2-3f28d0b20c3d> in <module>()
      1 try:
      2     from sklearn.datasets import fetch_openml
----> 3     mnist = fetch_openml('mnist_784', version=1, cache=True)
      4     mnist.target = mnist.target.astype(np.int8) # fetch_openml() returns targets as strings
      5     sort_by_target(mnist) # fetch_openml() returns an unsorted dataset

C:\Users\taketoshi\Anaconda3\lib\site-packages\sklearn\datasets\openml.py in fetch_openml(name, version, data_id, data_home, target_column, cache, return_X_y)
    641                           k in data_columns + target_column}
    642 
--> 643     X, y = _convert_arff_data(arff['data'], col_slice_x, col_slice_y, shape)
    644 
    645     is_classification = {col_name in nominal_attributes

C:\Users\taketoshi\Anaconda3\lib\site-packages\sklearn\datasets\openml.py in _convert_arff_data(arff_data, col_slice_x, col_slice_y, shape)
    246                            dtype='float64', count=count)
    247         data = data.reshape(*shape)
--> 248         X = data[:, col_slice_x]
    249         y = data[:, col_slice_y]
    250         return X, y

MemoryError: 
```

## Setup Details
- numpy 1.16.4
- sklearn 0.21.2
- windows10 32bit memory 4gb

**Comment by hduwza** [comment]
Same problem. Have you solve it?

**Comment by ageron** [comment]
Thanks @i-taketoshi for your feedback. Indeed, the error says that there's not enough RAM to load the MNIST dataset. It's a fairly small dataset, but loading it seems to use much more RAM than the size of the dataset, for some reason (perhaps it's not stored in a very efficient way, which would also explain why it takes so long to load). I'm afraid the only solution is ensuring that your machine has enough RAM. For that, start by closing as many programs as you can, and also close tabs in your browser. Look at your system's RAM usage to see if a program is eating up all the RAM. Then try again.
Hope this helps.

**Comment by Sudhir-Goswami** [comment]
> i am getting the following error 03_classification.ipynb: What am I missing? Please help me.
> 
> ```
> try:
>     from sklearn.datasets import fetch_openml
>     mnist = fetch_openml('mnist_784', version=1, cache=True)
>     mnist.target = mnist.target.astype(np.int8) # fetch_openml() returns targets as strings
>     sort_by_target(mnist) # fetch_openml() returns an unsorted dataset
> except ImportError:
>     from sklearn.datasets import fetch_mldata
>     mnist = fetch_mldata('MNIST original')
> mnist["data"], mnist["target"]
> ```
> 
> Error message
> 
> ```
> ---------------------------------------------------------------------------
> MemoryError                               Traceback (most recent call last)
> <ipython-input-2-3f28d0b20c3d> in <module>()
>       1 try:
>       2     from sklearn.datasets import fetch_openml
> ----> 3     mnist = fetch_openml('mnist_784', version=1, cache=True)
>       4     mnist.target = mnist.target.astype(np.int8) # fetch_openml() returns targets as strings
>       5     sort_by_target(mnist) # fetch_openml() returns an unsorted dataset
> 
> C:\Users\taketoshi\Anaconda3\lib\site-packages\sklearn\datasets\openml.py in fetch_openml(name, version, data_id, data_home, target_column, cache, return_X_y)
>     641                           k in data_columns + target_column}
>     642 
> --> 643     X, y = _convert_arff_data(arff['data'], col_slice_x, col_slice_y, shape)
>     644 
>     645     is_classification = {col_name in nominal_attributes
> 
> C:\Users\taketoshi\Anaconda3\lib\site-packages\sklearn\datasets\openml.py in _convert_arff_data(arff_data, col_slice_x, col_slice_y, shape)
>     246                            dtype='float64', count=count)
>     247         data = data.reshape(*shape)
> --> 248         X = data[:, col_slice_x]
>     249         y = data[:, col_slice_y]
>     250         return X, y
> 
> MemoryError: 
> ```
> 
> ## Setup Details
> * numpy 1.16.4
> * sklearn 0.21.2
> * windows10 32bit memory 4gb
@i-taketoshi 
same issue occurred with me with windows10 with 8GB of RAM and 32-bit Python but it has been resolved when run on the same machine with 64-bit python.

**Comment by Sudhir-Goswami** [comment]
@i-taketoshi
same issue occurred with me on windows10 with 8GB of RAM and 32-bit Python but it has been resolved when run on the same machine with 64-bit python.
