### ISSUE TITLE
Ch.2, Codes for Exercise

### ISSUE THREAD

**Issue by MitchIwata** [ageron/handson-ml#463]
Hello,
I found the code lines below 102 is not shown.  How/where can I get/see the example answer codes for the exercises on p.79? 
Thank you,

Mitch

**Comment by hduwza** [comment]
Have you found a solution?

**Comment by hduwza** [comment]
you can find the solution to exercises on this website: https://www.cnblogs.com/yangxiaoling/p/10154745.html

**Comment by MitchIwata** [comment]
Thanks!  I can see the solutions for Exercise 1-3 on the link you provided.  Could you tell me where I can get the solutions for exercise 4 & 5 as well?

**Comment by ageron** [comment]
It seems that github has some bugs, it does not display long notebooks properly, it just truncates the end. It's really weird, I contacted their support team, I'm hoping they'll fix it asap.
In the meantime, please [visualize the notebook using jupyter.org's viewer](https://nbviewer.jupyter.org/github/ageron/handson-ml/blob/master/index.ipynb), or use Colab, or open the notebook locally on your machine.

**Comment by MitchIwata** [comment]
Awesome.  Appreciate your help.  I hope the issue on github will be solved soon.
