### ISSUE TITLE
cannot import name 'awesome_cossim_topn' from 'sparse_dot_topn' (unknown location)

### ISSUE THREAD

**Issue by vhrika3** [ageron/handson-ml#465]
after installation of  sparse_dot_topn  package in python by anaconda prompt received below error message. please help me to resolve the issue.

from sparse_dot_topn import awesome_cossim_topn

ImportError: cannot import name 'awesome_cossim_topn' from 'sparse_dot_topn' (unknown location)

**Comment by ageron** [comment]
Hi @vhrika3 ,
I'm afraid I can't help you, I never used this package, you should file an issue to the right github repo (I'm guessing https://github.com/ing-bank/sparse_dot_topn).
