### ISSUE TITLE
Chapter 5: Calculating support vectors for LinearSVC throws an Attribute Error

### ISSUE THREAD

**Issue by amansingh9097** [ageron/handson-ml#468]
When calculating the support vectors using your hack for getting the support vectors for LinearSVC, I'm getting an attribute error when assigning the new calculated values back to the `intercept_` and `coef_` parameters.

In your notebook on Support Vector Machines (Chapter 5 in book)
in the following code:
```python
# Convert to unscaled parameters
b1 = svm_clf1.decision_function([-scaler.mean_ / scaler.scale_])
b2 = svm_clf2.decision_function([-scaler.mean_ / scaler.scale_])
w1 = svm_clf1.coef_[0] / scaler.scale_
w2 = svm_clf2.coef_[0] / scaler.scale_
svm_clf1.intercept_ = np.array([b1])
svm_clf2.intercept_ = np.array([b2])
svm_clf1.coef_ = np.array([w1])
svm_clf2.coef_ = np.array([w2])

# Find support vectors (LinearSVC does not do this automatically)
t = y * 2 - 1
support_vectors_idx1 = (t * (X.dot(w1) + b1) < 1).ravel()
support_vectors_idx2 = (t * (X.dot(w2) + b2) < 1).ravel()
svm_clf1.support_vectors_ = X[support_vectors_idx1]
svm_clf2.support_vectors_ = X[support_vectors_idx2]
```
I'm getting an error that says,
```
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-41-c8bdec78f479> in <module>
      8 svm_clf1.intercept_ = np.array([b1])
      9 svm_clf2.intercept_ = np.array([b2])
---> 10 svm_clf1.coef_ = np.array([w1])
     11 svm_clf2.coef_ = np.array([w2])
     12 
AttributeError: can't set attribute
```

Is there any other work around, because this one doesn't seem to work now or could it be that some functionality has changed over time with Scikit Learn? Please help.

Regards,
Aman Singh

**Comment by ageron** [comment]
Hi @amansingh9097 ,
Thanks for your feedback. That's odd, I just tried setting `coef_` on a `LinearSVC`, and it works fine.

Which version of Scikit-Learn, NumPy and Python are you using?

**Comment by amansingh9097** [comment]
Hi @ageron 

I'm using `Python version 3.7` and 
```power-shell
$> pip freeze | findstr -i "scikit pandas numpy"
numpy==1.15.4
numpydoc==0.8.0
pandas==0.25.0
scikit-image==0.14.1
scikit-learn==0.20.1
```

**Comment by ageron** [comment]
Hi @amansingh9097 ,
I tried to reproduce this issue using Scikit-Learn 0.20.1 and python 3.7, but everything worked fine. Could you upgrade your libraries to the latest versions, and provide a minimal code example that fails, along with the full stacktrace?
Thanks!
