### ISSUE TITLE
ImportError: cannot import name 'awGA' from 'awGA' (unknown location)

### ISSUE THREAD

**Issue by wilson209** [ageron/handson-ml#471]
安装了geatpy 库后
运行import geatpy as ga 
就显示ImportError: cannot import name 'awGA' from 'awGA' (unknown location)
有什么解决方法

**Comment by ageron** [comment]
Hi @wilson209 ,
Please post this question to geatpy, my book and Jupyter notebooks do not use this library.
https://github.com/geatpy-dev/geatpy
Cheers

**Comment by wilson209** [comment]
> 
> 
> Hi @wilson209 ,
> Please post this question to geatpy, my book and Jupyter notebooks do not use this library.
> https://github.com/geatpy-dev/geatpy
> Cheers

thanks,I have found where my question is in https://github.com/geatpy-dev/geatpy
