### ISSUE TITLE
Chapter 8: Agglomerative Clustering

### ISSUE THREAD

**Issue by qy-yang** [ageron/handson-ml#474]
Hi Ageron, thanks for the book and notebook. It's awesome to read it. 

I have problems to understand the 'children_' attribute of AgglomerativeClustering. It is not straightforward in the official docs as well. Is it possible to help me with this?

By calling `agg.children_`, it returns 
> array([[0, 1],
       [2, 3],
       [4, 5]])
How should I understand the numbers in the array?

Thanks a lot!

**Comment by ageron** [comment]
Hi @qy-yang ,
Sorry for the late response.
Here's the doc for the `children_` attribute:

> The children of each non-leaf node. Values less than n_samples correspond to leaves of the tree which are the original samples. A node i greater than or equal to `n_samples` is a non-leaf node and has children `children_[i - n_samples]`. Alternatively at the i-th iteration, `children[i][0]` and `children[i][1]` are merged to form node `n_samples + i`

So in your example:
* the first non-leaf node has 2 children: nodes 0 and 1.
* the second non-leaf node has 2 children: nodes 2 and 3
* the third non-leaf node has 2 children: nodes 4 and 5.

Assuming there were just 4 samples in the dataset (nodes 0, 1, 2, 3), the algorithm first created the non-leaf node 4, parent of nodes 0 and 1. Then it created the non-leaf node 5, parent of nodes 2 and 3. And finally, it created the non-leaf node 6, parent of the (non-leaf) nodes 4 and 5. The tree looks like this:

* node 6
  * node 4
    * node 0
    * node 1
  * node 5
    * node 2
    * node 3

Hope this helps!

**Comment by qy-yang** [comment]
Hi @ageron , thanks for the explanation. That's clear to me now.
