### ISSUE TITLE
Chapter 2-Issue saving figures

### ISSUE THREAD

**Issue by sebassilverac** [ageron/handson-ml#485]
Hi Aurelien, really enjoying your book a lot.
I have been running across this issue with my code. In the book, you have the following block of code:
`housing.plot(kind="scatter", x="longitude", y="latitude", alpha=0.4,
    s=housing["population"]/100, label="population", figsize=(10,7),
    c="median_house_value", cmap=plt.get_cmap("jet"), colorbar=True,
    sharex=False)
plt.legend()
save_fig("housing_prices_scatterplot")`

whenever I type this in however, I get the following error message:

FileNotFoundError: [Errno 2] No such file or directory: '.\\images\\fundamentals\\housing_prices_scatterplot.png'

I dont know where I could have messed up in my code because I cant seem to figure out how to create this directory.

Thank you for your help

**Comment by ageron** [comment]
Hi @sebassilverac ,

Thanks for your kind message!

The simplest solution is to comment out the `save_fig()` line: all it does is save the figure, so unless you need the image file, you can safely ignore this line.

However, if you really want this `save_fig()` command to work, you just need to have an `.\images\fundamentals` directory. It's part of the `handson-ml` project, so if you cloned this project, you just need to make sure that you start the Jupyter server from the `handson-ml` directory.

Alternatively, you can just create this directory by running the following code:

```python
import os
os.makedirs(os.path.join("images", "fundamentals"))
```

After that, the `save_fig()` command should work fine.

Hope this helps!

**Comment by sebassilverac** [comment]
Thank you for the quick response. Your suggestion worked perfectly. 
Again, really enjoying this book. very thorough and very informative. I look forward to reading the rest. 
Cheers
