### ISSUE TITLE
Ridge Regression

### ISSUE THREAD

**Issue by kasrahabib** [ageron/handson-ml#487]
First of all, I would like to thank for making such a beautiful ML book.
I have a problem with understanding the formula for Ridge Regression. I did not get the part about dividing lambda by 2; is it something to cancel out the power after the first derivative is taken.
And secondly, this question is a bit general why are we adding the regularization part instead of subtracting or something else; ain't adding make the error bigger.

Finally, in Ridge regression, it is written that “If we define w as the vector of feature weights (θ1 to θn), then the regularization term is simply equal to ½(∥ w ∥2)2, where ∥ · ∥2 represents the ℓ2 norm of the weight vector.12 For Gradient Descent, just add αw to the MSE gradient vector”

based on what I get from the paragraph; I edited Chapter 4. ipython notebook code for Gradient Descent as follow: (is it correct or not)

```python
eta = 0.1
n_iterations = 1000
m = 100
alpha = 0.0001
theta = np.random.randn(2,1)

for iteration in range(n_iterations):
    gradients = 2/m * X_b.T.dot(X_b.dot(theta) - y) + alpha * theta[1:]
    theta = theta - eta * gradients
```

**Comment by ageron** [comment]
Thanks for your kind words @kasrahabib , I'm really glad you're enjoying my book! :)

* Why do we divide alpha by 2?

I suppose you meant alpha instead of lambda? Indeed, by doing this we simplify the derivatives, as it's just alpha * theta instead of 2 * alpha * theta.

* Why are we adding the regularization term to the loss instead of subtracting it?

If we add it to the loss, we encourage gradient descent to minimize it, since its goal is to make the loss as small as possible. This will push the model to have small weights, which is exactly what we want for regularization. If instead we subtracted the regularization term from the loss, Gradient Descent would try to make the weights as big as possible, since this would reduce the loss: this would be the opposite of what we want.

* Is your gradient descent implementation of ridge regression correct?

Almost, but not quite. The term you added to the gradients is `alpha * theta[1:]`, which is a vector of shape [1, 1]. However, the original gradients have a shape of [2, 1], so when you add a [1, 1] array, NumPy performs broadcasting, meaning it adds the value in the [1, 1] array to each and every gradient in the gradient array. In other words, you will be adding the regularization term for theta_1 to the gradients of theta_0 and theta_1.

To fix this, one approach is to do this:

```python
    gradients = 2/m * X_b.T.dot(X_b.dot(theta) - y)
    gradients[1:] += alpha * theta[1:]
```

Hope this helps!

**Comment by kasrahabib** [comment]
Hi @ageron 
Thanks from your kind guidance.
I am struggling with a new problem for fun & experience I used your learning curve codes from chapter 4's notebook for a sentiment analysis project while passing the X and y for the function it throws error: 

ValueError: The number of classes has to be greater than one; got 1 class

<img width="561" alt="Screen Shot 2019-10-15 at 1 21 11 PM" src="https://user-images.githubusercontent.com/29026528/66816222-f9444800-ef4e-11e9-9c44-105d43c97d1f.png">

First I was thinking that my labels are string so i did checked them they are int16.  So I guess that it is the X. Because, after transformation X changes to sparse matrix and this migh cause the problem.

Thanks in advace,
kasra

**Comment by ageron** [comment]
Hi @kasrahabib ,
Thanks for your question. The error message says "The number of classes has to be greater than one; got 1 class". This means that Scikit-Learn thinks the labels only contain a single class. Could you please double check that there are at least two different values in the labels `y`?
Could you please run this and copy/paste the result in this thread?


```python
print("X", repr(X[:10])) # a look at the first 10 elements of X
print("y", repr(y[:10])) # and y
print(repr(np.unique(y)[:10])) # and the first 10 distinct elements of y
```

**Comment by kasrahabib** [comment]
Hi again,
Yes it shows two distinct classes. Here is the output:

<img width="1033" alt="Screen Shot 2019-10-17 at 8 25 29 PM" src="https://user-images.githubusercontent.com/29026528/67026130-7244ca80-f11c-11e9-9705-c60e0e1ecce2.png">

**Comment by ageron** [comment]
Oh, I think I found the problem. In the notebook, we're tackling a regression problem while you are trying to tackle a classification problem. The bug occurs in the following section within the `plot_learning_curve()` function (you can see that in the exception's stacktrace):

```python
for m in range(1, len(X_train)):
    model.fit(X_train[:m], y_train[:m])   # error
    [...]
```

As you can see, we're trying to train the model with just 1 instance, then 2, then 3, and so on. With a regression model that's fine, but with a classification model it's not. Indeed, when we try to train the model on a single instance, there's a single class, and classifiers don't like being trained on a single class.

In your case, the first two instances belong to two different classes, so you can probably fix the problem just by replacing `range(1, len(X_train))` with `range(2, len(X_train))`. However, the code will break if you try with another classification dataset whose first two instances belong to the same class. So instead you may want to add some logic to determine the proper starting point. Perhaps something like this (untested code):

```python
n_classes = len(np.unique(y_train))
for start_at in range(2, len(X_train)):
    if len(np.unique(y_train[:start_at])) == n_classes:
        break

# Since we will skip the first `start_at` dataset sizes, we must fill in
# some values to plot. We'll just plot 0s.
train_errors = [0.] *start_at
val_errors = [0.] * start_at

for m in range(start_at, len(X_train)):
    model.fit(X_train[:m], y_train[:m])
    [...]
```

Hope this helps.

**Comment by kasrahabib** [comment]
Hi @ageron,

Thans and I really appreciate your help. It works perfectly.  I attached the  image (and the function wich I replaced the new code in it) in the below. And one more thing I want to make sure is, is it correct to replace the original mean square error form your ipython notebook with the hinge loss, since I am using  SGDClassifier's hinge loss function (i.e., My question is we should alwayse plot the errors for learning curves based on the cost function we choose for the clf to work with?).

```python
from sklearn.metrics import hinge_loss
from sklearn.model_selection import train_test_split

def plot_learning_curves(model, X, y):
    X_train, X_val, y_train, y_val = train_test_split(X, y, test_size=0.2, random_state=10)  
    n_classes = len(np.unique(y_train))
    for start_at in range(2, len(X_train)):
        if len(np.unique(y_train[:start_at])) == n_classes:
            break;
    
    train_errors = [0.] * start_at
    val_errors = [0.] * start_at
    
    for m in range(start_at, len(X_train), 100):
        model.fit(X_train[:m], y_train[:m]) 
        y_train_decision = sgd_clf.decision_function(X_train[:m])
        y_val_decision = sgd_clf.decision_function(X_val)
        train_errors.append(hinge_loss(y_train[:m], y_train_decision))
        val_errors.append(hinge_loss(y_val, y_val_decision))

    plt.plot(np.sqrt(train_errors), "r-+", linewidth=2, label="Training-Error")
    plt.plot(np.sqrt(val_errors), "b-", linewidth=3, label="Validation-Error")
    plt.legend(loc="upper right", fontsize=14)   
    plt.xlabel("Training set size", fontsize=14) 
    plt.ylabel("HING LOSS", fontsize=14)             
```
![Unknown-2](https://user-images.githubusercontent.com/29026528/68805193-ec676100-0680-11ea-85c2-5f771f5f1c18.png)


Besides that (from Chapter 5: SVM), I also want to ask one small question about the “Dual form of the linear SVM objective”. I did not get why we super script the value of vector $\mathbf{w}}$ with (i and j) while substituting back to the formula aren't they the same x's (the datapoint).

$
\begin{split}
&\hat{\mathbf{w}} = \sum_{i=1}^{m}{\hat{\alpha}}^{(i)}t^{(i)}\mathbf{x}^{(i)}\\
&\hat{b} = \dfrac{1}{n_s}\sum\limits_{\scriptstyle i=1 \atop {\scriptstyle {\hat{\alpha}}^{(i)} > 0}}^{m}{\left(1 - t^{(i)}({\hat{\mathbf{w}}}^T \cdot \mathbf{x}^{(i)})\right)}
\end{split}
$
