### ISSUE TITLE
Batch gradient descent theta does not updated

### ISSUE THREAD

**Issue by alparslanuysal** [ageron/handson-ml#49]
Hi @ageron , in [chapter 4](https://github.com/ageron/handson-ml/blob/master/04_training_linear_models.ipynb), section Linear regression using batch gradient descent following code does not update `theta`. Am a missing something? 

```python
eta = 0.1
n_iterations = 1000
m = 100
theta = np.random.randn(2,1)

for iteration in range(n_iterations):
    gradients = 2/m * X_b.T.dot(X_b.dot(theta) - y)
    theta = theta - eta * gradients 
```

**Comment by ageron** [comment]
Hi @alparslanuysal ,

Well actually the last line of this code does update `theta`:  I could have written instead `theta -= eta * gradients`, but I wanted it to look like the equation.

Cheers,
Aurélien

**Comment by Kellym-Kainos** [comment]
Answer to this issue: https://github.com/ageron/handson-ml/issues/16 , adding:

`from __future__ import division`

to your notebook if using Python 2 also solves this.
