### ISSUE TITLE
Chapter 16 exercise 9 solution

### ISSUE THREAD

**Issue by DCtheTall** [ageron/handson-ml#490]
Since a solution to chapter 16 exercise 9 is currently not in this repository,
would an owner of this repo approve a PR which copies [my solution](https://github.com/DCtheTall/hands-on-machine-learning/blob/master/chapter16/Exercises.ipynb) (taking out the Colab specific parts) into this repository?

**Comment by ageron** [comment]
That would be absolutely awesome, thanks a lot @DCtheTall !
Could you please add an intro or outro paragraph to give yourself proper credit? Something like this:
"Big thanks to [Dylan Cutler](https://github.com/DCtheTall) who created the solution to this exercise."
👍
