### ISSUE TITLE
CH7 p.188 Typo on line 15

### ISSUE THREAD

**Issue by nazihkalo** [ageron/handson-ml#499]
When discussing OOB validation the text reads:
“For example, the oob evaluation estimates that the second training instance has a 60.6% probability of belonging to the positive class (and 39.4% of belonging to the positive class):”

Should say positive for the first percentage.

**Comment by ageron** [comment]
Thanks @nazihkalo , indeed this was an error in an earlier release of the first edition, I fixed it some time ago so newer releases (as well as the 2nd edition) do not have the error anymore.

Note: for any further text-related errata, please submit them at https://homl.info/errata2 . Github is best for the errors in the code.

Cheers!
