### ISSUE TITLE
I don't understand the exercise 5 of chapter 2

### ISSUE THREAD

**Issue by arnau6610** [ageron/handson-ml#508]
This is the code:

```python
param_grid = [{
    'preparation__num__imputer__strategy': ['mean', 'median', 'most_frequent'],
    'feature_selection__k': list(range(1, len(feature_importances) + 1))
}]

grid_search_prep = GridSearchCV(prepare_select_and_predict_pipeline, param_grid, cv=5,
                                scoring='neg_mean_squared_error', verbose=2)
grid_search_prep.fit(housing, housing_labels)
```

`prepare_select_and_predict_pipeline` is the following pipeline:

```python
preparation_and_feature_selection_pipeline= Pipeline([
    ('preparation', full_pipeline),
    ('feature_selection', TopFeatureSelector(feature_importances, k))
])
```

What I don't understand is how does `GridSearchCV` know that `preparation__num__imputers__strategy`  refers to a hyperparameter of the `SimpleImputer` transformer  and `feature_selection__k`  refers to the hyperparameter `k` of the `TopFeatureSelector` transformer. 

I would appreciate a response, this is something that I am not able to understand despite trying.

**Comment by ageron** [comment]
Hi @arnau6610 ,

Great question! The `Pipeline` class uses a naming convention whereby double underscores `__` are used a bit like `/` separators in file paths. So you can think of `preparation__num__imputer__strategy` a bit like a file path `preparation/num/imputer/strategy`. Specifically, it refers to the `strategy` hyperparameter of the estimator named `imputer` within the pipeline named `num` within the pipeline named `preparation`. Thanks to this naming convention, you can refer to arbitrarily nested hyperparameters in a pipeline object.

Similarly, `feature_selection__k` is a bit like the path `feature_selection/k`: it's the hyperparameter `k` of the estimator named `feature_selection`.

Hope this helps.

**Comment by jamesonrader** [comment]
This should have been included at least in a footnote somewhere...

**Comment by ageron** [comment]
@jamesonrader , oh great catch, you're right, I really thought I wrote it somewhere in the book, but it seems that I forgot, sorry about that. I replaced the "Don't forget..." tip at the end of the Grid Search section with this:

> Remember that you can treat some of the data preparation steps as hyperparameters. For example, you could build an end-to-end pipeline (including all the steps from preprocessing to predictions), and use grid search to tune several hyperparameters simultaneously, including not only model hyperparameters, but also preprocessing hyperparameters. The grid search could automatically find out whether or not to add a feature you were not sure about (e.g., using the `add_bedrooms_per_room` hyperparameter of your `CombinedAttributesAdder` transformer). It may similarly be used to automatically find the best way to handle outliers, missing features, feature selection, and more.
> 
> When running grid search on a pipeline (or any other estimator which contains other estimators, such as a `ColumnTransformer`), each hyperparameter's name must be prefixed by the estimator's name in the pipeline, followed by two underscores. For example, `"imputer__strategy"` refers to the `strategy` hyperparameter of the estimator named `"imputer"`. This also works recursively (e.g., `a__b__c` refers to the hyperparameter `c` of the estimator named `"b"` inside the estimator named `"a"`).

Thanks for helping me improve the book! 👍
