### ISSUE TITLE
Pipeline Issue with Chapter 2 Problem 4

### ISSUE THREAD

**Issue by FezTheImmigrant** [ageron/handson-ml#509]
I'm currently trying to do problem 4, but I run into the following issue: 

`'NoneType' object has no attribute 'transform'`

The code I have is as follows -

`prepare_select_and_predict_pipeline = Pipeline([`
    `('preparation', full_pipeline),`
    `('feature_selection', TopFeatureSelector(feature_importances, k)),`
    `('svm_reg', SVR(**rand_grid_search.best_params_))`
`])`

`prepare_select_and_predict_pipeline.fit(housing, housing_labels)`

The issue lies within the SVR estimator. I don't know why it is trying to call transform when I'm only trying to fit anyways.

I fell like this is a bug with Pipeline because if I do -

 `SVR(**rand_grid_search.best_params_).fit` 

The model fits fine. For some reason the Pipeline tries to call fit_transform on SVR

**Comment by ageron** [comment]
Hi @FezTheImmigrant ,
Thanks for your question. Can you please copy/paste the full stacktrace, so I can see exactly where the error occurs. A frequent cause of such problems is when a custom transformer's `fit()` method does not return `self`. Please make sure that the `TopFeatureSelector` has a `fit()` method that returns `self`.
Hope this helps.

**Comment by FezTheImmigrant** [comment]
@ageron You are correct. I forgot to include `return self` in my fit function. Thank you!
