### ISSUE TITLE
Multi-gpu Implementation - RNNCell Error

### ISSUE THREAD

**Issue by francotheengineer** [ageron/handson-ml#51]
Hi,

I'm running the mutli-gpu code and it's throwing the error:
  File "/home/USER/Tensorflow_Models/Lstm-Rnn/model.py", line 68, in __init__
    dtype=tf.float32)
  File "/usr/lib/python3.4/site-packages/tensorflow/python/ops/rnn.py", line 508, in dynamic_rnn
    raise TypeError("cell must be an instance of RNNCell")
TypeError: cell must be an instance of RNNCell

Understanding of Error:  The dynamic_rnn module cannot deal with the new wrapper. Despite the wrapper being a RNNCell.
I've had a crack at trying to fix it but to no avail! Thanks!

Francos

**Comment by francotheengineer** [comment]
solved it. So basically, there is no need to used a custom cell wrapper. use tf.python.ops.nn.rnn_cell.DeviceCellWrapper  . Will commit changes.

devices = ["/gpu:0", "/gpu:1", "/gpu:2"]  # define gpus
        cells = []
        for dev in devices:
                cell = DeviceWrapper(rnn_cell.BasicLSTMCell(num_units=args.rnn_size), dev)
                cells.append(cell)

        self.multiple_lstm_cells = tf.contrib.rnn.MultiRNNCell(cells, state_is_tuple=True)
        self.initial_state = cell.zero_state(args.batch_size, tf.float32)

^^ this is training for me

**Comment by ageron** [comment]
Thanks for your feedback. I'm on vacation for the next couple of weeks, but I may be able to find a minute to check this out.  I took a quick look but I could not find the `DeviceCellWrapper`. What version of tensorflow do you have?

**Comment by francotheengineer** [comment]
I guessed that might have been the problem.  It's a very good book!

**Comment by ageron** [comment]
Hi @francotheengineer ,

I just updated the book to mention the fact that the `DeviceWrapper` class was added in TF 1.1.

Thanks a lot for your contribution.  :)

**Comment by francotheengineer** [comment]
It's an honor! :)
