### ISSUE TITLE
May be a mistake in Chapter 1,input[34]?

### ISSUE THREAD

**Issue by L0ngMarch** [ageron/handson-ml#510]
Should there be a 
`import sklearn.neighbors`
at the beginning?caus if it is missing, there will be a error
`module 'sklearn' has no attribute 'neighbors'`
Or maybe this only happen on my computer?

**Comment by ageron** [comment]
Good catch, thanks! I had fixed this in the [2nd edition notebook](https://github.com/ageron/handson-ml2/blob/master/01_the_machine_learning_landscape.ipynb) but I forgot to do the same in the [1st edition notebook](https://github.com/ageron/handson-ml/blob/master/01_the_machine_learning_landscape.ipynb). Just fixed that, thanks.
