### ISSUE TITLE
"titanic" is missing.

### ISSUE THREAD

**Issue by xqihao** [ageron/handson-ml#520]
The Jupyter file "03_classification.ipynb" requires the "titanic", but the directory and the files associated with it are missing. I attach snapshot of the errors. Please help fix it.

![image](https://user-images.githubusercontent.com/53481591/69784426-a85e7b00-11ad-11ea-81d9-26e46c6b65a7.png)

**Comment by ageron** [comment]
Thanks for your feedback, you need to get the data from https://www.kaggle.com/c/titanic.
Hope this helps!

**Comment by xqihao** [comment]
Thank you.
