### ISSUE TITLE
facing problem with virtualenv and tarfile in chapter 2

### ISSUE THREAD

**Issue by oniika-rohatgi** [ageron/handson-ml#552]
Hello Ageron,
I am using anaconda version 4.5.12, pip version 18.1, PYTHON version 3.7. I am facing two problem in chapter 2 
1 while creating virtual environment it is throwing following error
 'virtualenv' is not recognized as an internal or external command, operable program or batch file.

2 I have tried both commands pip install tarfile and conda install tarfile. it is throwing following error
Could not find a version that satisfies the requirement tarfile (from versions: )
No matching distribution found for tarfile

**Comment by DhruvAwasthi** [comment]
#552 
Greetings @oniika-rohatgi 
1. The steps to create and activate a virtual environment that you are asking for is given here in this link. You can check it out and see if it resolves the issue:
[https://uoa-eresearch.github.io/eresearch-cookbook/recipe/2014/11/20/conda/](url)
2. You don't need to install `tarfile` instead, you can directly import it within your notebook as it comes preloaded here:
`import tarfile` 

I hope this resolves the issue.

**Comment by oniika-rohatgi** [comment]
Thank you for the link.
