### ISSUE TITLE
Latex errors

### ISSUE THREAD

**Issue by egafni** [ageron/handson-ml#57]
Getting "unknown character" renders of some equations in 
https://github.com/ageron/handson-ml/blob/master/math_linear_algebra.ipynb

for example, in the Main properties section of Dot Product.  Is it just me?  I've tried chrome and safari.

**Comment by egafni** [comment]
Also, thanks for putting together such great material!

**Comment by egafni** [comment]
Equations load if i clone the repo and open the notebook in jupyter, so that's good news.  So look like it's just a limitation of github's ipynb viewer

**Comment by ageron** [comment]
Thanks for your feedback and your kind words. :)
Indeed, github's notebook viewer is pretty bad at rendering equations.  You can either use [Jupyter's viewer](http://nbviewer.jupyter.org/github/ageron/handson-ml/blob/master/book_equations.ipynb) or do as you did, i.e. clone the repo and run Jupyter on your machine.
Cheers!
