### ISSUE TITLE
End-to-end Machine Learning project

### ISSUE THREAD

**Issue by artsuzy** [ageron/handson-ml#58]
Hi, Thank you for the great book. I have one question:
```
final_model = grid_search.best_estimator_

X_test = strat_test_set.drop("median_house_value", axis=1)
y_test = strat_test_set["median_house_value"].copy()

X_test_prepared = full_pipeline.transform(X_test)
final_predictions = final_model.predict(X_test_prepared)

final_mse = mean_squared_error(y_test, final_predictions)
final_rmse = np.sqrt(final_mse)
```

In this line of code `X_test_prepared = full_pipeline.transform(X_test)` why do we use just transform rather than fit_transform. Am I correctly understand that you do it because when you fit it with train_set you get parameters like std for `StandardScaler` and median for `imputer` etc. So for test_set we use these parameters for transform due to we can't get std, median etc on real examples(because we have only one example)

**Comment by ageron** [comment]
Hi @artsuzy,

Yes, you absolutely got it: during training, the `StandardScaler` finds the mean and standard deviation of the training set, and you want to transform any test data you get (after training) using these same values.  Here's one way to understand why: suppose you get just one test instance, what mean and std deviation would you be able to use, if not the ones measured during training?

Thanks for the kind words, btw. :)
Aurélien
