### ISSUE TITLE
 Unreadable Notebook: error: with 09_up_and_running_with_tensorflow.ipynb

### ISSUE THREAD

**Issue by yevgenyfrolov** [ageron/handson-ml#580]
![Unredable NOtebook 09_up_and_running_with_tensorflow](https://user-images.githubusercontent.com/67621003/89591978-23823180-d811-11ea-81ac-85aca53db1ea.JPG)
I get this Unreadable Notebook: error:

 09_up_and_running_with_tensorflow.ipynb NotJSONError('Notebook does not appear to be JSON: \'\\n\\n\\n\\n\\n<!DOCTYPE html>\\n<html lang="...')

**Comment by IgBell** [comment]
Hello, did you cope with the problem? I have the same issue nobody can help.

**Comment by ageron** [comment]
Hi @yevgenyfrolov ,
I'm not sure what the problem was, but it seems fixed now.
