### ISSUE TITLE
Trouble with fetch_openml

### ISSUE THREAD

**Issue by GiaGoswami** [ageron/handson-ml#594]
Hi! I was having trouble with fetch_openml. Here is the code line and the Error message :
Code : mnist = fetch_openml(dataname="MNIST original")
Error : TypeError: fetch_openml() got an unexpected keyword argument 'dataname'
I tried to change the name, but that didn't help. 
Does anyone know how I can fix this Error?

**Comment by Praful932** [comment]
@GiaGoswami if you want to use mnist you could do this `mnist = fetch_openml('mnist_784', version = 1)`

**Comment by GiaGoswami** [comment]
Thank you.

**Comment by GiaGoswami** [comment]
Never mind

**Comment by ageron** [comment]
Note that since Scikit-Learn 0.24, `fetch_openml()` returns a Pandas dataframe by default, which breaks the code in the book. So you need to add the argument `as_frame=False` to ask the function to return a NumPy array, as before.
