### ISSUE TITLE
Chapter 2 Housing - unable to get local issuer certificate

### ISSUE THREAD

**Issue by B-GW** [ageron/handson-ml#596]
Hello, I'm very new here but I'm trying to get the housing code to run however I'm getting a URLError. 

![image](https://user-images.githubusercontent.com/71794501/94082515-f59f7f00-fdb5-11ea-8b0a-9b01f1046d37.png)

Am I missing something? I cannot get passed this error and I've tried to fix it through my own terminal.Thanks in advance

**Comment by digitech-ai** [comment]
Try this temporary fix.

import ssl
ssl._create_default_https_context = ssl._create_unverified_context #added to suppress verification of security certificate

It will basically suppress the warning.

**Comment by B-GW** [comment]
Actually that did work. Thank you so much! I'm curious as well I'm getting a NameError: name 'fetch_housing_data' is not defined. but I'm copy pasting the code form the notebook into my Jupyter and I'm not sure how to resolve that. Can you help with that as well?

**Comment by digitech-ai** [comment]
It is there under "Get the data" section, right after "Setup".

Dont worry too much of code, if it still doesnt work just download the dataset.

**Comment by B-GW** [comment]
Yeah... I know I've got it all defined according to what the notebook is recommending... Anyways. I appreciate your help thank you very much. I'll download it.
