### ISSUE TITLE
do the codes in the book  have been updated to tf 1.0 ?

### ISSUE THREAD

**Issue by yebangyu** [ageron/handson-ml#6]
Dear Aurélien, 

I was noticed that your great book has been published 2 days ago from your twitter

So,   before published officially , do the codes in your book have also been updated to tf1.0 just as the online and digital version ?

thx a lot.

**Comment by ageron** [comment]
Hi @yebangyu, thanks for your interest.  Yes, I updated all the code examples in the book to TF 1.0.
