### ISSUE TITLE
Chapter 2/median_house_value, Length: 16512, dtype: float64>, dtype=object) cannot be considered a valid collection.

### ISSUE THREAD

**Issue by Al3xDo** [ageron/handson-ml#602]
Hi everyone,
I'm stuck in this error when i use 
`from sklearn.linear_model import LinearRegression

lin_reg= LinearRegression()
lin_reg.fit(housing_prepared, housing_labels)`
Here is the error log:
![12](https://user-images.githubusercontent.com/56794124/98387261-c605b700-2083-11eb-81b8-7a9d219b4dad.png)
![13](https://user-images.githubusercontent.com/56794124/98387441-f51c2880-2083-11eb-879b-aabad92a8d63.png)

**Comment by adityaparamesh** [comment]
replace `housing_labels = strat_train_set["median_house_value"].copy` to  `housing_labels = strat_train_set["median_house_value"].copy.()` and that will fix it
