### ISSUE TITLE
Macports: SSL error on running fetch_housing_data()

### ISSUE THREAD

**Issue by clenchedteeth** [ageron/handson-ml#617]
Related to #46, I get an error about SSL certificates. The solutions given in #46 assume that the official python installer was used. However, I am using a macports version of python, and the solutions in #46 do not cover this option. Using macports is one of the approaches that the book recommends, and this piece of code is the first "real" piece of code encountered in the book, so I consider this problem worth addressing in a separate bug report. 

Edit: Additionally, the solution e.g. #339 to run `pip3 install --upgrade certifi` did not work in my case.

**Comment by jamesonrader** [comment]
Try this, although it might not be super secure if you don't know where you are downloading from:

```
import ssl
ssl._create_default_https_context = ssl._create_unverified_context
```

**Comment by ageron** [comment]
Thanks for your feedback @clenchedteeth , I'm looking into it.

**Comment by clenchedteeth** [comment]
@ageron Works perfectly, thank you!
