### ISSUE TITLE
Chapter 3 Warning

### ISSUE THREAD

**Issue by DimitrisTrakos** [ageron/handson-ml#618]
![image](https://user-images.githubusercontent.com/72466785/109435251-3ca73580-7a22-11eb-9992-5a3af9fbf41b.png)

**skfolds = StratifiedKFold(n_splits=3, random_state=42)

It raised a warning  and so to avoid it this it should be :

skfolds = StratifiedKFold(n_splits=3, random_state=42 ,shuffle=True)**

**Comment by ageron** [comment]
Thanks for your feedback, @DimitrisTrakos, you're right. I fixed this error last year (in commit e8ee783f), so please update this project to the latest version (run `git pull`).
Hope this helps
