### ISSUE TITLE
Help Me Please!!!!!!!!!!!!!

### ISSUE THREAD

**Issue by Lance123456790** [ageron/handson-ml#632]
I wanted to install pandas-profiling in my pc and was unable to do so just because of hashes i am a absolute begginer help me please.

**Comment by kabartay** [comment]
Give us information about errors please. And which required libraries' versions you have already installed.

**Comment by Mr-Dheer** [comment]
Install Anaconda it already installs pandas for you to use in your Jupiter notebook :D
