### ISSUE TITLE
chapter 2 confidence interval- why t-distribution?

### ISSUE THREAD

**Issue by Nevermetyou65** [ageron/handson-ml#633]
Hi,

I've just finished the chapter 2 of this book. The book is so great but I have a few question regarding computing 95% confidence interval. Well in the book the code is something like this,

```python
from scipy import stats

confidence = 0.95
squared_error = (final_prediction - y_test) ** 2
print(len(squared_error))

np.sqrt(stats.t.interval(confidence, len(squared_error)-1, 
                        loc=squared_error.mean(),
                        scale=stats.sem(squared_error)))
```
My questions are
1. Is there a specific reason that you choose to find the interval from t-distribution??
2 . And why np.sqrt(interval)??(Is it because you squared the error??)

thank you

**Comment by Nevermetyou65** [comment]
> Hi,
> 
> I've just finished the chapter 2 of this book. The book is so great but I have a few question regarding computing 95% confidence interval. Well in the book the code is something like this,
> 
> ```python
> from scipy import stats
> 
> confidence = 0.95
> squared_error = (final_prediction - y_test) ** 2
> print(len(squared_error))
> 
> np.sqrt(stats.t.interval(confidence, len(squared_error)-1, 
>                         loc=squared_error.mean(),
>                         scale=stats.sem(squared_error)))
> ```
> 
> My questions are
> 
> 1. Is there a specific reason that you choose to find the interval from t-distribution??
>    2 . And why np.sqrt(interval)??(Is it because you squared the error??)
> 
> thank you

**Comment by ageron** [comment]
Hi @Nevermetyou65 ,
Thanks for your questions, and sorry for the late reply.

1. The Central Limit Theorem guarantees that the sampling distribution of the sample means tends towards a Normal distribution as the sample size gets larger and larger. However, a t-distribution is more accurate for smaller sample sizes. It has fatter tails than the Normal distribution. The t-distribution gets really close to the Normal distribution for large sample sizes, so using it works in all cases, whether the sample size is small or large. Note that the population we're sampling from here is the squared errors of all possible predictions from the model. The squared errors most likely don't have a Normal distribution, but that's okay, we're taking the mean of a sample of squared errors, so the CRT applies.
2. Once we have a confidence interval for the mean squared error (MSE), if we want a confidence interval for the RMSE, we must compute the square root of the MSE interval.

Hope this helps

**Comment by Nevermetyou65** [comment]
Thank you so much for your replying.
