### ISSUE TITLE
mnist dataset

### ISSUE THREAD

**Issue by cherifseye** [ageron/handson-ml#644]
Hello I want to download the mnist dataset but I get this error, can you help me to fix this issue?
Thanks
![Screen Shot 2021-12-07 at 8 47 56 AM](https://user-images.githubusercontent.com/74331175/145042587-26ddeaf6-d013-43fa-8eae-fb9ba2957438.png)

**Comment by ageron** [comment]
Hi @cherifseye ,

Thanks for your question. This is a very common question.

You probably need to install the SSL certificates (see this [StackOverflow question](https://stackoverflow.com/questions/27835619/urllib-and-ssl-certificate-verify-failed-error)). If you downloaded Python from the official website, then run `/Applications/Python\ 3.7/Install\ Certificates.command` in a terminal (change `3.7` to whatever version you installed). If you installed Python using MacPorts, run sudo port install curl-ca-bundle in a terminal.

That said, I think you'll have less installation problems if you run this project on Miniconda. Please follow the [installation instructions](https://github.com/ageron/handson-ml2/blob/master/INSTALL.md).

Hope this helps.

**Comment by cherifseye** [comment]
Thanks it works
Kind regards
