### ISSUE TITLE
Broken image in readme

### ISSUE THREAD

**Issue by klieret** [ageron/handson-ml#660]
![image](https://user-images.githubusercontent.com/13602468/185795133-1ffa4029-790c-4d05-8e09-8931851b1135.png)

**Comment by ageron** [comment]
Good catch, thanks. Note that this repository is outdated, it was for the 1st edition of my book. The 3rd edition is about to come out (in October 2022), and its repository is located at https://github.com/ageron/handson-ml3
Thanks again!
