### ISSUE TITLE
Typo in 11_deep_learning.ipynb

### ISSUE THREAD

**Issue by Sangwon91** [ageron/handson-ml#69]
In cell 57, I think it should be
```python
hidden3 = tf.get_default_graph().get_tensor_by_name("dnn/hidden3/Relu:0")
```
but in the cell,
```python
hidden3 = tf.get_default_graph().get_tensor_by_name("dnn/hidden4/Relu:0")
```

Also, In my opinion, the graph view is more intuitive with "dnn" namespace for the new layers.

```python
new_hidden4 = tf.layers.dense(hidden3, n_hidden4, activation=tf.nn.relu, name="dnn/new_hidden4")
new_logits = tf.layers.dense(new_hidden4, n_outputs, name="dnn/new_outputs")
```
![graph](https://user-images.githubusercontent.com/20216145/28995389-0ce74342-7a23-11e7-9cd4-65ddd3f31aa6.PNG)

This book is one of the best books in my life. Thank you

**Comment by ageron** [comment]
Hi @Sangwon91,

Thanks a lot for your kind words, I really appreciate it and I'm glad you find my book useful.

Indeed, you are right, there was a typo in cell [57].  I just fixed it, and I will push the updated notebook shortly.

Thanks for your help!
