### ISSUE TITLE
Invalid number of arguments when preparing full pipeline housing data

### ISSUE THREAD

**Issue by jasrys** [ageron/handson-ml#75]
Hi Aurélien - 

Thanks for the informative book. Much appreciated. Following along in the Chapter 2 housing example I hit an error when calling `full_pipeline.fit_transform(housing)`. I thought I must have missed something but I cloned the 02_end_to_end notebook and still get the same invalid number of arguments error. Any ideas?

Thanks!

```
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-277-020337ad7bee> in <module>()
----> 1 housing_prepared = full_pipeline.fit_transform(housing)
      2 housing_prepared

/usr/local/lib/python3.6/site-packages/sklearn/pipeline.py in fit_transform(self, X, y, **fit_params)
    744             delayed(_fit_transform_one)(trans, weight, X, y,
    745                                         **fit_params)
--> 746             for name, trans, weight in self._iter())
    747 
    748         if not result:

/usr/local/lib/python3.6/site-packages/sklearn/externals/joblib/parallel.py in __call__(self, iterable)
    777             # was dispatched. In particular this covers the edge
    778             # case of Parallel used with an exhausted iterator.
--> 779             while self.dispatch_one_batch(iterator):
    780                 self._iterating = True
    781             else:

/usr/local/lib/python3.6/site-packages/sklearn/externals/joblib/parallel.py in dispatch_one_batch(self, iterator)
    623                 return False
    624             else:
--> 625                 self._dispatch(tasks)
    626                 return True
    627 

/usr/local/lib/python3.6/site-packages/sklearn/externals/joblib/parallel.py in _dispatch(self, batch)
    586         dispatch_timestamp = time.time()
    587         cb = BatchCompletionCallBack(dispatch_timestamp, len(batch), self)
--> 588         job = self._backend.apply_async(batch, callback=cb)
    589         self._jobs.append(job)
    590 

/usr/local/lib/python3.6/site-packages/sklearn/externals/joblib/_parallel_backends.py in apply_async(self, func, callback)
    109     def apply_async(self, func, callback=None):
    110         """Schedule a func to be run"""
--> 111         result = ImmediateResult(func)
    112         if callback:
    113             callback(result)

/usr/local/lib/python3.6/site-packages/sklearn/externals/joblib/_parallel_backends.py in __init__(self, batch)
    330         # Don't delay the application, to avoid keeping the input
    331         # arguments in memory
--> 332         self.results = batch()
    333 
    334     def get(self):

/usr/local/lib/python3.6/site-packages/sklearn/externals/joblib/parallel.py in __call__(self)
    129 
    130     def __call__(self):
--> 131         return [func(*args, **kwargs) for func, args, kwargs in self.items]
    132 
    133     def __len__(self):

/usr/local/lib/python3.6/site-packages/sklearn/externals/joblib/parallel.py in <listcomp>(.0)
    129 
    130     def __call__(self):
--> 131         return [func(*args, **kwargs) for func, args, kwargs in self.items]
    132 
    133     def __len__(self):

/usr/local/lib/python3.6/site-packages/sklearn/pipeline.py in _fit_transform_one(transformer, weight, X, y, **fit_params)
    587                        **fit_params):
    588     if hasattr(transformer, 'fit_transform'):
--> 589         res = transformer.fit_transform(X, y, **fit_params)
    590     else:
    591         res = transformer.fit(X, y, **fit_params).transform(X)

/usr/local/lib/python3.6/site-packages/sklearn/pipeline.py in fit_transform(self, X, y, **fit_params)
    290         Xt, fit_params = self._fit(X, y, **fit_params)
    291         if hasattr(last_step, 'fit_transform'):
--> 292             return last_step.fit_transform(Xt, y, **fit_params)
    293         elif last_step is None:
    294             return Xt

TypeError: fit_transform() takes 2 positional arguments but 3 were given
```

**Comment by gr3ybr0w** [comment]
I also have found this issue. Seem like there is an issue with using the pipeline and the LabelBinarizer()
To over come this I have used sklearn-pandas 1.5.0

`
from sklearn_pandas import DataFrameMapper

# record median values for total_bedrooms
total_bedrooms_median = housing.total_bedrooms.median()
# fill missing values
housing.total_bedrooms.fillna(value=total_bedrooms_median, inplace=True)

# making new features with pandas
housing['rooms_per_household'] = housing.total_rooms / housing.households
housing['population_per_household'] = housing.population / housing.households
housing['bedrooms_per_room'] = housing.total_bedrooms / housing.total_rooms

mapper = DataFrameMapper([
    (['longitude'], [Imputer(strategy="median"),
                     StandardScaler()]),
    (['latitude'], [Imputer(strategy="median"),
                    StandardScaler()]),
    (['housing_median_age'], [Imputer(strategy="median"),
                              StandardScaler()]),
    (['total_rooms'], [Imputer(strategy="median"),
                       StandardScaler()]),
    (['total_bedrooms'], [Imputer(strategy="median"),
                          StandardScaler()]),
    (['population'], [Imputer(strategy="median"),
                      StandardScaler()]),
    (['households'], [Imputer(strategy="median"),
                      StandardScaler()]),
    (['median_income'], [Imputer(strategy="median"),
                         StandardScaler()]),
    ('ocean_proximity', LabelBinarizer()),
    (['rooms_per_household'], StandardScaler()),
    (['population_per_household'], StandardScaler()),
    (['bedrooms_per_room'], StandardScaler())
])

housing_prepared = mapper.fit_transform(housing)
housing_prepared.shape
`

This is best made into a function so that the test set can be quickly used with it.

**Comment by Nirmal-Ramjee** [comment]
Hi

I am having the same issues. I have tried what was mentioned by gr3ybr0w but still am getting the same error. Any ideas what I am missing?

`from sklearn.pipeline import FeatureUnion

full_pipeline = FeatureUnion(transformer_list=[
        ("num_pipeline", num_pipeline),
        ("cat_pipeline", cat_pipeline),
    ])`

`housing_prepared = full_pipeline.fit_transform(housing)
housing_prepared`

> ---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-90-020337ad7bee> in <module>()
----> 1 housing_prepared = full_pipeline.fit_transform(housing)
      2 housing_prepared

/usr/local/lib/python2.7/dist-packages/sklearn/pipeline.pyc in fit_transform(self, X, y, **fit_params)
    744             delayed(_fit_transform_one)(trans, weight, X, y,
    745                                         **fit_params)
--> 746             for name, trans, weight in self._iter())
    747 
    748         if not result:

/usr/local/lib/python2.7/dist-packages/sklearn/externals/joblib/parallel.pyc in __call__(self, iterable)
    777             # was dispatched. In particular this covers the edge
    778             # case of Parallel used with an exhausted iterator.
--> 779             while self.dispatch_one_batch(iterator):
    780                 self._iterating = True
    781             else:

/usr/local/lib/python2.7/dist-packages/sklearn/externals/joblib/parallel.pyc in dispatch_one_batch(self, iterator)
    623                 return False
    624             else:
--> 625                 self._dispatch(tasks)
    626                 return True
    627 

/usr/local/lib/python2.7/dist-packages/sklearn/externals/joblib/parallel.pyc in _dispatch(self, batch)
    586         dispatch_timestamp = time.time()
    587         cb = BatchCompletionCallBack(dispatch_timestamp, len(batch), self)
--> 588         job = self._backend.apply_async(batch, callback=cb)
    589         self._jobs.append(job)
    590 

/usr/local/lib/python2.7/dist-packages/sklearn/externals/joblib/_parallel_backends.pyc in apply_async(self, func, callback)
    109     def apply_async(self, func, callback=None):
    110         """Schedule a func to be run"""
--> 111         result = ImmediateResult(func)
    112         if callback:
    113             callback(result)

/usr/local/lib/python2.7/dist-packages/sklearn/externals/joblib/_parallel_backends.pyc in __init__(self, batch)
    330         # Don't delay the application, to avoid keeping the input
    331         # arguments in memory
--> 332         self.results = batch()
    333 
    334     def get(self):

/usr/local/lib/python2.7/dist-packages/sklearn/externals/joblib/parallel.pyc in __call__(self)
    129 
    130     def __call__(self):
--> 131         return [func(*args, **kwargs) for func, args, kwargs in self.items]
    132 
    133     def __len__(self):

/usr/local/lib/python2.7/dist-packages/sklearn/pipeline.pyc in _fit_transform_one(transformer, weight, X, y, **fit_params)
    587                        **fit_params):
    588     if hasattr(transformer, 'fit_transform'):
--> 589         res = transformer.fit_transform(X, y, **fit_params)
    590     else:
    591         res = transformer.fit(X, y, **fit_params).transform(X)

/usr/local/lib/python2.7/dist-packages/sklearn/pipeline.pyc in fit_transform(self, X, y, **fit_params)
    290         Xt, fit_params = self._fit(X, y, **fit_params)
    291         if hasattr(last_step, 'fit_transform'):
--> 292             return last_step.fit_transform(Xt, y, **fit_params)
    293         elif last_step is None:
    294             return Xt

TypeError: fit_transform() takes exactly 2 arguments (3 given)

**Comment by Rydez** [comment]
Hello there,

Same problem. Check out this link for a different method to perform one hot encoding:
[https://github.com/ageron/handson-ml/issues/55](url)

**Comment by nirmalramjee** [comment]
Hi

I tried following the steps from issue 55 but am getting the same error. Does not seem to work. 

Please let me know if there is anything else I can do

Thanks!

**Comment by Freyert** [comment]
@jasrys I'm having the same issue as you and I think I've isolated it to the `DataFrameSelector`'s implementation:

```
from sklearn.base import BaseEstimator, TransformerMixin

class DataFrameSelector(BaseEstimator, TransformerMixin):
    def __init__(self, attribute_names):
        self.attribute_names = attribute_names
    def fit(self, X, y=None):
        return self
    def transform(self, X):
        return X[self.attribute_names].values
```

It all seems correct though, but when I remove the DataFrameSelector from the pipeline it proceeds and I get a different error.

This is what my pipeline looks like when I get your error @jasrys:

```
from sklearn.pipeline import FeatureUnion

num_attribs = list(housing_num)
cat_attribs = ["ocean_proximity"]

num_pipeline = Pipeline([
        ('selector', DataFrameSelector(num_attribs)),
        ('imputer', Imputer(strategy="median")),
        ('attribs_adder', CombinedAttributesAdder()),
        ('std_scaler', StandardScaler()),
    ])

cat_pipeline = Pipeline([
        ('selector', DataFrameSelector(cat_attribs)),
        ('label_binarizer', LabelBinarizer()),
    ])

full_pipeline = FeatureUnion(transformer_list=[
        ("num_pipeline", num_pipeline),
        ("cat_pipeline", cat_pipeline)
    ])

full_pipeline.fit_transform(housing)
TypeError: fit_transform() takes 2 positional arguments but 3 were given
```

**Comment by Freyert** [comment]
OK, got this working for myself:

Copy and paste this implementation of [`LabelBinarizerPipelineFriendly`](https://github.com/scikit-learn/scikit-learn/pull/7375/files#diff-1e175ddb0d84aad0a578d34553f6f9c6) into your notebook:

```python
class LabelBinarizerPipelineFriendly(LabelBinarizer):
    def fit(self, X, y=None):
        """this would allow us to fit the model based on the X input."""
        super(LabelBinarizerPipelineFriendly, self).fit(X)
    def transform(self, X, y=None):
        return super(LabelBinarizerPipelineFriendly, self).transform(X)

    def fit_transform(self, X, y=None):
        return super(LabelBinarizerPipelineFriendly, self).fit(X).transform(X)
```

Thanks @Kallin for pointing this out in issue #55 and @hesenp for the implementation. From reading #55 this seems like a workaround and not at all ideal.

**Comment by nirmalramjee** [comment]
@Freyert, could you share your notebook with me please. Thanks.

**Comment by Freyert** [comment]
```python
from sklearn.base import BaseEstimator, TransformerMixin

#credit to @hesenp 
class LabelBinarizerPipelineFriendly(LabelBinarizer):
    def fit(self, X, y=None):
        """this would allow us to fit the model based on the X input."""
        super(LabelBinarizerPipelineFriendly, self).fit(X)
    def transform(self, X, y=None):
        return super(LabelBinarizerPipelineFriendly, self).transform(X)

    def fit_transform(self, X, y=None):
        return super(LabelBinarizerPipelineFriendly, self).fit(X).transform(X)


class DataFrameSelector(BaseEstimator, TransformerMixin):
    def __init__(self, attribute_names):
        self.attribute_names = attribute_names
    def fit(self, X, y=None):
        return self
    def transform(self, X):
        return X[self.attribute_names].values

from sklearn.pipeline import FeatureUnion

num_attribs = list(housing_num)
cat_attribs = ["ocean_proximity"]

num_pipeline = Pipeline([
        ('selector', DataFrameSelector(num_attribs)),
        ('imputer', Imputer(strategy="median")),
        ('attribs_adder', CombinedAttributesAdder()),
        ('std_scaler', StandardScaler()),
    ])

cat_pipeline = Pipeline([
        ('selector', DataFrameSelector(cat_attribs)),
        ('label_binarizer', LabelBinarizerPipelineFriendly()),
    ])

full_pipeline = FeatureUnion(transformer_list=[
        ("num_pipeline", num_pipeline),
        ("cat_pipeline", cat_pipeline)
    ])
```

**Comment by jasrys** [comment]
Fantastic, that custom binarizer transformer works perfectly @Freyert. Thanks!

**Comment by dustbort** [comment]
According to the documentation, LabelBinarizer does not work on the 2-dimensional input X the way you intend.
http://scikit-learn.org/stable/modules/generated/sklearn.preprocessing.LabelBinarizer.html

```
fit(y)
Parameters: | y : array of shape [n_samples,] or [n_samples, n_classes]  
Target values. The 2-d matrix should only contain 0 and 1, represents multilabel classification.
```
Similarly for `transform(y)` and `fit_transform(y)`.

So, it seems to treat the columns of the 2-d matrix X as a single multiple-label classification feature with Boolean entries, not multiple single-label classification features. I guess it just treats zero as False and non-zero as True, and although it seems to run OK, the behavior should be quite different than you intend. Or have I misunderstood?

**Comment by NirajNair** [comment]
@Freyert thanks for the solution.

**Comment by PatChandresh** [comment]
you can try this code

**from sklearn.compose import ColumnTransformer

housing_prepared = full_pipeline.fit_transform(housing)
housing_prepared.shape**

**Comment by PatChandresh** [comment]
> from sklearn.compose import ColumnTransformer

housing_prepared = full_pipeline.fit_transform(housing)
housing_prepared.shape
