### ISSUE TITLE
ch.14: Generating a creative new sequence: charts go exponential!

### ISSUE THREAD

**Issue by DarrenCook** [ageron/handson-ml#78]
I've been working through 14_recurrent_neural_networks, from top to bottom; the two "testing the model" charts look just like in the book, but instead of Figure 14-11 (p.396) I get:

![index](https://user-images.githubusercontent.com/880436/29754012-0f349fba-8b75-11e7-979d-d35ae22eded2.png)

I'm using the jupyter notebooks downloaded 2 or 3 days ago.
Mint 18, python 3, and these pip packages:
  tensorflow-gpu (1.3.0)
  tensorflow-tensorboard (0.1.5)

cuda 8.0, and cuDnn v6.

I'm curious if you (Aurelian, or anyone else) see the same problem with TensorFlow 1.3; if not, it must be something with my environment??

**Comment by ageron** [comment]
Hi @DarrenCook ,

Have you tried tweaking the parameters a bit? I remember getting some of those exponential sequences a few times during my initial experiments: not all generated sequences looked great, and I only got good ones after a bit of hyperparameter tweaking.  What's probably happening is that the network learned that when the sequence looks like an exponential curve, then it should keep accelerating up.  I has not learned properly that at one point this upward trend needs to stop!

Please try playing around with the hyperparameters and tell me if you can manage to get a nice looking sequence.  If you really can't no matter how much you try, then there might be another problem, and I'll look into it.

Thanks!
Aurélien

**Comment by ageron** [comment]
Closing this issue, please reopen if needed after trying the above suggestions. Thanks!
