### ISSUE TITLE
ch.13: image preprocessing for inception_v3 slightly off

### ISSUE THREAD

**Issue by marksgraham** [ageron/handson-ml#80]
Hi Aurélien, thanks for the great book!

When you prepare images for transfer learning in chapter 13 in the function prepare_image(), you scale them between 0 and 1:

```
def prepare_image(image, target_width = 299, target_height = 299, max_zoom = 0.2):
    ...skip a load of code...
    # Finally, the Convolution Neural Network expects colors represented as
    # 32-bit floats ranging from 0.0 to 1.0:
    return image.astype(np.float32) / 255
```

But in the training of inception_v3 (found [here](https://github.com/tensorflow/models/blob/master/slim/preprocessing/inception_preprocessing.py)) images were scaled between -1 and 1, by subtracting 0.5 and then multiplying by 2:

```
def preprocess_for_train(image, height, width, bbox,
                         fast_mode=True,
                         scope=None):
    ...skip a load of code...
    distorted_image = tf.subtract(distorted_image, 0.5)
    distorted_image = tf.multiply(distorted_image, 2.0)
    return distorted_image
```
You can verify this function was used for the training of inception_v3 by taking a look in the function get_preprocessing() in [preprocessing_factory.py](https://github.com/tensorflow/models/blob/master/slim/preprocessing/preprocessing_factory.py).

I wasn't able to check whether correcting this improves performance on the flower classification task in your notebook, because my GPU doesn't have enough memory to check the test accuracy, but correcting the preprocessing step for some of my own networks gave me a ~1% boost in test accuracy. 

I'd be happy to submit a pull request with a fix if it would be helpful.

**Comment by ageron** [comment]
Hi @marksgraham ,
Nice catch! I've just fixed the code, I'm training the network, and if all goes well I'll push this by Monday.

Thanks so much for your help. :+1:

**Comment by ageron** [comment]
Done, thanks again!
