### ISSUE TITLE
Command '['conda', 'info', '--json']' returned non-zero exit status 255

### ISSUE THREAD

**Issue by ittayd** [ageron/handson-ml#85]
Working with the instructions to setup with Anaconda, `jupyter notebook` exists with an error 
`subprocess.CalledProcessError: Command '['conda', 'info', '--json']' returned non-zero exit status 255`

Running `conda info --json` in the shell returns a status 0

**Comment by cuent** [comment]
This error happens when Anaconda is not in your `PATH` variable. Please check [this](https://github.com/ContinuumIO/anaconda-issues/issues/921).

**Comment by ageron** [comment]
Thanks @ittayd for your question, and thanks @cuent for answering. :)
@ittayd, did this solve your issue?

**Comment by ageron** [comment]
Closing the issue.  @ittayd , please reopen if the problem persists after following the instructions by @cuent .
