### ISSUE TITLE
Chap 9, p.248, California housing dataset: "BadZipFile: File is not a zip file"

### ISSUE THREAD

**Issue by dpnolan** [ageron/handson-ml#9]
Hi, I'm getting an error message when I try to run this code on Chapter 9, p.248.  Any suggestions for solving this please or is the resource link broken?

from sklearn.datasets import fetch_california_housing
housing = fetch_california_housing()
m, n = housing.data.shape
housing_data_plus_bias = np.c_[np.ones((m, 1)), housing.data]

The final error message is 
BadZipFile: File is not a zip file

**Comment by ageron** [comment]
Hi @dpnolan ,

That's odd, I just tried it and everything worked fine.  Perhaps it's a temporary connectivity issue or server error? Could you please retry?

Here's my output:

```
Python 3.5.3 (default, Jan 19 2017, 14:11:04) 
[GCC 6.3.0 20170118] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from sklearn.datasets import fetch_california_housing
>>> housing = fetch_california_housing()
downloading Cal. housing from http://www.dcc.fc.up.pt/~ltorgo/Regression/cal_housing.tgz to /home/ageron/scikit_learn_data
>>> m,n=housing.data.shape
>>> housing_data_plus_bias = np.c_[np.ones((m,1)), housing.data]
>>> housing_data_plus_bias
array([[   1.        ,    8.3252    ,   41.        , ...,    2.55555556,
          37.88      , -122.23      ],
       [   1.        ,    8.3014    ,   21.        , ...,    2.10984183,
          37.86      , -122.22      ],
       [   1.        ,    7.2574    ,   52.        , ...,    2.80225989,
          37.85      , -122.24      ],
       ..., 
       [   1.        ,    1.7       ,   17.        , ...,    2.3256351 ,
          39.43      , -121.22      ],
       [   1.        ,    1.8672    ,   18.        , ...,    2.12320917,
          39.43      , -121.32      ],
       [   1.        ,    2.3886    ,   16.        , ...,    2.61698113,
          39.37      , -121.24      ]])

```

Notice the URL where Scikit-Learn fetches the data. By default, this tgz file is saved to `~/scikit_learn_data`:

```
$ ls -l ~/scikit_learn_data/
total 372
-rw-r--r-- 1 ageron ageron 366877 avril 16 22:37 cal_housing_py3.pkz
drwxr-xr-x 2 ageron ageron   4096 avril  8 14:21 mldata
```

Perhaps this file exists on your machine, but it is corrupted? If so, try deleting it, then try again.

**Comment by dpnolan** [comment]
Hi Aurélien, I have this working on the Python 2 version when I run that. There seem to be some problems with my Anaconda setup, so I will re-install. I should perhaps not start off with chapter 9.  Thanks.  It's a great book.  Peter

**Comment by ageron** [comment]
@dpnolan I'm really glad you enjoy the book, thanks for your feedback and good luck with your installation.
