### ISSUE TITLE
13_convolutional_neural_networks Exercise 8.2

### ISSUE THREAD

**Issue by CharlesFr** [ageron/handson-ml#94]
Link to the Inception v3 model checkpoint is broken.

**Comment by CharlesFr** [comment]
Unrelated note on the book: I love how you talk us through building models in the early chapters, it's very nice to be explained each step and being able to replicate it without have to go into your notebook. However, as we get into more complex models such as CNN this is completely lost. It would be fantastic if you talked through the MNIST you have in the exercise. Despite having read everything it's hard to understand the example without any annotations. I would be very grateful if you could do so!

**Comment by ageron** [comment]
Thanks @CharlesFr ,

Indeed, the link is broken.  :(
They moved the slim directory to: https://github.com/tensorflow/models/tree/master/research/slim
I'll update the notebook and the book, thanks a lot!

Note that this URL issue did not prevent the code from working, since the download URL has not changed (yet?).

Regarding your suggestion, I had to keep things short because I was way over the target number of pages for the book, but I will add more details in the notebook. Would that be okay?

**Comment by CharlesFr** [comment]
Thanks for the link.

That was my suspicion, however I find the step by step guides offer the most educational value - perhaps  something to keep in mind for your next book. Nonetheless, annotation on the example would be great.

Your prompt responses are also much appreciated!

**Comment by michael-GitHub-0** [comment]
Aurelien is so cool. I had the opportunity to chat with him in his Safari course. If he ever needs a place to stay in Canada, I'll put him up AND make him breakfast.

As you found, I did find that the more complex models were explained in a bit less detail than the earlier material (now I know why) but Aurelien really made an extra effort in the notebooks. If he can augment those even further, he would be the coolest guy EVER. I hope everyone appreciates him as much as I do. I am going to order another copy of the book and give it to a friend.

**Comment by nmvega** [comment]
&gt;&gt; I hope everyone appreciates him as much as I do. I am going to order another copy of the book and give it to a friend.



Me, too!

--

Noel Milton Vega | PRISMALYTICS, LLC. | www.prismalytics.io
P: 212.882.1279 |  nmvega@prismalytics.io












---- On Mon, 16 Oct 2017 22:20:20 -0400 michael-GitHub-0 &lt;notifications@github.com&gt; wrote ----




Aurelien is so cool. I had the opportunity to chat with him in his Safari course. If he ever needs a place to stay in Canada, I'll put him up AND make him breakfast.

As you found, I did find that the more complex models were explained in a bit less detail than the earlier material (now I know why) but Aurelien really made an extra effort in the notebooks. If he can augment those even further, he would be the coolest guy EVER. I hope everyone appreciates him as much as I do. I am going to order another copy of the book and give it to a friend.

**Comment by ageron** [comment]
You guys are soooo kind, thank you very very much!  :))

I'm working on the exercises (for chapter 14 right now), and once I'm done I plan to polish the notebooks a bit, by adding more explanations, in particular in the later chapters.

Thanks again for being so positive and encouraging, it means a lot to me.
