### ISSUE TITLE
Chapter 9: saver.restore is throwing session closed error! 

### ISSUE THREAD

**Issue by dixiematt8** [ageron/handson-ml#95]
The following lines throws session is closed error.
```
with tf.Session() as sess:
    saver.restore(sess, "/tmp/my_model_final.ckpt")
    best_theta_restored = theta.eval() # not shown in the book
```
I had to manually open and close. It fixed the problem.
```
sess=tf.Session()
saver.restore(sess,'./tmp/my_model_final.ckpt')
best_theta_restored=sess.run(theta)
sess.close()

```

**Comment by ageron** [comment]
Hi, thanks for your feedback. That's really odd, there should be no difference (except that you are not using the same filepath in both versions). I just tried, it's working fine for me. Could you please check the filepaths, and if it still fails, please give me more details about your environment: TensorFlow version, python version, O.S. and so on so I can reproduce the issue.

**Comment by dixiematt8** [comment]
You can close the issue. I couldn't able to replicate error after I restarted the kernel. Sorry. Couldn't determine why?  I swear to God,  I got that error.

**Comment by ageron** [comment]
Thanks for letting me know.  No worries, it's computer science, restarting is often the correct solution! :)
