### ISSUE TITLE
Chapter 13 - Convolutional Neural Network

### ISSUE THREAD

**Issue by bright1993ff66** [ageron/handson-ml#97]
I am doing the convolutional neural network here and I have one question about the code using in constructing the filters. The code is the following:

```Python
fmap = np.zeros(shape=(7, 7, 1, 2), dtype=np.float32) # shape = (height, width, channel, #filters)
fmap[:, 3, 0, 0] = 1
fmap[3, :, 0, 1] = 1
fmap[:, :, 0, 0]
plot_image(fmap[:, :, 0, 0])
plt.show()
plot_image(fmap[:, :, 0, 1])
plt.show()`
```
I want to know the meaning of 

```Python
fmap[:, :, 0, 0] 
```
in the code above. I have no idea what this code is about and if I erased it, the outputs are still the same.  Can anybody explain this to me? Cheers!

**Comment by ageron** [comment]
Oops, good catch.  This line doesn't do a thing, it must be a copy & paste mistake.  I'll remove it, sorry about that.

**Comment by bright1993ff66** [comment]
No worries, this book is so great! I will keep learning it~
